-- Taxonomy master import pack for Impronta.
-- Data only; no schema changes.
-- Canonical location still lives on public.talent_profiles.location_id.

BEGIN;

DO $$
BEGIN
  ALTER TYPE public.taxonomy_kind ADD VALUE IF NOT EXISTS 'location_city';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  ALTER TYPE public.taxonomy_kind ADD VALUE IF NOT EXISTS 'location_country';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

COMMIT;

BEGIN;

INSERT INTO public.taxonomy_terms (
  kind,
  slug,
  name_en,
  name_es,
  aliases,
  sort_order
)
VALUES
  ('talent_type', 'model', 'Model', 'Modelo', ARRAY['modelo'], 10),
  ('talent_type', 'fashion-model', 'Fashion Model', 'Modelo de moda', ARRAY['fashion talent'], 20),
  ('talent_type', 'editorial-model', 'Editorial Model', 'Modelo editorial', ARRAY['editorial talent'], 30),
  ('talent_type', 'commercial-model', 'Commercial Model', 'Modelo comercial', ARRAY['advertising model'], 40),
  ('talent_type', 'promotional-model', 'Promotional Model', 'Modelo promocional', ARRAY['promo model'], 50),
  ('talent_type', 'hostess', 'Hostess', 'Anfitriona', ARRAY['hostess talent'], 60),
  ('talent_type', 'brand-ambassador', 'Brand Ambassador', 'Embajador(a) de marca', ARRAY['brand rep'], 70),
  ('talent_type', 'influencer', 'Influencer', 'Influencer', ARRAY['creator influencer'], 80),
  ('talent_type', 'actor', 'Actor', 'Actor/Actriz', ARRAY['screen talent'], 90),
  ('talent_type', 'performer', 'Performer', 'Artista', ARRAY['live performer'], 100),
  ('talent_type', 'dancer', 'Dancer', 'Bailarin(a)', ARRAY['dance talent'], 110),
  ('talent_type', 'dj', 'DJ', 'DJ', ARRAY['disc jockey'], 120),
  ('talent_type', 'entertainer', 'Entertainer', 'Animador(a)', ARRAY['show talent'], 130),
  ('talent_type', 'fitness-model', 'Fitness Model', 'Modelo fitness', ARRAY['athletic model'], 140),
  ('talent_type', 'runway-model', 'Runway Model', 'Modelo de pasarela', ARRAY['catwalk model'], 150),
  ('talent_type', 'trade-show-model', 'Trade Show Model', 'Modelo para expo', ARRAY['expo model'], 160),
  ('talent_type', 'luxury-model', 'Luxury Model', 'Modelo de lujo', ARRAY['premium model'], 170),
  ('talent_type', 'lifestyle-model', 'Lifestyle Model', 'Modelo lifestyle', ARRAY['lifestyle talent'], 180),
  ('talent_type', 'catalog-model', 'Catalog Model', 'Modelo de catalogo', ARRAY['ecommerce model'], 190),
  ('talent_type', 'showroom-model', 'Showroom Model', 'Modelo de showroom', ARRAY['showroom talent'], 200),
  ('talent_type', 'event-model', 'Event Model', 'Modelo para eventos', ARRAY['event talent'], 210),
  ('talent_type', 'presenter', 'Presenter', 'Presentador(a)', ARRAY['presenting talent'], 220),
  ('talent_type', 'mc', 'MC', 'Maestro(a) de ceremonias', ARRAY['emcee'], 230),
  ('talent_type', 'content-creator', 'Content Creator', 'Creador(a) de contenido', ARRAY['creator'], 240),
  ('talent_type', 'singer', 'Singer', 'Cantante', ARRAY['vocal talent'], 250),
  ('talent_type', 'musician', 'Musician', 'Musico(a)', ARRAY['instrumentalist'], 260),
  ('talent_type', 'athlete-talent', 'Athlete Talent', 'Talento atletico', ARRAY['sports talent'], 270),
  ('talent_type', 'mascot-performer', 'Mascot Performer', 'Performer de mascota', ARRAY['costumed performer'], 280),

  ('tag', 'luxury', 'Luxury', 'Lujo', ARRAY[]::text[], 10),
  ('tag', 'bilingual', 'Bilingual', 'Bilingue', ARRAY[]::text[], 20),
  ('tag', 'premium', 'Premium', 'Premium', ARRAY[]::text[], 30),
  ('tag', 'vip', 'VIP', 'VIP', ARRAY[]::text[], 40),
  ('tag', 'featured', 'Featured', 'Destacado(a)', ARRAY[]::text[], 50),
  ('tag', 'international', 'International', 'Internacional', ARRAY[]::text[], 60),
  ('tag', 'local-talent', 'Local Talent', 'Talento local', ARRAY[]::text[], 70),
  ('tag', 'experienced', 'Experienced', 'Con experiencia', ARRAY[]::text[], 80),
  ('tag', 'new-face', 'New Face', 'Nuevo(a)', ARRAY[]::text[], 90),
  ('tag', 'high-energy', 'High Energy', 'Alta energia', ARRAY[]::text[], 100),
  ('tag', 'professional', 'Professional', 'Profesional', ARRAY[]::text[], 110),
  ('tag', 'camera-ready', 'Camera Ready', 'Listo(a) para camara', ARRAY[]::text[], 120),
  ('tag', 'event-specialist', 'Event Specialist', 'Especialista en eventos', ARRAY[]::text[], 130),
  ('tag', 'travel-ready', 'Travel Ready', 'Disponible para viajar', ARRAY[]::text[], 140),
  ('tag', 'corporate-friendly', 'Corporate Friendly', 'Ideal corporativo', ARRAY[]::text[], 150),
  ('tag', 'elegant', 'Elegant', 'Elegante', ARRAY[]::text[], 160),
  ('tag', 'sporty', 'Sporty', 'Deportivo(a)', ARRAY[]::text[], 170),
  ('tag', 'nightlife', 'Nightlife', 'Nightlife', ARRAY['club-friendly'], 180),
  ('tag', 'editorial-look', 'Editorial Look', 'Look editorial', ARRAY[]::text[], 190),
  ('tag', 'natural-look', 'Natural Look', 'Look natural', ARRAY[]::text[], 200),
  ('tag', 'commercial-friendly', 'Commercial Friendly', 'Ideal comercial', ARRAY[]::text[], 210),
  ('tag', 'polished', 'Polished', 'Pulido(a)', ARRAY[]::text[], 220),
  ('tag', 'outgoing', 'Outgoing', 'Extrovertido(a)', ARRAY[]::text[], 230),
  ('tag', 'reliable', 'Reliable', 'Confiable', ARRAY[]::text[], 240),
  ('tag', 'punctual', 'Punctual', 'Puntual', ARRAY[]::text[], 250),
  ('tag', 'on-camera', 'On Camera', 'Bueno(a) en camara', ARRAY[]::text[], 260),
  ('tag', 'crowd-friendly', 'Crowd Friendly', 'Conecta con publico', ARRAY[]::text[], 270),
  ('tag', 'stage-ready', 'Stage Ready', 'Listo(a) para escenario', ARRAY[]::text[], 280),
  ('tag', 'wellness', 'Wellness', 'Wellness', ARRAY[]::text[], 290),
  ('tag', 'beach-look', 'Beach Look', 'Look de playa', ARRAY[]::text[], 300),
  ('tag', 'resort-style', 'Resort Style', 'Estilo resort', ARRAY[]::text[], 310),

  ('skill', 'runway', 'Runway', 'Pasarela', ARRAY['catwalk'], 10),
  ('skill', 'hosting', 'Hosting', 'Presentacion', ARRAY['host'], 20),
  ('skill', 'dancing', 'Dancing', 'Baile', ARRAY[]::text[], 30),
  ('skill', 'public-speaking', 'Public Speaking', 'Oratoria', ARRAY[]::text[], 40),
  ('skill', 'acting', 'Acting', 'Actuacion', ARRAY[]::text[], 50),
  ('skill', 'product-demo', 'Product Demo', 'Demostracion de producto', ARRAY[]::text[], 60),
  ('skill', 'sales', 'Sales', 'Ventas', ARRAY[]::text[], 70),
  ('skill', 'brand-activation', 'Brand Activation', 'Activacion de marca', ARRAY[]::text[], 80),
  ('skill', 'crowd-engagement', 'Crowd Engagement', 'Interaccion con publico', ARRAY[]::text[], 90),
  ('skill', 'modeling', 'Modeling', 'Modelaje', ARRAY[]::text[], 100),
  ('skill', 'fitness', 'Fitness', 'Fitness', ARRAY[]::text[], 110),
  ('skill', 'social-media', 'Social Media', 'Redes sociales', ARRAY[]::text[], 120),
  ('skill', 'influencer-marketing', 'Influencer Marketing', 'Marketing de influencers', ARRAY[]::text[], 130),
  ('skill', 'promotions', 'Promotions', 'Promociones', ARRAY[]::text[], 140),
  ('skill', 'stage-performance', 'Stage Performance', 'Performance en escenario', ARRAY[]::text[], 150),
  ('skill', 'event-support', 'Event Support', 'Apoyo en eventos', ARRAY[]::text[], 160),
  ('skill', 'improvisation', 'Improvisation', 'Improvisacion', ARRAY[]::text[], 170),
  ('skill', 'bilingual-hosting', 'Bilingual Hosting', 'Presentacion bilingue', ARRAY[]::text[], 180),
  ('skill', 'interview-speaking', 'Interview Speaking', 'Entrevistas', ARRAY[]::text[], 190),
  ('skill', 'live-streaming', 'Live Streaming', 'Transmision en vivo', ARRAY[]::text[], 200),
  ('skill', 'choreography', 'Choreography', 'Coreografia', ARRAY[]::text[], 210),
  ('skill', 'emceeing', 'Emceeing', 'Maestria de ceremonias', ARRAY['mc'], 220),
  ('skill', 'customer-engagement', 'Customer Engagement', 'Relacion con clientes', ARRAY[]::text[], 230),
  ('skill', 'retail-promo', 'Retail Promo', 'Promocion retail', ARRAY[]::text[], 240),
  ('skill', 'luxury-service', 'Luxury Service', 'Servicio de lujo', ARRAY[]::text[], 250),
  ('skill', 'product-education', 'Product Education', 'Educacion de producto', ARRAY[]::text[], 260),
  ('skill', 'script-reading', 'Script Reading', 'Lectura de guion', ARRAY[]::text[], 270),
  ('skill', 'voice-over', 'Voice Over', 'Locucion', ARRAY[]::text[], 280),
  ('skill', 'posing', 'Posing', 'Posado', ARRAY[]::text[], 290),
  ('skill', 'team-lead', 'Team Lead', 'Lider de equipo', ARRAY[]::text[], 300),
  ('skill', 'multilingual-speaking', 'Multilingual Speaking', 'Comunicacion multilingue', ARRAY[]::text[], 310),

  ('industry', 'fashion', 'Fashion', 'Moda', ARRAY[]::text[], 10),
  ('industry', 'hospitality', 'Hospitality', 'Hospitalidad', ARRAY[]::text[], 20),
  ('industry', 'nightlife', 'Nightlife', 'Vida nocturna', ARRAY[]::text[], 30),
  ('industry', 'corporate', 'Corporate', 'Corporativo', ARRAY[]::text[], 40),
  ('industry', 'luxury-events', 'Luxury Events', 'Eventos de lujo', ARRAY[]::text[], 50),
  ('industry', 'trade-shows', 'Trade Shows', 'Expos', ARRAY[]::text[], 60),
  ('industry', 'automotive', 'Automotive', 'Automotriz', ARRAY[]::text[], 70),
  ('industry', 'technology', 'Technology', 'Tecnologia', ARRAY[]::text[], 80),
  ('industry', 'real-estate', 'Real Estate', 'Bienes raices', ARRAY[]::text[], 90),
  ('industry', 'tourism', 'Tourism', 'Turismo', ARRAY[]::text[], 100),
  ('industry', 'food-beverage', 'Food and Beverage', 'Alimentos y bebidas', ARRAY['fnb'], 110),
  ('industry', 'beauty', 'Beauty', 'Belleza', ARRAY[]::text[], 120),
  ('industry', 'fitness', 'Fitness', 'Fitness', ARRAY[]::text[], 130),
  ('industry', 'music', 'Music', 'Musica', ARRAY[]::text[], 140),
  ('industry', 'entertainment', 'Entertainment', 'Entretenimiento', ARRAY[]::text[], 150),
  ('industry', 'health-wellness', 'Health and Wellness', 'Salud y wellness', ARRAY[]::text[], 160),
  ('industry', 'cosmetics', 'Cosmetics', 'Cosmeticos', ARRAY[]::text[], 170),
  ('industry', 'travel-luxury', 'Travel Luxury', 'Viaje de lujo', ARRAY[]::text[], 180),
  ('industry', 'resorts', 'Resorts', 'Resorts', ARRAY[]::text[], 190),
  ('industry', 'weddings', 'Weddings', 'Bodas', ARRAY[]::text[], 200),
  ('industry', 'sports', 'Sports', 'Deportes', ARRAY[]::text[], 210),
  ('industry', 'fintech', 'Fintech', 'Fintech', ARRAY[]::text[], 220),
  ('industry', 'telecom', 'Telecom', 'Telecom', ARRAY[]::text[], 230),
  ('industry', 'spirits', 'Spirits', 'Bebidas espirituosas', ARRAY[]::text[], 240),
  ('industry', 'retail', 'Retail', 'Retail', ARRAY[]::text[], 250),
  ('industry', 'lifestyle', 'Lifestyle', 'Lifestyle', ARRAY[]::text[], 260),
  ('industry', 'conventions', 'Conventions', 'Convenciones', ARRAY[]::text[], 270),
  ('industry', 'gaming', 'Gaming', 'Gaming', ARRAY[]::text[], 280),
  ('industry', 'art-culture', 'Art and Culture', 'Arte y cultura', ARRAY[]::text[], 290),
  ('industry', 'yachting', 'Yachting', 'Yates', ARRAY[]::text[], 300),
  ('industry', 'property-development', 'Property Development', 'Desarrollo inmobiliario', ARRAY[]::text[], 310),

  ('event_type', 'trade-show', 'Trade Show', 'Expo', ARRAY[]::text[], 10),
  ('event_type', 'corporate-event', 'Corporate Event', 'Evento corporativo', ARRAY[]::text[], 20),
  ('event_type', 'brand-activation', 'Brand Activation', 'Activacion de marca', ARRAY[]::text[], 30),
  ('event_type', 'nightclub-event', 'Nightclub Event', 'Evento en nightclub', ARRAY[]::text[], 40),
  ('event_type', 'private-party', 'Private Party', 'Fiesta privada', ARRAY[]::text[], 50),
  ('event_type', 'luxury-event', 'Luxury Event', 'Evento de lujo', ARRAY[]::text[], 60),
  ('event_type', 'product-launch', 'Product Launch', 'Lanzamiento de producto', ARRAY[]::text[], 70),
  ('event_type', 'conference', 'Conference', 'Conferencia', ARRAY[]::text[], 80),
  ('event_type', 'expo', 'Expo', 'Expo', ARRAY[]::text[], 90),
  ('event_type', 'festival', 'Festival', 'Festival', ARRAY[]::text[], 100),
  ('event_type', 'wedding', 'Wedding', 'Boda', ARRAY[]::text[], 110),
  ('event_type', 'vip-event', 'VIP Event', 'Evento VIP', ARRAY[]::text[], 120),
  ('event_type', 'photoshoot', 'Photoshoot', 'Sesion de fotos', ARRAY[]::text[], 130),
  ('event_type', 'commercial-shoot', 'Commercial Shoot', 'Grabacion comercial', ARRAY[]::text[], 140),
  ('event_type', 'promotional-campaign', 'Promotional Campaign', 'Campana promocional', ARRAY[]::text[], 150),
  ('event_type', 'store-opening', 'Store Opening', 'Apertura de tienda', ARRAY[]::text[], 160),
  ('event_type', 'convention', 'Convention', 'Convencion', ARRAY[]::text[], 170),
  ('event_type', 'gala', 'Gala', 'Gala', ARRAY[]::text[], 180),
  ('event_type', 'yacht-event', 'Yacht Event', 'Evento en yate', ARRAY[]::text[], 190),
  ('event_type', 'resort-event', 'Resort Event', 'Evento en resort', ARRAY[]::text[], 200),
  ('event_type', 'hotel-activation', 'Hotel Activation', 'Activacion hotelera', ARRAY[]::text[], 210),
  ('event_type', 'pop-up-event', 'Pop-Up Event', 'Evento pop-up', ARRAY[]::text[], 220),
  ('event_type', 'beach-event', 'Beach Event', 'Evento de playa', ARRAY[]::text[], 230),
  ('event_type', 'tasting-event', 'Tasting Event', 'Evento de degustacion', ARRAY[]::text[], 240),
  ('event_type', 'sports-event', 'Sports Event', 'Evento deportivo', ARRAY[]::text[], 250),
  ('event_type', 'red-carpet', 'Red Carpet', 'Alfombra roja', ARRAY[]::text[], 260),
  ('event_type', 'influencer-event', 'Influencer Event', 'Evento de influencers', ARRAY[]::text[], 270),
  ('event_type', 'press-event', 'Press Event', 'Evento de prensa', ARRAY[]::text[], 280),
  ('event_type', 'launch-party', 'Launch Party', 'Fiesta de lanzamiento', ARRAY[]::text[], 290),
  ('event_type', 'networking-event', 'Networking Event', 'Evento de networking', ARRAY[]::text[], 300),

  ('fit_label', 'best-for-nightlife', 'Best for Nightlife', 'Ideal para nightlife', ARRAY[]::text[], 10),
  ('fit_label', 'best-for-corporate', 'Best for Corporate', 'Ideal corporativo', ARRAY[]::text[], 20),
  ('fit_label', 'best-for-luxury', 'Best for Luxury', 'Ideal para lujo', ARRAY[]::text[], 30),
  ('fit_label', 'best-for-promotions', 'Best for Promotions', 'Ideal para promociones', ARRAY[]::text[], 40),
  ('fit_label', 'best-for-trade-shows', 'Best for Trade Shows', 'Ideal para expos', ARRAY[]::text[], 50),
  ('fit_label', 'best-for-hosting', 'Best for Hosting', 'Ideal para presentacion', ARRAY[]::text[], 60),
  ('fit_label', 'best-for-acting', 'Best for Acting', 'Ideal para actuacion', ARRAY[]::text[], 70),
  ('fit_label', 'best-for-dancing', 'Best for Dancing', 'Ideal para baile', ARRAY[]::text[], 80),
  ('fit_label', 'best-for-fashion', 'Best for Fashion', 'Ideal para moda', ARRAY[]::text[], 90),
  ('fit_label', 'best-for-events', 'Best for Events', 'Ideal para eventos', ARRAY[]::text[], 100),
  ('fit_label', 'best-for-brand-activation', 'Best for Brand Activation', 'Ideal para activaciones', ARRAY[]::text[], 110),
  ('fit_label', 'best-for-hospitality', 'Best for Hospitality', 'Ideal para hospitalidad', ARRAY[]::text[], 120),
  ('fit_label', 'best-for-conferences', 'Best for Conferences', 'Ideal para conferencias', ARRAY[]::text[], 130),
  ('fit_label', 'best-for-resorts', 'Best for Resorts', 'Ideal para resorts', ARRAY[]::text[], 140),
  ('fit_label', 'best-for-yacht-events', 'Best for Yacht Events', 'Ideal para eventos en yate', ARRAY[]::text[], 150),
  ('fit_label', 'best-for-private-events', 'Best for Private Events', 'Ideal para eventos privados', ARRAY[]::text[], 160),
  ('fit_label', 'best-for-editorial', 'Best for Editorial', 'Ideal para editorial', ARRAY[]::text[], 170),
  ('fit_label', 'best-for-commercial', 'Best for Commercial', 'Ideal para comercial', ARRAY[]::text[], 180),
  ('fit_label', 'best-for-social-content', 'Best for Social Content', 'Ideal para contenido social', ARRAY[]::text[], 190),
  ('fit_label', 'best-for-runway', 'Best for Runway', 'Ideal para pasarela', ARRAY[]::text[], 200),
  ('fit_label', 'best-for-fitness', 'Best for Fitness', 'Ideal para fitness', ARRAY[]::text[], 210),
  ('fit_label', 'best-for-bilingual-events', 'Best for Bilingual Events', 'Ideal para eventos bilingues', ARRAY[]::text[], 220),

  ('language', 'en', 'English', 'Ingles', ARRAY[]::text[], 10),
  ('language', 'es', 'Spanish', 'Espanol', ARRAY[]::text[], 20),
  ('language', 'pt', 'Portuguese', 'Portugues', ARRAY[]::text[], 30),
  ('language', 'fr', 'French', 'Frances', ARRAY[]::text[], 40),
  ('language', 'it', 'Italian', 'Italiano', ARRAY[]::text[], 50),
  ('language', 'de', 'German', 'Aleman', ARRAY[]::text[], 60),
  ('language', 'he', 'Hebrew', 'Hebreo', ARRAY[]::text[], 70),
  ('language', 'ru', 'Russian', 'Ruso', ARRAY[]::text[], 80),
  ('language', 'ar', 'Arabic', 'Arabe', ARRAY[]::text[], 90),
  ('language', 'nl', 'Dutch', 'Neerlandes', ARRAY[]::text[], 100),
  ('language', 'tr', 'Turkish', 'Turco', ARRAY[]::text[], 110),
  ('language', 'sv', 'Swedish', 'Sueco', ARRAY[]::text[], 120),
  ('language', 'pl', 'Polish', 'Polaco', ARRAY[]::text[], 130),
  ('language', 'uk', 'Ukrainian', 'Ucraniano', ARRAY[]::text[], 140),
  ('language', 'ro', 'Romanian', 'Rumano', ARRAY[]::text[], 150),
  ('language', 'zh', 'Chinese', 'Chino', ARRAY[]::text[], 160),
  ('language', 'ja', 'Japanese', 'Japones', ARRAY[]::text[], 170),
  ('language', 'ko', 'Korean', 'Coreano', ARRAY[]::text[], 180),

  ('location_country', 'mx', 'Mexico', 'Mexico', ARRAY[]::text[], 10),
  ('location_country', 'es', 'Spain', 'Espana', ARRAY[]::text[], 20),
  ('location_country', 'us', 'United States', 'Estados Unidos', ARRAY[]::text[], 30),
  ('location_country', 'br', 'Brazil', 'Brasil', ARRAY[]::text[], 40),
  ('location_country', 'fr', 'France', 'Francia', ARRAY[]::text[], 50),
  ('location_country', 'ae', 'United Arab Emirates', 'Emiratos Arabes Unidos', ARRAY[]::text[], 60),

  ('location_city', 'cancun', 'Cancun', 'Cancun', ARRAY[]::text[], 10),
  ('location_city', 'playa-del-carmen', 'Playa del Carmen', 'Playa del Carmen', ARRAY[]::text[], 20),
  ('location_city', 'ibiza', 'Ibiza', 'Ibiza', ARRAY[]::text[], 30),
  ('location_city', 'tulum', 'Tulum', 'Tulum', ARRAY[]::text[], 40),
  ('location_city', 'madrid', 'Madrid', 'Madrid', ARRAY[]::text[], 50),
  ('location_city', 'barcelona', 'Barcelona', 'Barcelona', ARRAY[]::text[], 60),
  ('location_city', 'miami', 'Miami', 'Miami', ARRAY[]::text[], 70),
  ('location_city', 'los-angeles', 'Los Angeles', 'Los Angeles', ARRAY[]::text[], 80),
  ('location_city', 'sao-paulo', 'Sao Paulo', 'Sao Paulo', ARRAY[]::text[], 90),
  ('location_city', 'rio-de-janeiro', 'Rio de Janeiro', 'Rio de Janeiro', ARRAY[]::text[], 100),
  ('location_city', 'dubai', 'Dubai', 'Dubai', ARRAY[]::text[], 110),
  ('location_city', 'paris', 'Paris', 'Paris', ARRAY[]::text[], 120)
ON CONFLICT (kind, slug) DO UPDATE
SET name_en = EXCLUDED.name_en,
    name_es = EXCLUDED.name_es,
    aliases = EXCLUDED.aliases,
    sort_order = EXCLUDED.sort_order,
    archived_at = NULL,
    updated_at = now();

COMMIT;
