/**
 * Sentence keys for Package 3 refusals. The UI session reads these; the
 * engine returns the reason word only.
 */
export const VENUE_ENGINE_REFUSAL_CODES = [
  "duplicate_slug",
  "last_location",
  "has_spaces",
  "already_seated",
  "space_occupied",
  "expired",
  "overlap",
  "two_active",
  "station_in_use",
  "visit_closed",
  "item_unavailable",
  "already_paid",
  "exceeds_outstanding",
  "not_submitted",
  "seat_taken",
  "hold_expired",
  "same_session",
  "price_up_needs_payment",
  "needs_approval",
  "channel_unavailable",
  "superseded",
  "too_many_attempts",
  "unknown_device",
  "not_replayable",
  "stale_app",
  "conflict",
  "not_found",
  "wrong_tenant",
  "invalid",
  "unavailable",
  "not_allowed",
] as const;

export type VenueEngineRefusal = (typeof VENUE_ENGINE_REFUSAL_CODES)[number];

export const VENUE_ENGINE_REFUSALS: Readonly<Record<VenueEngineRefusal, string>> = {
  duplicate_slug: "dashboard.venue.engine.refusal.duplicate_slug",
  last_location: "dashboard.venue.engine.refusal.last_location",
  has_spaces: "dashboard.venue.engine.refusal.has_spaces",
  already_seated: "dashboard.venue.engine.refusal.already_seated",
  space_occupied: "dashboard.venue.engine.refusal.space_occupied",
  expired: "dashboard.venue.engine.refusal.expired",
  overlap: "dashboard.venue.engine.refusal.overlap",
  two_active: "dashboard.venue.engine.refusal.two_active",
  station_in_use: "dashboard.venue.engine.refusal.station_in_use",
  visit_closed: "dashboard.venue.engine.refusal.visit_closed",
  item_unavailable: "dashboard.venue.engine.refusal.item_unavailable",
  already_paid: "dashboard.venue.engine.refusal.already_paid",
  exceeds_outstanding: "dashboard.venue.engine.refusal.exceeds_outstanding",
  not_submitted: "dashboard.venue.engine.refusal.not_submitted",
  seat_taken: "dashboard.venue.engine.refusal.seat_taken",
  hold_expired: "dashboard.venue.engine.refusal.hold_expired",
  same_session: "dashboard.venue.engine.refusal.same_session",
  price_up_needs_payment: "dashboard.venue.engine.refusal.price_up_needs_payment",
  needs_approval: "dashboard.venue.engine.refusal.needs_approval",
  channel_unavailable: "dashboard.venue.engine.refusal.channel_unavailable",
  superseded: "dashboard.venue.engine.refusal.superseded",
  too_many_attempts: "dashboard.venue.engine.refusal.too_many_attempts",
  unknown_device: "dashboard.venue.engine.refusal.unknown_device",
  not_replayable: "dashboard.venue.engine.refusal.not_replayable",
  stale_app: "dashboard.venue.engine.refusal.stale_app",
  conflict: "dashboard.venue.engine.refusal.conflict",
  not_found: "dashboard.venue.engine.refusal.not_found",
  wrong_tenant: "dashboard.venue.engine.refusal.wrong_tenant",
  invalid: "dashboard.venue.engine.refusal.invalid",
  unavailable: "dashboard.venue.engine.refusal.unavailable",
  not_allowed: "dashboard.venue.engine.refusal.not_allowed",
};
