/**
 * event_program copy, es/en in-file like `ticket-picker-copy.ts`. Item text
 * arrives already localised from the loader (the row's `i18n` overlay); this
 * is only the block chrome. No em dashes.
 */
import type { ProgramLocale } from "./event-program-model";

export function pickProgramLocale(raw?: string): ProgramLocale {
  return raw?.toLowerCase().startsWith("es") ? "es" : "en";
}

export const PROGRAM_COPY: Record<ProgramLocale, Record<string, string>> = {
  en: {
    loading: "Loading the program...",
    not_configured: "This block is not set up yet: it needs an event whose program to show.",
    disabled: "The program is switched off for this event. Turn it on under the event's Program tab.",
    empty: "The program is on its way.",
    unavailable: "The program could not be loaded right now.",
    tba: "Time to be confirmed",
    performerTba: "Performer to be announced",
    now: "Now",
    nowLabel: "Happening now",
    nextDay: "next day",
    nights: "Nights",
    places: "Places",
    viewProfile: "View profile",
    close: "Close",
    reserveSpot: "Reserve a spot",
    seeMore: "See more",
    sponsoredBy: "With the support of",
    instagram: "Instagram",
    website: "Website",
    gallery: "Gallery",
    video: "Video",
    openDetails: "Open details",
    // Kind words, shown only with `showKind` as a tiny uppercase label; never a symbol.
    kind_set: "Set",
    kind_performance: "Performance",
    kind_talk: "Talk",
    kind_panel: "Panel",
    kind_workshop: "Workshop",
    kind_class: "Class",
    kind_ceremony: "Ceremony",
    kind_presentation: "Presentation",
    kind_service: "Service",
    kind_break: "Break",
    kind_competition: "Competition",
    kind_meet_greet: "Meet and greet",
    kind_afterparty: "Afterparty",
    kind_doors: "Doors",
    kind_close: "Close",
    kind_other: "Program",
  },
  es: {
    loading: "Cargando el programa...",
    not_configured: "Este bloque aún no está configurado: necesita un evento cuyo programa mostrar.",
    disabled: "El programa está apagado para este evento. Actívalo en la pestaña Programa del evento.",
    empty: "El programa está en camino.",
    unavailable: "No se pudo cargar el programa en este momento.",
    tba: "Hora por confirmar",
    performerTba: "Artista por anunciar",
    now: "En curso",
    nowLabel: "Sucediendo ahora",
    nextDay: "día siguiente",
    nights: "Noches",
    places: "Lugares",
    viewProfile: "Ver perfil",
    close: "Cerrar",
    reserveSpot: "Reservar lugar",
    seeMore: "Ver más",
    sponsoredBy: "Con el apoyo de",
    instagram: "Instagram",
    website: "Sitio web",
    gallery: "Galería",
    video: "Video",
    openDetails: "Abrir detalles",
    kind_set: "Set",
    kind_performance: "Actuación",
    kind_talk: "Charla",
    kind_panel: "Panel",
    kind_workshop: "Taller",
    kind_class: "Clase",
    kind_ceremony: "Ceremonia",
    kind_presentation: "Presentación",
    kind_service: "Servicio",
    kind_break: "Descanso",
    kind_competition: "Competencia",
    kind_meet_greet: "Meet and greet",
    kind_afterparty: "Afterparty",
    kind_doors: "Puertas",
    kind_close: "Cierre",
    kind_other: "Programa",
  },
};
