/** Nail Designer visible copy (EN is the owner's design text; ES added). No em dashes. */
export const NAIL_COPY = {
  en: {
    sub: "Design a manicure, nail by nail.",
    undo: "Undo",
    reset: "Reset",
    editing: "Editing",
    allNails: "All nails",
    oneNail: "One nail",
    only: "only",
    nailWord: "nail",
    selected: "selected",
    hint: "Tap a nail to style it on its own",
    surprise: "Surprise me",
    save: "Save look",
    applyTo: "Apply to",
    tabs: { color: "Color", art: "Art", finish: "Finish", shape: "Shape", extras: "Extras", looks: "Looks" },
    polish: "Polish",
    accent: "Accent",
    accentNote: "Used for tips, dots, stripes, moons and marbling.",
    customPolish: "Mix a custom polish",
    customAccent: "Mix a custom accent",
    nailArt: "Nail art",
    finish: "Finish",
    shape: "Shape",
    length: "Length",
    skinTone: "Skin tone",
    skinLabel: "Skin tone",
    charms: "Charms & stickers",
    charmsTip: "Tip: switch to one nail first for a single accent charm.",
    savedLooks: "Saved looks",
    myLook: "My look",
    toastReset: "Reset to the starter look",
    toastSaved: "Saved as",
    toastApplied: "Applied",
    toastSent: "Design ready. Add your details to send it.",
    send: "Send my design",
    stage: "Your design",
  },
  es: {
    sub: "Diseña una manicura, uña por uña.",
    undo: "Deshacer",
    reset: "Reiniciar",
    editing: "Editando",
    allNails: "Todas las uñas",
    oneNail: "Una uña",
    only: "solamente",
    nailWord: "uña",
    selected: "seleccionada",
    hint: "Toca una uña para diseñarla por separado",
    surprise: "Sorpréndeme",
    save: "Guardar diseño",
    applyTo: "Aplicar a",
    tabs: { color: "Color", art: "Arte", finish: "Acabado", shape: "Forma", extras: "Extras", looks: "Diseños" },
    polish: "Esmalte",
    accent: "Acento",
    accentNote: "Se usa en puntas, lunares, rayas, lunas y mármol.",
    customPolish: "Mezcla un esmalte propio",
    customAccent: "Mezcla un acento propio",
    nailArt: "Arte de uñas",
    finish: "Acabado",
    shape: "Forma",
    length: "Largo",
    skinTone: "Tono de piel",
    skinLabel: "Tono de piel",
    charms: "Accesorios y calcomanías",
    charmsTip: "Consejo: cambia primero a una uña para poner un solo accesorio.",
    savedLooks: "Diseños guardados",
    myLook: "Mi diseño",
    toastReset: "De vuelta al diseño inicial",
    toastSaved: "Guardado como",
    toastApplied: "Aplicado",
    toastSent: "Diseño listo. Agrega tus datos para enviarlo.",
    send: "Enviar mi diseño",
    stage: "Tu diseño",
  },
} as const;

export type NailCopy = (typeof NAIL_COPY)["en"] | (typeof NAIL_COPY)["es"];
