/**
 * ticket_picker copy + tiny formatters. Split from the island so the island
 * stays under the file cap; nothing here touches the DOM.
 */
export type Locale = "en" | "es";
export function pickLocale(raw?: string): Locale { return raw?.toLowerCase().startsWith("es") ? "es" : "en"; }
export function newOrderKey(): string {
  try { return crypto.randomUUID(); } catch {
    const r = () => Math.floor(Math.random() * 0x10000).toString(16).padStart(4, "0");
    return `${r()}${r()}-${r()}-4${r().slice(1)}-a${r().slice(1)}-${r()}${r()}${r()}`;
  }
}

export const COPY: Record<Locale, Record<string, string>> = {
  en: {
    heading: "Tickets",
    night: "Pick a night",
    tier: "Pick a ticket",
    loading: "Loading tickets...",
    not_configured: "This block is not set up yet: it needs an event to sell.",
    noNights: "No night is on sale yet.",
    noTiers: "No ticket is on sale for that night yet.",
    quantity: "How many",
    decrease: "Fewer",
    increase: "More",
    email: "Email",
    emailHelp: "Your ticket goes here. If you cannot open it, we will find you by name at the door.",
    emailPlaceholder: "you@email.com",
    promo: "Promo code",
    promoPlaceholder: "If you have one",
    promo_unknown: "That code is not recognised.",
    promo_not_started: "That code is not active yet.",
    promo_expired: "That code has ended.",
    promo_exhausted: "That code has been used up.",
    promo_customer_limit: "You have already used that code.",
    promo_not_applicable: "That code does not apply to this order.",
    name: "Name",
    namePlaceholder: "Your name",
    buy: "Buy with card",
    buyFree: "Get your ticket",
    free: "Free",
    admits: "admits {n}",
    payHow: "How will you pay",
    payCard: "Card now",
    payDoor: "At the door",
    payDoorHelp: "Your seats are held until the night ends. Pay at the door when you arrive. Offered only up to 7 days before the night.",
    holdDoor: "Holding your seats for the door...",
    heldDoor: "Your seats are held. Pay at the door when you arrive. Your receipt:",
    buying: "Holding your seats...",
    redirecting: "Taking you to payment...",
    door_opens_closer: "Paying at the door opens closer to the date.",
    door_doors_open: "Doors are open: pay at the door in person.",
    door_offered: "Paying at the door is available closer to the night.",
    sold_out: "That night just sold out at that ticket. Pick another and it is yours.",
    night_not_on_sale: "That night is no longer on sale. Pick another.",
    tier_not_on_sale: "That ticket is not on sale right now.",
    quantity_err: "That number of tickets is outside what one order can hold.",
    not_sellable: "This event is not on sale just now.",
    unavailable: "We could not load the tickets. Nothing was charged. Try again.",
    invalid_request: "Something in that did not look right. Check the details and try again.",
    engine_error: "Something went wrong at our end. Nothing was charged.",
    pay_at_door_not_yet: "Paying at the door is not available online yet. Pay by card, or at the door on the night.",
    pay_at_door_not_offered: "Paying at the door is not offered for that night.",
    emailRequired: "We need an email to send your ticket to.",
    not_found: "We could not find that order. Nothing was charged.",
    ageGate: "Age check",
    ageConfirm: "I am {n} or over",
    ageHelp: "Bring ID. Staff check at the door, and a ticket without ID is not admitted.",
    age_gate_unconfirmed: "Please confirm your age to continue.",
    age_gate_below_minimum: "This one has an age limit, so we cannot sell it to you.",
    seats: "Seats",
    holdSeats: "Hold seats",
    holdingSeats: "Holding seats...",
    heldUntil: "Held until {when}",
    seat_taken: "That seat was just taken.",
    hold_expired: "That hold ended. Pick the seats again.",
    step_tier: "Your ticket",
    step_qty: "How many",
    step_details: "Your details",
    continue: "Continue",
    back: "Back",
    total: "Total",
    openSheet: "Buy tickets",
    close: "Close",
    byInvitation: "By invitation only",
    includes: "Includes",
    each: "each",
  },
  es: {
    heading: "Entradas",
    night: "Elegí una noche",
    tier: "Elegí una entrada",
    loading: "Cargando entradas...",
    not_configured: "Este bloque aún no está configurado: necesita un evento para vender.",
    noNights: "Todavía no hay ninguna noche a la venta.",
    noTiers: "Todavía no hay entradas a la venta para esa noche.",
    quantity: "Cuántas",
    decrease: "Menos",
    increase: "Más",
    email: "Correo",
    emailHelp: "Tu entrada llega acá. Si no podés abrirla, te buscamos por tu nombre en la puerta.",
    emailPlaceholder: "tu@correo.com",
    name: "Nombre",
    namePlaceholder: "Tu nombre",
    buy: "Pagar con tarjeta",
    buyFree: "Conseguir entrada",
    free: "Gratis",
    admits: "admite {n}",
    payHow: "Como vas a pagar",
    payCard: "Tarjeta ahora",
    payDoor: "En la puerta",
    payDoorHelp: "Tus plazas quedan reservadas hasta que termine la noche. Pagas en la puerta al llegar. Solo hasta 7 dias antes de la noche.",
    holdDoor: "Reservando tus plazas para la puerta...",
    heldDoor: "Tus plazas estan reservadas. Pagas en la puerta al llegar. Tu recibo:",
    buying: "Reservando tus plazas...",
    redirecting: "Llevandote al pago...",
    door_opens_closer: "Pagar en la puerta se abre más cerca de la fecha.",
    door_doors_open: "Las puertas están abiertas: pagá en la puerta en persona.",
    door_offered: "Pagar en la puerta estará disponible más cerca de la noche.",
    sold_out: "Esa noche se acaba de agotar con esa entrada. Elegí otra y es tuya.",
    night_not_on_sale: "Esa noche ya no está a la venta. Elegí otra.",
    tier_not_on_sale: "Esa entrada no está a la venta ahora.",
    quantity_err: "Ese número de entradas está fuera de lo que admite un pedido.",
    not_sellable: "Este evento no está a la venta por ahora.",
    unavailable: "No pudimos cargar las entradas. No se cobró nada. Intentá de nuevo.",
    invalid_request: "Algo no se ve bien. Revisá los datos e intentá de nuevo.",
    engine_error: "Algo falló de nuestro lado. No se cobró nada.",
    pay_at_door_not_yet: "Pagar en la puerta aún no está disponible en línea. Pagá con tarjeta, o en la puerta esa noche.",
    pay_at_door_not_offered: "Pagar en la puerta no se ofrece para esa noche.",
    promo: "Código promocional",
    promoPlaceholder: "Si tenés uno",
    promo_unknown: "Ese código no se reconoce.",
    promo_not_started: "Ese código todavía no está activo.",
    promo_expired: "Ese código ya terminó.",
    promo_exhausted: "Ese código ya se usó por completo.",
    promo_customer_limit: "Ya usaste ese código.",
    promo_not_applicable: "Ese código no aplica a este pedido.",
    emailRequired: "Necesitamos un correo para enviarte la entrada.",
    not_found: "No encontramos ese pedido. No se cobró nada.",
    ageGate: "Control de edad",
    ageConfirm: "Tengo {n} años o más",
    ageHelp: "Traé documento. En la puerta lo revisan, y sin documento no se entra.",
    age_gate_unconfirmed: "Confirmá tu edad para continuar.",
    age_gate_below_minimum: "Esta entrada tiene límite de edad, así que no te la podemos vender.",
    seats: "Asientos",
    holdSeats: "Reservar asientos",
    holdingSeats: "Reservando asientos...",
    heldUntil: "Reservado hasta {when}",
    seat_taken: "Ese asiento acaba de ocuparse.",
    hold_expired: "Esa reserva terminó. Elegí los asientos de nuevo.",
    step_tier: "Tu entrada",
    step_qty: "Cuántas",
    step_details: "Tus datos",
    continue: "Continuar",
    back: "Volver",
    total: "Total",
    openSheet: "Comprar entradas",
    close: "Cerrar",
    byInvitation: "Solo por invitación",
    includes: "Incluye",
    each: "c/u",
  },
};

export function formatWhen(iso: string, timeZone: string | null, locale: Locale): string {
  try {
    return new Intl.DateTimeFormat(locale === "es" ? "es" : "en", {
      weekday: "short", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit", hour12: false,
      ...(timeZone ? { timeZone } : {}),
    }).format(new Date(iso));
  } catch { return iso; }
}
export function money(cents: number, currency: string, locale: Locale, freeLabel: string): string {
  if (cents === 0) return freeLabel;
  try { return new Intl.NumberFormat(locale === "es" ? "es" : "en", { style: "currency", currency }).format(cents / 100); }
  catch { return `${(cents / 100).toFixed(2)} ${currency}`; }
}
export const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

