#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# CI-only: write web/.env.local for a run against the hermetic local stack.
#
# Every third-party value here is a DUMMY. The only real values are the local
# Supabase URL and the two keys minted by local-services.mjs from the Supabase
# CLI's published local development secret — which unlock nothing but a
# throwaway loopback database. Nothing in supabase/ci/ ever reads a production
# credential, and this file must never be pointed at one.
#
# The three talent-website flags the QA plan asks for are set true here.
#
# USAGE
#   eval "$(PGPORT=55700 bash supabase/ci/local-postgres.sh env)"
#   SUPABASE_PORT=54321 APP_PORT=3400 bash supabase/ci/app-env.sh
#   # → writes web/.env.local (overwrites; it is git-ignored)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
APP_PORT="${APP_PORT:-3400}"
OUT="${OUT:-$REPO/web/.env.local}"

# Two callers, one file:
#   - no Docker (RUNBOOK): mint the keys from the local JWT secret — the
#     gateway in local-services.mjs verifies them with the same secret.
#   - GitHub Actions: `supabase start` printed its own local keys and the
#     workflow exported them before calling this; keep those.
if [ -z "${NEXT_PUBLIC_SUPABASE_URL:-}" ] || [ -z "${SUPABASE_SERVICE_ROLE_KEY:-}" ] ||
   [ -z "${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}" ]; then
  eval "$(SUPABASE_PORT="${SUPABASE_PORT:-54321}" node "$HERE/local-services.mjs" --print-keys)"
fi

cat > "$OUT" <<ENV
# Generated by supabase/ci/app-env.sh — hermetic local stack, no real credentials.
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
NEXT_PUBLIC_SITE_URL=http://localhost:${APP_PORT}

# Talent-website flags under QA (Phase Q).
TALENT_THEME_GALLERY_ENABLED=true
TALENT_FREE_WEBSITE_ENABLED=true
TALENT_SITE_SUBDOMAINS_ENABLED=true
NEXT_PUBLIC_TALENT_THEME_GALLERY_ENABLED=true
NEXT_PUBLIC_TALENT_FREE_WEBSITE_ENABLED=true
NEXT_PUBLIC_TALENT_SITE_SUBDOMAINS_ENABLED=true

# Everything below is a DUMMY value: present so code paths that read the name
# do not branch on "unset", never used to reach a third party from CI.
CRON_SECRET=ci-dummy-cron-secret
STRIPE_SECRET_KEY=sk_test_ci_dummy
STRIPE_WEBHOOK_SECRET=whsec_ci_dummy
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_ci_dummy
STRIPE_PRICE_STUDIO_MONTHLY=price_ci_dummy_studio_monthly
STRIPE_PRICE_STUDIO_ANNUAL=price_ci_dummy_studio_annual
STRIPE_PRICE_AGENCY_MONTHLY=price_ci_dummy_agency_monthly
STRIPE_PRICE_AGENCY_ANNUAL=price_ci_dummy_agency_annual
STRIPE_PRICE_NETWORK_MONTHLY=price_ci_dummy_network_monthly
STRIPE_PRICE_NETWORK_ANNUAL=price_ci_dummy_network_annual
STRIPE_PRICE_TALENT_PRO_MONTHLY=price_ci_dummy_talent_pro_monthly
STRIPE_PRICE_TALENT_PRO_ANNUAL=price_ci_dummy_talent_pro_annual
STRIPE_PRICE_TALENT_PORTFOLIO_MONTHLY=price_ci_dummy_talent_portfolio_monthly
STRIPE_PRICE_TALENT_PORTFOLIO_ANNUAL=price_ci_dummy_talent_portfolio_annual
GOOGLE_PLACES_API_KEY=
NEXT_PUBLIC_BUILDER_PRESENCE=1
NEXT_PUBLIC_BUILDER_PROFILE=0
MEDIA_PER_HUB_FACES_ENABLED=0
MEDIA_TWO_KEY_GRANTS_ENABLED=0
ENABLE_SITE_SHELL=0
SITE_SHELL_TENANT_IDS=
ENABLE_SITE_SHELL_EDIT=0
SITE_SHELL_EDIT_TENANT_IDS=
ENV

echo "[app-env] wrote $OUT (Supabase: ${NEXT_PUBLIC_SUPABASE_URL}, app port ${APP_PORT})"
