import test from "node:test";
import assert from "node:assert/strict";
import { generateBaseline, orderTables, fkTarget } from "./gen-baseline.mjs";

const col = (name, type, extra = {}) => ({
  name, type, notNull: false, default: null, generated: null, identity: null, ...extra,
});

// Hand-made: child declared before parent to prove dependency ordering.
const snapshot = {
  extensions: [{ name: "pgcrypto", schema: "extensions" }],
  enums: [{ name: "site_status", labels: ["draft", "it's live"] }],
  tables: [
    {
      name: "child",
      columns: [
        col("id", "uuid", { notNull: true, default: "gen_random_uuid()" }),
        col("parent_id", "uuid", { notNull: true }),
        col("owner", "uuid"),
        col("status", "site_status", { default: "'draft'::site_status" }),
        col("total", "integer", { generated: "(a + b)" }),
        col("seq", "bigint", { notNull: true, identity: "d" }),
      ],
      constraints: [
        { name: "child_pkey", type: "p", def: "PRIMARY KEY (id)" },
        { name: "child_parent_fkey", type: "f", def: "FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE" },
        { name: "child_owner_fkey", type: "f", def: "FOREIGN KEY (owner) REFERENCES auth.users(id)" },
        { name: "child_ghost_fkey", type: "f", def: "FOREIGN KEY (owner) REFERENCES ghost(id)" },
      ],
      indexes: [{ name: "child_parent_idx", def: "CREATE INDEX child_parent_idx ON public.child USING btree (parent_id)" }],
    },
    {
      name: "parent",
      columns: [col("id", "uuid", { notNull: true }), col("slug", "text")],
      constraints: [
        { name: "parent_pkey", type: "p", def: "PRIMARY KEY (id)" },
        { name: "parent_slug_key", type: "u", def: "UNIQUE (slug)" },
      ],
      indexes: [],
    },
  ],
};

test("fkTarget parses qualified and unqualified targets", () => {
  assert.deepEqual(fkTarget("FOREIGN KEY (a) REFERENCES auth.users(id)"), { schema: "auth", name: "users" });
  assert.deepEqual(fkTarget("FOREIGN KEY (a) REFERENCES parent(id)"), { schema: "public", name: "parent" });
  assert.equal(fkTarget("PRIMARY KEY (id)"), null);
});

test("orderTables puts referenced tables first and tolerates cycles", () => {
  assert.deepEqual(orderTables(snapshot.tables).map((t) => t.name), ["parent", "child"]);
  const cyc = [
    { name: "b", columns: [], constraints: [{ type: "f", def: "FOREIGN KEY (x) REFERENCES a(id)" }] },
    { name: "a", columns: [], constraints: [{ type: "f", def: "FOREIGN KEY (x) REFERENCES b(id)" }] },
  ];
  assert.deepEqual(orderTables(cyc).map((t) => t.name), ["a", "b"]);
});

test("generateBaseline emits objects in dependency order with expected DDL", () => {
  const { sql, warnings } = generateBaseline(snapshot);
  const at = (s) => {
    const i = sql.indexOf(s);
    assert.ok(i >= 0, `missing: ${s}`);
    return i;
  };
  assert.ok(at('create extension if not exists "pgcrypto" with schema "extensions"') < at("create type"));
  assert.ok(at("create type public.\"site_status\" as enum ('draft', 'it''s live')") < at("create table public.\"parent\""));
  assert.ok(at('create table public."parent"') < at('create table public."child"'));
  assert.ok(at('"seq" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL') > 0);
  assert.ok(at('"total" integer GENERATED ALWAYS AS ((a + b)) STORED') > 0);
  assert.ok(at('"id" uuid DEFAULT gen_random_uuid() NOT NULL') > 0);
  // PK/UNIQUE before indexes before FKs.
  assert.ok(at('add constraint "parent_slug_key" UNIQUE (slug)') < at("CREATE INDEX child_parent_idx"));
  assert.ok(at("CREATE INDEX child_parent_idx") < at('add constraint "child_parent_fkey"'));
  assert.ok(at('add constraint "child_owner_fkey" FOREIGN KEY (owner) REFERENCES auth.users(id)') > 0);
  // FK to a table outside the snapshot is skipped and reported.
  assert.ok(!sql.includes('add constraint "child_ghost_fkey"'));
  assert.equal(warnings.length, 1);
  assert.match(warnings[0], /ghost/);
});
