/* Seeded FAKE data only — no production IDs or real PII. */
window.DESK_DATA = {
  agents: {
    oran: { id: "ag_oran", name: "Oran Tene", role: "owner", initials: "OT" },
    maya: { id: "ag_maya", name: "Maya Ruiz", role: "agent", initials: "MR" },
    leo: { id: "ag_leo", name: "Leo Park", role: "specialist", initials: "LP" },
    ai: { id: "ag_ai", name: "Tulala Assist", role: "ai", initials: "AI" },
  },
  me: "maya",
  queues: [
    { id: "needs_you", label: "Needs you", count: 7 },
    { id: "unassigned", label: "Unassigned", count: 4 },
    { id: "mine", label: "Assigned to me", count: 5 },
    { id: "waiting_customer", label: "Waiting on customer", count: 9 },
    { id: "sla_risk", label: "SLA risk", count: 2 },
    { id: "escalated", label: "Escalated", count: 1 },
    { id: "snoozed", label: "Snoozed", count: 3 },
    { id: "resolved_today", label: "Resolved today", count: 6 },
    { id: "all", label: "All open", count: 28 },
  ],
  conversations: [
    {
      id: "c1",
      customer: "Ana Castillo",
      email: "ana.castillo@example.test",
      preview: "My booking receipt never arrived — can you resend?",
      time: "2m",
      unread: true,
      status: "open",
      assignee: "maya",
      priority: "high",
      sla: "warn",
      channel: "email",
      language: "EN",
      source: "app.tulala.digital",
      hub: "Tulala App",
    },
    {
      id: "c2",
      customer: "Diego Morales",
      email: "diego@studio-norte.test",
      preview: "Agency roster invite bounced for two talents",
      time: "18m",
      unread: true,
      status: "waiting_agent",
      assignee: null,
      priority: "normal",
      sla: "ok",
      channel: "in_app",
      language: "ES",
      source: "impronta.tulala.digital",
      hub: "Agency workspace",
      agencyManaged: true,
    },
    {
      id: "c3",
      customer: "Guest · sofia-r",
      email: null,
      preview: "How do I claim my guest quotes?",
      time: "1h",
      unread: false,
      status: "open",
      assignee: "maya",
      priority: "low",
      sla: "ok",
      channel: "guest_chat",
      language: "EN",
      source: "tulala.digital/contact",
      hub: "Marketing",
      unverified: true,
    },
    {
      id: "c4",
      customer: "Valeria Test",
      email: "valeria.qa@example.test",
      preview: "Payment shows processing for 40 minutes",
      time: "3h",
      unread: false,
      status: "escalated",
      assignee: "leo",
      priority: "urgent",
      sla: "breach",
      channel: "in_app",
      language: "ES",
      source: "talent site",
      hub: "Talent · TAL-93901",
    },
    {
      id: "c5",
      customer: "Marco Silva",
      email: "marco.silva@example.test",
      preview: "Thanks — that fixed it.",
      time: "Yesterday",
      unread: false,
      status: "resolved",
      assignee: "maya",
      priority: "normal",
      sla: "ok",
      channel: "email",
      language: "EN",
      source: "hello@ inbound",
      hub: "Email",
    },
    {
      id: "c6",
      customer: "Priya Nair",
      email: "priya@example.test",
      preview: "Can you merge my duplicate tickets?",
      time: "Yesterday",
      unread: false,
      status: "waiting_customer",
      assignee: "maya",
      priority: "normal",
      sla: "ok",
      channel: "form",
      language: "EN",
      source: "help form",
      hub: "Help center",
    },
  ],
  threadC1: [
    { type: "date", label: "Today · 2 Oct 2026" },
    {
      type: "customer",
      who: "Ana Castillo",
      time: "09:42",
      text: "Hi — I paid for booking BK-10422 yesterday but never got the receipt email. Can you resend it to ana.castillo@example.test?",
    },
    {
      type: "system",
      text: "Ticket created from email · matched Message-ID · assigned queue Needs you",
    },
    {
      type: "assignment",
      text: "Assigned to Maya Ruiz by routing rule · Brand inquiries EN",
    },
    {
      type: "ai-draft",
      who: "Tulala Assist",
      time: "09:43",
      confidence: "medium",
      text: "Hi Ana — thanks for writing. I can resend the receipt for booking BK-10422 to ana.castillo@example.test. Confirm and I’ll send it now.",
      stale: false,
    },
    {
      type: "agent",
      who: "Maya Ruiz",
      time: "09:48",
      text: "Hi Ana — confirming we can resend. One moment while I pull the payment record.",
    },
    {
      type: "note",
      who: "Maya Ruiz",
      time: "09:49",
      text: "Internal: Stripe pi_test_10422 shows succeeded. Receipt cron skipped — likely template flag. Do not promise timeline until Leo checks.",
    },
    {
      type: "status",
      text: "Status → Waiting on specialist",
    },
    {
      type: "escalation",
      text: "Escalated to Leo Park · reason: payment receipt missing",
    },
    {
      type: "attachment",
      who: "Ana Castillo",
      time: "10:02",
      name: "bank-screenshot.png",
      size: "240 KB",
      ok: true,
    },
    {
      type: "attachment",
      who: "Ana Castillo",
      time: "10:03",
      name: "statement.exe",
      size: "1.2 MB",
      ok: false,
      reason: "Unsupported type · executable blocked",
    },
    { type: "unread", label: "New since you last viewed" },
    {
      type: "customer",
      who: "Ana Castillo",
      time: "10:11",
      text: "Also attaching the transfer confirmation. Let me know if you need anything else — happy to wait.",
      long: false,
    },
    {
      type: "customer",
      who: "Ana Castillo",
      time: "10:12",
      text: "Here’s the help article I already tried: https://help.tulala.digital/receipts — it says receipts arrive within 5 minutes but mine never did. I also checked spam, promotions, and the booking detail page under Payments → Receipts. Still empty after refreshing on desktop and iOS.",
      long: true,
      linkPreview: {
        host: "help.tulala.digital",
        title: "When do booking receipts arrive?",
      },
    },
    {
      type: "failed",
      who: "Maya Ruiz",
      time: "10:15",
      text: "Ana — I’ve asked payments to regenerate the receipt. You’ll get it at ana.castillo@example.test.",
      error: "Outbound email failed · SMTP 421 temporary",
    },
    {
      type: "loading",
      who: "Maya Ruiz",
      text: "Sending…",
    },
    {
      type: "typing",
      who: "Ana Castillo",
    },
    {
      type: "presence",
      text: "Leo Park viewing · Maya Ruiz typing",
    },
  ],
  contextRich: {
    identity: {
      name: "Ana Castillo",
      email: "ana.castillo@example.test",
      phone: "+52 ······4412",
      locale: "en-MX",
      timezone: "America/Mexico_City",
    },
    verification: "Verified email · signed-in user",
    customerType: "Client",
    language: "English (preferred) · reads Spanish",
    plan: "Client free",
    related: [{ label: "Talent · Valeria Test", href: "#/unavailable/talent" }],
    website: [{ label: "Booking page", href: "#/unavailable/site", meta: "Read-only" }],
    services: [{ label: "Portrait session", meta: "90 min" }],
    bookings: [
      { label: "BK-10422 · Portrait", meta: "Paid · Yesterday", href: "#/unavailable/booking" },
      { label: "BK-9910 · Retouch add-on", meta: "Completed · Aug", href: "#/unavailable/booking" },
    ],
    quotes: [{ label: "QT-2201", meta: "Accepted" }],
    payments: [
      { label: "pi_test_10422", meta: "Succeeded · $180 USD", href: "#/unavailable/payment" },
      { label: "pi_test_9910", meta: "Succeeded · $40 USD", href: "#/unavailable/payment" },
    ],
    refunds: [],
    previous: [
      { label: "TK-8821 Receipt delay", meta: "Resolved · Jul" },
      { label: "TK-7740 Reschedule", meta: "Resolved · May" },
    ],
    diagnostics: [{ label: "Diag · iOS Safari blank receipt", meta: "Open", href: "#/unavailable/diag" }],
    replays: [{ label: "Replay · consent granted", meta: "12m", href: "#/unavailable/replay" }],
    features: [{ label: "FR · PDF receipt download", meta: "Triaged" }],
    escalations: [{ label: "ESC-44 payments receipt", meta: "Active" }],
    flags: ["Priority: high", "SLA warn · first response"],
  },
  contextEmpty: {
    identity: {
      name: "Guest · sofia-r",
      email: "Unverified",
      phone: "—",
      locale: "en",
      timezone: "Unknown",
    },
    verification: "Unverified guest session",
    customerType: "Guest",
    language: "English",
    plan: "—",
    related: [],
    website: [],
    services: [],
    bookings: [],
    quotes: [],
    payments: [],
    refunds: [],
    previous: "hidden",
    diagnostics: [],
    replays: [],
    features: [],
    escalations: [],
    flags: ["Unverified · history hidden"],
  },
  canned: [
    { id: "cr1", title: "Resend receipt", body: "Hi {{first_name}} — I’ve resent the receipt for {{booking_id}} to {{email}}." },
    { id: "cr2", title: "Need more info", body: "Hi {{first_name}} — could you share the booking code and the email on the account?" },
  ],
  macros: [
    { id: "m1", title: "Escalate payments", vars: ["ticket_id", "reason"] },
    { id: "m2", title: "Snooze 24h follow-up", vars: ["first_name"] },
  ],
  insights: {
    range: "Last 7 days · America/Mexico_City business hours",
    volume: { value: "142", def: "Tickets created in range (all channels)" },
    firstResponse: { value: "18m", def: "Median time to first human or approved AI reply" },
    resolution: { value: "11h", def: "Median time from create → resolved" },
    sla: { value: "92%", def: "% with first response inside target" },
    backlog: { value: "28", def: "Open now · not snoozed" },
    aiAssisted: { value: "41%", def: "Resolved with ≥1 approved AI draft" },
    handoff: { value: "12%", def: "AI draft rejected → human took over" },
    escalations: { value: "7", def: "Escalated to specialist in range" },
    csat: { value: "—", def: "CSAT placeholder · collection not wired in Phase 1" },
  },
  cmdkCommands: [
    { id: "search", label: "Search conversations", kbd: "↵", group: "Go" },
    { id: "customer", label: "Open customer · Ana Castillo", kbd: "", group: "Go" },
    { id: "assign", label: "Assign…", kbd: "A", group: "Ticket" },
    { id: "status", label: "Change status…", kbd: "E", group: "Ticket" },
    { id: "snooze", label: "Snooze…", kbd: "S", group: "Ticket" },
    { id: "note", label: "Add internal note", kbd: "N", group: "Ticket" },
    { id: "canned", label: "Insert canned reply…", kbd: "R", group: "Compose" },
    { id: "escalate", label: "Escalate…", kbd: "", group: "Ticket" },
    { id: "diag", label: "Open diagnostics", kbd: "", group: "Go" },
    { id: "hq", label: "Open Platform Admin", kbd: "", group: "Owner", ownerOnly: true },
  ],
};
