/**
 * Embed roster data — Phase G PR 2.
 *
 * Loads the public-facing roster for a tenant in a shape suitable for
 * the embeddable widget. Read-only, no auth required, no PII beyond
 * what the public profile pages already expose.
 *
 * The widget consumes this either:
 *  - Server-side (rendered into the iframe page at /embed/roster/[slug])
 *  - Client-side via /api/embed/roster/[slug] as JSON (for partners
 *    who want to render the UI themselves on their own page)
 */

import { createClient } from "@/lib/supabase/server";

export interface EmbedRosterEntry {
  /** Stable URL slug used in /t/<code>. */
  profileCode: string;
  /** Display name. */
  displayName: string;
  /** Hero image absolute URL, or null. */
  imageUrl: string | null;
  /** First public talent type, e.g. "Model" / "MC" — locale-resolved. */
  publicRole: string | null;
  /** Residence locality (city) — locale-resolved. */
  locality: string | null;
}

export interface EmbedRosterResult {
  tenantSlug: string;
  tenantName: string;
  entries: EmbedRosterEntry[];
  /** Suggestion to the host page on what to set as iframe height. */
  suggestedHeightPx: number;
}

interface RosterRow {
  profile_code: string;
  display_name: string | null;
  first_name: string | null;
  last_name: string | null;
  updated_at: string | null;
  // Hero image columns intentionally omitted from this v1; the page
  // builds image URLs from a known media-bucket path or falls back to
  // the OpenGraph image route.
}

/** Fetch the embeddable roster for a tenant. Filters by the same gates
 *  the public talent page uses: workflow_status in approved/published,
 *  visibility=public, not deleted, scoped to the tenant via
 *  `created_by_agency_id`. */
export async function loadEmbedRoster(
  tenantId: string,
  tenantName: string,
  tenantSlug: string,
  options: { limit?: number } = {},
): Promise<EmbedRosterResult | null> {
  const supabase = await createClient();
  if (!supabase) return null;

  const limit = Math.min(Math.max(options.limit ?? 24, 1), 48);

  const { data, error } = await supabase
    .from("talent_profiles")
    .select(
      `profile_code, display_name, first_name, last_name, updated_at`,
    )
    .eq("created_by_agency_id", tenantId)
    .in("workflow_status", ["approved", "published"])
    .eq("visibility", "public")
    .is("deleted_at", null)
    .order("is_featured", { ascending: false })
    .order("updated_at", { ascending: false })
    .limit(limit);

  if (error) {
    return null;
  }

  const rows = (data ?? []) as RosterRow[];
  const entries: EmbedRosterEntry[] = rows.map((r) => ({
    profileCode: r.profile_code,
    displayName:
      r.display_name?.trim() ||
      [r.first_name, r.last_name].filter(Boolean).join(" ").trim() ||
      r.profile_code,
    // v1: image is the talent's OpenGraph image (which is generated by
    // the existing /t/[profileCode]/opengraph-image.tsx route). A future
    // PR can pull the actual hero crop from the media bucket directly.
    imageUrl: null,
    publicRole: null, // Could derive from taxonomy in a follow-up PR.
    locality: null,
  }));

  // Suggested height: card height (~340 px) × ceil(count / 3) + padding
  // assuming a 3-up desktop grid. The loader script will read the actual
  // height via postMessage and resize the iframe to fit anyway.
  const suggestedHeightPx = Math.min(
    340 * Math.max(1, Math.ceil(entries.length / 3)) + 80,
    1800,
  );

  return {
    tenantSlug,
    tenantName,
    entries,
    suggestedHeightPx,
  };
}
