/**
 * backfill-lifestyle-folder.ts — file the imagery that already exists.
 *
 * The Lifestyle folder starts empty: generation files new images into it, but
 * everything created before that lands nowhere. This moves the unambiguous
 * ones in.
 *
 * WHAT COUNTS AS UNAMBIGUOUS. Only `metadata->>source = 'ai-image-generate'`.
 * That flag is written by the generator itself, so it is a fact, not a guess.
 * The owner's scope for this folder is wider than AI — any lifestyle or brand
 * imagery belongs — but "which of these uploads is lifestyle?" is a judgement
 * a script should not make on a live library. So other workspace-owned images
 * are REPORTED as candidates and left exactly where they are; the owner files
 * them from the media library in one click each.
 *
 * DRY RUN IS THE DEFAULT. A backup of every row that would change is written
 * before any write, on dry runs too.
 *
 *   npx tsx scripts/backfill-lifestyle-folder.ts
 *   npx tsx scripts/backfill-lifestyle-folder.ts --apply
 */

import { writeFileSync } from "node:fs";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";

import { LIFESTYLE_FOLDER, ensureSystemFolder } from "../src/lib/media/system-folders";

interface AssetRow {
  id: string;
  storage_path: string | null;
  purpose: string | null;
  variant_kind: string | null;
  ownership_kind: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

function serviceClient(): SupabaseClient {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();
  if (!url || !key) throw new Error("NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY required.");
  return createClient(url, key, { auth: { persistSession: false } });
}

/** Generated by us, therefore certainly lifestyle imagery. */
export function isGeneratedAsset(row: Pick<AssetRow, "metadata">): boolean {
  const source = (row.metadata ?? {})["source"];
  return source === "ai-image-generate";
}

async function main() {
  const { loadEnvLocal } = await import("./load-env-local.mjs");
  loadEnvLocal();

  const apply = process.argv.includes("--apply");
  if (!apply) console.log("DRY RUN — nothing will be filed.\n");

  const supabase = serviceClient();
  const slug = process.env.IMPRONTA_SEED_TENANT_SLUG ?? "impronta";
  const { data: tenant } = await supabase
    .from("agencies")
    .select("id")
    .eq("slug", slug)
    .maybeSingle<{ id: string }>();
  if (!tenant) throw new Error(`No tenant for slug "${slug}".`);

  const { data: rows } = await supabase
    .from("media_assets")
    .select("id, storage_path, purpose, variant_kind, ownership_kind, metadata, created_at")
    .eq("tenant_id", tenant.id)
    .eq("ownership_kind", "agency")
    .is("deleted_at", null)
    .order("created_at", { ascending: false });
  const assets = (rows ?? []) as AssetRow[];

  const generated = assets.filter(isGeneratedAsset);
  const otherWorkspace = assets.filter(
    (a) => !isGeneratedAsset(a) && a.purpose !== "branding",
  );

  // Which of those are already filed here (re-runs must be no-ops).
  const folderId = await ensureSystemFolder(supabase, tenant.id, LIFESTYLE_FOLDER, null);
  if (!folderId) throw new Error("Could not resolve the Lifestyle folder.");
  const { data: alreadyRows } = await supabase
    .from("media_folder_items")
    .select("asset_id")
    .eq("folder_id", folderId);
  const already = new Set((alreadyRows ?? []).map((r) => (r as { asset_id: string }).asset_id));

  const toFile = generated.filter((a) => !already.has(a.id));

  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = `/tmp/impronta-lifestyle-backfill-${stamp}.json`;
  writeFileSync(
    backupPath,
    JSON.stringify({ tenantId: tenant.id, folderId, willFile: toFile, candidates: otherWorkspace }, null, 1),
  );
  console.log(`BACKUP written: ${backupPath}\n`);

  console.log(`TO FILE into "${LIFESTYLE_FOLDER.name}" (generated, certain): ${toFile.length}`);
  for (const a of toFile.slice(0, 20)) {
    console.log(`  ${a.id}  ${String(a.created_at).slice(0, 10)}  ${a.storage_path ?? ""}`);
  }
  if (toFile.length > 20) console.log(`  … and ${toFile.length - 20} more`);

  console.log(
    `\nCANDIDATES left alone (workspace images, not generated, not branding): ${otherWorkspace.length}`,
  );
  console.log("  These may or may not be lifestyle imagery — that is the owner's call.");
  console.log("  File them from the media library's folder list; this script will not guess.");
  for (const a of otherWorkspace.slice(0, 10)) {
    console.log(`  ${a.id}  purpose=${a.purpose}  ${a.storage_path ?? ""}`);
  }
  if (otherWorkspace.length > 10) console.log(`  … and ${otherWorkspace.length - 10} more`);

  if (!apply) {
    console.log("\nRe-run with --apply to file the generated set.");
    return;
  }
  if (toFile.length === 0) {
    console.log("\nNothing to do.");
    return;
  }

  const { error } = await supabase.from("media_folder_items").upsert(
    toFile.map((a) => ({ folder_id: folderId, asset_id: a.id, added_by: null })),
    { onConflict: "folder_id,asset_id" },
  );
  if (error) throw new Error(`filing failed: ${error.message}`);
  console.log(`\nFiled ${toFile.length} asset(s) into ${LIFESTYLE_FOLDER.name}.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
