import { chromium } from "playwright";
import fs from "node:fs";
const BASE="http://127.0.0.1:3001";
const OUT="/cursor/stores/bc-80661ff2-8036-4d60-998b-696a75e11225/media/alba-builder-pending";
const cookies = fs.readFileSync("/tmp/alba-cookies.txt","utf8").split("\n").filter(l=>l&&!l.startsWith("#")).map(l=>{const p=l.split("\t");return p.length>=7?{name:p[5],value:p[6],url:BASE}:null}).filter(Boolean) as Array<{name:string;value:string;url:string}>;
const browser = await chromium.launch({headless:true});
const ctx = await browser.newContext({viewport:{width:1440,height:900}});
await ctx.addCookies(cookies);
const page = await ctx.newPage();
await page.goto(BASE+"/talent/page-builder",{waitUntil:"domcontentloaded",timeout:60000});
await page.waitForTimeout(4000);
await page.getByRole("button",{name:/^Design$|^Diseño$/i}).first().click().catch(()=>{});
await page.waitForTimeout(400);
await page.getByRole("button",{name:/Open theme editor|Abrir editor/i}).click();
await page.waitForTimeout(1500);
await page.screenshot({path:OUT+"/09-theme-editor-open.png"});
await page.getByRole("tab",{name:/Style|Estilo/i}).click();
await page.waitForTimeout(800);
await page.screenshot({path:OUT+"/09-theme-style-tab-real.png"});
await page.getByRole("tab",{name:/Layout|Disposición/i}).click();
await page.waitForTimeout(600);
await page.screenshot({path:OUT+"/09-theme-layout-chat-real.png"});
const hasChat = await page.getByText(/Chat style|Estilo de chat/i).count();
const hasStyle = await page.getByText(/Typography|Tipografía|Type roles|Reset to design|Restablecer/i).count();
fs.writeFileSync(OUT+"/09-theme-controls.json", JSON.stringify({hasChat, hasStyle},null,2));
console.log({hasChat, hasStyle});
await browser.close();
