/**
 * TUL-256. Allow-list entries for the read-only impersonation guard that live
 * outside the portal route trees (batch 1: shared messaging, onboarding,
 * talent self-service and agenda modules). Every entry is a pure loader.
 */
export const READ = "pure loader: reads only, no write path, nothing for read-only mode to protect";

export type AllowEntry = [suffix: string, names: string[], reason: string];

export const EXTRA_ALLOW: AllowEntry[] = [
  ["app/(workspace)/[tenantSlug]/admin/media/actions.ts", ["actionLoadTalentMediaBundleAll"], READ],
  ["app/(workspace)/platform/admin/integrations/captcha-override-actions.ts", ["loadWorkspaceCaptchaOverrides"], READ],
  ["lib/server-actions/how-you-work.ts", ["loadHowYouWork"], READ],
  ["lib/site-admin/media/photo-caption-actions.ts", ["loadTalentPhotoCaptionLocalesAction"], READ],
  ["lib/client-account/actions.ts", ["signOutClientAccount"], "SIGN-OUT: ends the session; must keep working while impersonating (PM exception)"],
  ["lib/reviews/review-actions.ts", ["loadReviewableBookingsAction", "loadClientReviewablesAction"], READ],
  ["lib/server-actions/messaging-engine.ts", ["staff", "messagingLoadInbox", "messagingResolveOrderThread", "messagingLoadThread", "messagingLoadEssentials", "loadConversationHistory", "messagingResolve", "messagingRelinkImpact", "messagingSearch"], READ],
  ["lib/server-actions/messaging-identity.ts", ["messagingMatchCustomers"], READ],
  ["lib/server-actions/messaging-items.ts", ["messagingLoadItemsCatalog", "messagingLoadPersonSlots"], READ],
  ["lib/server-actions/messaging-money-actions.ts", ["messagingPreviewCancel", "messagingLoadRefundableTransaction", "messagingCanReadNotes"], READ],
  ["lib/server-actions/messaging-offers.ts", ["messagingLoadOfferForEditor", "messagingListOffers"], READ],
  ["lib/server-actions/messaging-sheets.ts", ["messagingLoadHandOverTargets", "messagingLoadDelivery", "messagingLoadSnapshots", "messagingLoadOffers", "messagingLoadBasketDiff", "messagingLoadContextLines"], READ],
  ["lib/server-actions/messaging-talent.ts", ["messagingTalentLoadInbox", "messagingTalentLoadThread", "messagingTalentLoadEssentials", "messagingTalentLoadContextLines"], READ],
  ["lib/server-actions/onboarding-lookups.ts", ["searchOnboardingTypes", "searchOnboardingCities"], READ],
  ["lib/server-actions/onboarding-module.ts", ["loadOnboardingResume", "loadOnboardingCard", "getOnboardingBuildStatus"], READ],
  ["lib/server-actions/onboarding-setup.ts", ["loadOnboardingSetup"], READ],
  ["lib/server-actions/talent-self-profile-sections.ts", ["getTalentProfileEditorDataForSelf", "getTalentProfileDynFieldValuesForSelf"], READ],
  ["lib/server-actions/talent-self-services.ts", ["getResolvedSkillsAsTalent", "getAspirationsAsTalent", "getEnabledParentCategoriesForPickerAsTalent", "getTalentTypesUnderParentAsTalent", "getResolvedContextsAsTalent", "getContextCatalogAsTalent"], READ],
  ["lib/server-actions/talent-self.ts", ["loadCurrentTalentPayoutSnapshot", "loadMyInquiryTakeHome", "loadTalentPreferredLanguage", "loadTalentLanguages"], READ],
  ["lib/server-actions/user-prefs.ts", ["loadUserPrefs", "getNotificationPrefs"], READ],
  ["lib/talent-agenda/booking-actions.ts", ["requireOwnBooking"], READ],
  ["lib/talent-agenda/load-record-item.ts", ["loadTalentAgendaRecordItem", "loadTalentTimelessBookingStub"], READ],
  ["lib/talent-site/history/history-actions.ts", ["loadTalentHistoryAction", "loadTalentGoLiveAction"], READ],
  ["lib/talent-site/server/actions.ts", ["fetchTalentPersonalSiteDashboardStateAction"], READ],
  ["lib/talent-site/server/site-management-actions.ts", ["loadMaxSiteManagerAction"], READ],
  ["lib/talent/apply-actions.ts", ["listOwnApplications"], READ],
  ["lib/talent/clients-actions.ts", ["loadTalentClients"], READ],
  ["lib/talent/menu-offerings-actions.ts", ["loadWorkspaceMenuForEditor"], READ],
  ["lib/talent/offerings-actions.ts", ["loadTalentOfferingsForEditor", "listTalentPortfolioPhotos"], READ],
  ["lib/talent/services-menu-actions.ts", ["loadTalentServicesMenu", "loadTalentServicePerformance"], READ],
  ["lib/talent/talent-booking-terms-actions.ts", ["loadTalentBookingTerms"], READ],
  ["app/(workspace)/platform/admin/commerce/commission/actions.ts", ["loadPlatformCommissionConfig"], READ],
  ["app/(workspace)/platform/admin/tenants/actions.ts", ["actionGetTenantManagementDetail"], READ],
  ["app/(workspace)/platform/admin/integrations/platform-integration-actions.ts", ["loadPlatformIntegrationDefaults"], READ],
  ["app/(workspace)/platform/admin/builder-lab/talent-designs/publish-actions.ts", ["actionPreviewDesignPublish"], READ],
  ["app/(workspace)/platform/admin/users/actions-billing.ts", ["getPersonBillingSnapshot"], READ],
  ["app/(workspace)/platform/admin/users/actions.ts", ["getPlatformUserActivity", "getPlatformUserAuditLog"], READ],
  ["app/(workspace)/platform/admin/users/actions-notes.ts", ["getPlatformUserNotes"], READ],
  ["app/(workspace)/platform/admin/stock/actions.ts", ["stockLimits"], READ],
  ["app/(workspace)/[tenantSlug]/admin/_events-schedule-actions.ts", ["listScheduleItems", "searchPerformers", "listEventSpaces"], READ],
  ["app/(workspace)/[tenantSlug]/admin/_events-page-actions.ts", ["loadEventPageLink"], READ],
  ["app/(workspace)/[tenantSlug]/admin/_exceptions-actions.ts", ["loadExceptionsInbox"], READ],
  ["app/(workspace)/[tenantSlug]/admin/_bridge-slice-actions.ts", ["loadBridgeSlicesAction"], READ],
  ["app/(workspace)/[tenantSlug]/admin/_events-actions.ts", ["loadWorkspaceEvents", "loadSessionComps", "loadSessionPools", "loadEventSettings"], READ],
  ["app/(workspace)/[tenantSlug]/admin/_door-actions.ts", ["loadDoor", "loadNightReport", "loadDoorTiers", "loadHeldDoorOrders"], READ],
  ["app/(workspace)/[tenantSlug]/admin/_pipeline-actions.ts", ["loadInquiryPaymentState", "loadAgencySettingsNamespace", "loadEditableJobFields", "loadInquiryLineup", "loadInquiryAttachments", "loadOfferDraft", "loadInquiryPayoutReceiverCandidates", "loadWorkspaceCoordinatorCandidates", "loadCoordinatorAssignCandidates", "loadSecondaryCoordinators", "loadBookingCommissionSnapshotAction", "loadHoldsForInquiryAction"], READ],
  ["app/(workspace)/[tenantSlug]/admin/settings/integration-actions.ts", ["loadTenantIntegrations"], READ],
  ["app/(workspace)/[tenantSlug]/admin/settings/domain-actions.ts", ["checkCustomDomainProvisioningAction"], READ],
  ["app/(workspace)/[tenantSlug]/admin/messages/actions.ts", ["fetchMessages"], READ],
  ["app/(workspace)/[tenantSlug]/admin/roster/registration/actions.ts", ["loadRegistrationManageData"], READ],
  ["app/(workspace)/[tenantSlug]/admin/website/redirects/actions.ts", ["listRedirects"], READ],
  ["app/(workspace)/[tenantSlug]/admin/website/forms/actions.ts", ["exportSubmissionsCsv", "getFormAttachmentDownloadUrl"], READ],
  ["app/(workspace)/[tenantSlug]/admin/pos/floor-actions.ts", ["floorLoadReserveTimes"], READ],
  ["app/(workspace)/[tenantSlug]/admin/pos/door-actions.ts", ["posDoorTonight", "posDoorReadSale", "posDoorIssuedTickets"], READ],
  ["app/(workspace)/[tenantSlug]/admin/pos/actions.ts", ["posSearchCustomers", "posLoadOpen", "posLoadSale", "posCurrentShift", "posReadCustomAmountLimit", "posBookingCandidates", "posDisplayRead", "posResolveScanCode"], READ],
  ["app/(workspace)/[tenantSlug]/admin/pos/classes-actions.ts", ["classesWalkInSlots", "classesServices"], READ],
  ["app/(workspace)/[tenantSlug]/admin/pos/_projects/projects-actions.ts", ["projectsFindReceipt"], READ],
  ["app/(workspace)/[tenantSlug]/admin/people/people-actions.ts", ["loadWhoPerforms"], READ],
  ["app/(workspace)/[tenantSlug]/admin/pitches/actions.ts", ["loadPitchDetailAction"], READ],
  ["app/(workspace)/[tenantSlug]/admin/orders/refund-actions.ts", ["loadOrderLinesForDesk"], READ],
  ["app/(workspace)/[tenantSlug]/admin/payouts/base-fee-actions.ts", ["loadWorkspaceBaseFee"], READ],
  ["app/(workspace)/[tenantSlug]/admin/payouts/payouts-surface-actions.ts", ["loadPayoutsSurface"], READ],
  ["app/(workspace)/[tenantSlug]/admin/media/stock-actions.ts", ["actionListLifestyleStock"], READ],
  ["app/(workspace)/[tenantSlug]/admin/media/folder-actions.ts", ["actionListMediaFolders", "actionListFolderAssets", "actionGetWorkspaceTags", "actionGetAssetActivity"], READ],
  ["app/(workspace)/[tenantSlug]/admin/media/actions.ts", ["actionLoadRosterTalents", "actionGetTalentDocumentSignedUrl", "actionLoadTalentGallery", "actionLoadTalentMediaBundle", "actionGetMediaCount", "actionListDriveFolder"], READ],
  ["app/t/[profileCode]/talent-profile-inquire-data.ts", ["getTalentProfileInquireData"], READ],
  ["app/t/[profileCode]/_actions/guest-full-thread-actions.ts", ["resolveSignedInClientRedirect", "getGuestFullThread"], READ],
  ["app/t/[profileCode]/_actions/guest-order-resume-actions.ts", ["resolveGuestTokenResumeHref", "getGuestInquiryByOrder"], READ],
  ["app/t/[profileCode]/_actions/guest-catalog-actions.ts", ["getGuestItemsCatalog"], READ],
  ["app/t/[profileCode]/_actions/guest-chat-actions.ts", ["checkGuestClaimEmail", "getGuestThreadMessages", "getActiveGuestInquiry"], READ],
  ["app/t/[profileCode]/_actions/guest-roster-actions.ts", ["listGuestTenantRoster", "resolveGuestCartPortraits"], READ],
  ["app/t/[profileCode]/_actions/guest-detail-chips-actions.ts", ["getGuestInquiryDetails"], READ],
  ["app/t/[profileCode]/_actions/guest-inquiries-actions.ts", ["listGuestInquiries"], READ],
  ["app/(marketing)/global-directory/actions.ts", ["loadMoreDirectoryTalents"], READ],
  ["app/(marketing)/get-started/actions.ts", ["checkSubdomainAvailability"], READ],
  ["app/(public)/_events/event-program-actions.ts", ["loadEventProgram"], READ],
  ["app/(public)/_events/ticket-picker-actions.ts", ["loadTicketPicker"], READ],
  ["app/(public)/_reserve/reserve-actions.ts", ["loadReserveAvailability"], READ],
  ["app/(public)/directory/get-inquiry-sheet-data.ts", ["getDirectoryInquirySheetData"], READ],
  ["app/(public)/_menu/menu-board-actions.ts", ["loadLiveMenuBoard"], READ],
  ["app/(public)/_sessions/session-picker-actions.ts", ["resolveSessionPickerOffering", "loadSessionPicker"], READ],
  ["components/edit-chrome/theme-template-design-actions.ts", ["loadThemeTemplateDesignAction"], READ],
  ["components/builder-lab/talent-factory/talent-factory-actions.ts", ["actionLoadTalentFactory"], READ],
  ["components/marketing/welcome-actions.ts", ["loadWelcomeModel"], READ],
  ["components/chat-interactions/pins-fetch-action.ts", ["fetchPinnedMessagesAction"], READ],
  ["components/talent/website-settings/website-settings-gate-action.ts", ["loadWebsiteSettingsEnabledAction", "loadHoursMinNoticeAction"], READ],
  ["lib/guide/guide-actions.ts", ["listGuideTopicsAction", "getGuideArticleAction"], READ],
  ["lib/storefront/order-lookup.server.ts", ["readOrderLookup", "actOrderLookup"], READ],
  ["lib/storefront/reviews.server.ts", ["readReviews"], READ],
  ["lib/storefront/package-selector.server.ts", ["readPackageSelector"], READ],
  ["lib/storefront/chat-with-us.server.ts", ["readChatWithUs"], READ],
  ["lib/storefront/seat-map.server.ts", ["readSeatMap"], READ],
  ["lib/messages/unfurl.ts", ["unfurlLink"], READ],
  ["lib/storefront/service-collection.server.ts", ["readServiceCollection"], READ],
  ["lib/storefront/appointment-picker.server.ts", ["readAppointmentPicker"], READ],
  ["lib/storefront/class-timetable.server.ts", ["readClassTimetable"], READ],
  ["lib/storefront/event-list.server.ts", ["readEventList"], READ],
  ["lib/storefront/catalog-grid.server.ts", ["readCatalogGrid"], READ],
  ["lib/storefront/cart-checkout.server.ts", ["readCartCheckout"], READ],
  ["lib/storefront/portal-entry.server.ts", ["readPortalEntry"], READ],
  ["lib/scheduling/appointments-actions.ts", ["loadAppointments", "loadSessionWaitlists", "loadBookingHoursProposals"], READ],
  ["lib/talent-integrations/actions.ts", ["fetchTalentConnectionSettingsAction", "fetchTalentFeaturedMediaAction"], READ],
  ["lib/server-actions/admin-talent-skills.ts", ["getResolvedSkills", "getEnabledParentCategoriesForPicker", "getAgencySkillOverrides", "getAspirations", "getTalentTypesUnderParent", "getUnpublishableSkillsForTenant"], READ],
  ["lib/server-actions/admin-user-workspaces.ts", ["actionLoadUserWorkspaces"], READ],
  ["lib/server-actions/admin-site-posts.ts", ["getPostForEditAction"], READ],
  ["lib/server-actions/admin-talent-field-values.ts", ["getTalentFieldValues", "getTalentFieldValueHistory"], READ],
  ["lib/server-actions/admin-taxonomy.ts", ["getResolverMetricsSnapshot", "getEnabledTaxonomyTree", "getCategoryDetail", "getFieldsForTalent"], READ],
  ["lib/server-actions/staff-resources.ts", ["listStaffResources"], READ],
  ["lib/server-actions/admin-workspace-default-currency.ts", ["loadAgencyDefaultCurrency"], READ],
  ["lib/server-actions/admin-cms-revisions.ts", ["listCmsPageRevisions", "listCmsPostRevisions", "getCmsPageRevisionForRestore", "getCmsPostRevisionForRestore"], READ],
  ["lib/server-actions/booking-policy-overrides-settings.ts", ["loadPolicyOverridesAction"], READ],
  ["lib/server-actions/details-tab-data.ts", ["loadDetailsTabData"], READ],
  ["lib/server-actions/pos-engine.ts", ["posCurrentDeviceSession"], READ],
  ["lib/server-actions/page-role-actions.ts", ["readPageRolesAction"], READ],
  ["lib/server-actions/load-talent-profile-editor-data.ts", ["loadTalentProfileEditorData"], READ],
  ["lib/server-actions/admin-platform-default-theme.ts", ["loadPlatformDefaultThemeAction"], READ],
  ["lib/server-actions/admin-code-snippets.ts", ["listCodeSnippets"], READ],
  ["lib/server-actions/admin-workspace-field-settings.ts", ["getFieldPrivacyCatalog", "getWorkspaceFieldSettings", "getWorkspaceFieldCatalog"], READ],
  ["lib/server-actions/admin-stripe-connect.ts", ["getConnectSnapshotAction"], READ],
  ["lib/server-actions/talent-hero-text.ts", ["loadHeroTextFields"], READ],
  ["lib/server-actions/roster-import.ts", ["listRosterImportJobs"], READ],
  ["lib/server-actions/trial-door.ts", ["loadTrialDoorOffer"], READ],
  ["lib/server-actions/spaces-editor.ts", ["loadSpacesSnapshot"], READ],
  ["lib/server-actions/admin-talent-translations.ts", ["adminLoadBioTranslationPanelData"], READ],
  ["lib/server-actions/admin-talent-extras.ts", ["getTrustBadges", "getAgencyMediaForTenant"], READ],
  ["lib/server-actions/admin-talent-languages.ts", ["getTalentLanguages"], READ],
  ["lib/server-actions/media-download.ts", ["actionGetMediaDownloadLink"], READ],
  ["lib/server-actions/admin-workspace-settings.ts", ["loadAgencyAutoAck", "loadWorkspaceAccountSettings", "loadAgencyBrandingSettings"], READ],
  ["lib/server-actions/admin-tracking.ts", ["readTrackingSettings"], READ],
  ["lib/server-actions/catalog-engine-reads.ts", ["loadOfferingComponentsAction", "loadOfferingPricePhasesAction"], READ],
  ["lib/server-actions/admin-roster-rates.ts", ["loadRosterRates"], READ],
  ["lib/server-actions/admin-discover-exposure.ts", ["loadDiscoverExposure"], READ],
  ["lib/server-actions/message-stars.ts", ["loadMyStarredMessageIds"], READ],
  ["lib/server-actions/admin-media-release.ts", ["actionListMediaReleaseRequests", "actionListMediaReleaseHistory", "actionListReleaseBakeRepairs"], READ],
  ["lib/server-actions/venue-engine.ts", ["locationsList", "partyWaitlistList", "layoutsList", "servicePeriodsList", "prepStationsList", "guestVisitMenu", "guestVisitBill", "ticketLookup", "posDevicesList"], READ],
  ["lib/server-actions/payment-methods.ts", ["listPaymentMethods"], READ],
  ["lib/server-actions/workspace-plan-summary.ts", ["loadWorkspacePlanSummary"], READ],
  ["lib/server-actions/pay-link-public-url.ts", ["resolvePayLinkPublicUrl"], READ],
  ["lib/server-actions/pos-modes.ts", ["getPosModes", "getLocationModes"], READ],
  ["lib/server-actions/roster-direct-booking.ts", ["loadRosterDirectBooking"], READ],
  ["lib/server-actions/admin-talent-contexts.ts", ["getResolvedContexts", "getContextCatalog"], READ],
  ["lib/server-actions/admin-branding-media.ts", ["actionListBrandingMedia"], READ],
  ["lib/server-actions/pos-location-facts.ts", ["getPosLocationFacts"], READ],
  ["lib/server-actions/admin-platform-default-templates.ts", ["loadPlatformDefaultTemplatesAction"], READ],
  ["lib/server-actions/commercial-terms-tenant.ts", ["loadTenantCommercialTerms"], READ],
  ["lib/server-actions/booking-hours.ts", ["listBookingHoursTargets", "loadBookingHours"], READ],
  ["lib/server-actions/admin-talent-hub-face.ts", ["actionLoadTalentHubFace"], READ],
  ["lib/server-actions/talent-field-values-catalog.ts", ["getTalentFieldValuesAsTalent", "getFieldsForTalentAsTalent"], READ],
  ["lib/server-actions/booking-policy-facts.ts", ["getBookingPolicyFacts"], READ],
  ["lib/server-actions/admin-talent-profile-sections.ts", ["getTalentPublishReadiness", "getTalentProfileDynFieldValuesForShell", "getTalentProfileActivity", "getTalentProfileEditorData"], READ],
  ["lib/server-actions/admin-translations-tax-loc.ts", ["adminLoadTaxonomyTranslationPanelData", "adminLoadLocationTranslationPanelData"], READ],
  ["lib/server-actions/industry-settings.ts", ["loadIndustrySettings"], READ],
  ["lib/server-actions/payment-providers.ts", ["getPaymentProviderStatus"], READ],
  ["lib/server-actions/appointments-settings-tenant.ts", ["loadTenantAppointmentsSettings"], READ],
  ["lib/server-actions/admin-tenant-fonts.ts", ["actionListTenantFonts"], READ],
  ["lib/server-actions/representation-actions.ts", ["loadRepresentationForAgencyAdmin"], READ],
  ["lib/server-actions/admin-talent-service-areas.ts", ["getTalentServiceAreasForTalent"], READ],
  ["lib/server-actions/admin-talent-metrics.ts", ["getTalentMetrics"], READ],
  ["lib/server-actions/role-limits-settings.ts", ["loadRoleLimitsAction", "loadApprovalRequestsAction"], READ],
  ["lib/server-actions/admin-site-pages.ts", ["listPagesForPickerAction"], READ],
  ["lib/server-actions/search-talent.ts", ["searchTalent"], READ],
  ["lib/server-actions/workspace-type.ts", ["getWorkspaceTypePreflight"], READ],
  ["lib/server-actions/admin-plan-downgrade.ts", ["getDowngradePreflight"], READ],
  ["lib/server-actions/message-media.ts", ["getMessageMediaUrl"], READ],
  ["lib/server-actions/voice-notes.ts", ["getVoicePlaybackUrl"], READ],
  ["lib/server-actions/admin-profile-template.ts", ["loadProfileTemplateFamily"], READ],
  ["lib/server-actions/admin-translation-quick-edit.ts", ["loadTranslationQuickEditPayload"], READ],
  ["lib/server-actions/admin-guest-chat-settings.ts", ["loadGuestChatSettingsForAdmin"], READ],
  ["lib/server-actions/admin-product-discounts.ts", ["listDiscountRedemptions", "validateDiscount"], READ],
  ["lib/server-actions/runs-events.ts", ["getRunsEvents"], READ],
  ["lib/server-actions/admin-pricing-defaults.ts", ["loadTenantPricingDefaultsAction"], READ],
  ["lib/server-actions/hybrid-identity-self.ts", ["loadHybridSwitcherProps"], READ],
  ["lib/server-actions/venue-settings.ts", ["loadVenueSettings"], READ],
  ["lib/server-actions/admin-subscription-discounts.ts", ["loadAccountDiscounts", "searchAssignableAccounts"], READ],
  ["lib/call-sheet/actions.ts", ["loadBookingCallSheet"], READ],
  ["lib/site-admin/site-shell-surface-availability.ts", ["isSiteShellSurfaceAvailableAction"], READ],
  ["lib/site-admin/cms-seo-actions.ts", ["loadPageSeoAction", "listRedirectsAction"], READ],
  ["lib/site-admin/site-header/actions.ts", ["loadHeaderSectionAction", "loadHeaderConfigAction"], READ],
  ["lib/site-admin/builder-core/lab/preview-subject-search.ts", ["searchLabTalentSubjects", "searchLabWorkspaceSubjects"], READ],
  ["lib/site-admin/builder-core/lab/tenant-rollout-search.ts", ["searchTenantsForRollout", "resolveTenantIdsForRollout", "getTotalActiveTenantCount"], READ],
  ["lib/site-admin/builder-core/adapters/cms-page-actions.ts", ["loadCmsFreeformPage", "loadCmsFreeformLocaleSettings"], READ],
  ["lib/site-admin/builder-core/lab/lab-canvas-render-data.ts", ["buildLabCanvasRenderData"], READ],
  ["lib/site-admin/builder-core/adapters/site-shell-actions.ts", ["loadSiteShellRow"], READ],
  ["lib/site-admin/builder-core/adapters/talent-site-shell-actions.ts", ["loadTalentSiteShellRow", "loadTalentSiteShellRevisionsAction"], READ],
  ["lib/site-admin/builder-core/adapters/talent-page-actions.ts", ["loadTalentPageAction"], READ],
  ["lib/site-admin/builder-core/adapters/print-actions.ts", ["listTenantPrintDesignsAction", "loadPrintDesignAction"], READ],
  ["lib/site-admin/builder-core/adapters/theme-template-actions.ts", ["loadThemeTemplateTreeAction"], READ],
  ["lib/site-admin/builder-core/templates/registry-actions.ts", ["getPublishDiff", "scanComponentDependents", "loadHideImpact", "listPublishedTemplates"], READ],
  ["lib/site-admin/builder-core/templates/builder-lab-audit.ts", ["listBuilderLabAudit"], READ],
  ["lib/site-admin/builder-core/templates/template-usage-actions.ts", ["getTemplateUsageTotals"], READ],
  ["lib/site-admin/builder-core/templates/import-builtin-starters.ts", ["listStarterTemplatesAction", "checkBuiltinStarterDriftAction"], READ],
  ["lib/site-admin/builder-core/templates/catalog-overlay-actions.ts", ["listCatalogOverlays", "getCatalogVersion", "loadOverlayHistory"], READ],
  ["lib/site-admin/builder-core/templates/registry-admin-actions.ts", ["listAllTemplates", "getTemplateById", "resolveLabMediaTenantId", "resolveTemplateThumbnails", "listTemplateRevisions"], READ],
  ["lib/site-admin/builder-core/templates/taxonomy-actions.ts", ["listTemplateTaxonomy"], READ],
  ["lib/site-admin/add-gallery/catalog-admin-view-action.ts", ["loadCatalogAdminView", "loadCatalogUsageCounts"], READ],
  ["lib/site-admin/add-gallery/component-usage-action.ts", ["loadComponentUsageTally"], READ],
  ["lib/site-admin/add-gallery/gallery-fetch-action.ts", ["fetchSurfaceGalleryItems"], READ],
  ["lib/site-admin/add-gallery/catalog-structure-actions.ts", ["listCatalogStructure"], READ],
  ["lib/site-admin/server/directory-catalogs.ts", ["readDirectoryLiveCatalogSnapshot", "readCardDesignFieldCandidates"], READ],
  ["lib/site-admin/builder-node/portfolio-albums-actions.ts", ["loadTalentMediaAlbumsForEditor"], READ],
  ["lib/site-admin/site-footer/actions.ts", ["loadFooterConfigAction"], READ],
  ["lib/site-admin/links/actions.ts", ["listLinksForPickerAction"], READ],
  ["lib/site-admin/events/inspector-actions.ts", ["listEventsForInspectorAction", "listEventTiersForInspectorAction", "resolveLinkedEventForPageInspectorAction"], READ],
  ["lib/site-admin/edit-mode/publish-diff-action.ts", ["loadPublishedSnapshotRowsAction"], READ],
  ["lib/site-admin/edit-mode/starter-action.ts", ["loadStarterAvailability"], READ],
  ["lib/site-admin/edit-mode/form-inbox-sections-action.ts", ["listInboxFormSectionsAction"], READ],
  ["lib/site-admin/edit-mode/builder-components-action.ts", ["listBuilderComponents"], READ],
  ["lib/site-admin/edit-mode/talent-paths-action.ts", ["loadTalentPathsForLinkPicker"], READ],
  ["lib/site-admin/edit-mode/page-composer-action.ts", ["listComposablePages"], READ],
  ["lib/site-admin/edit-mode/revisions-actions.ts", ["loadHomepageRevisionsAction", "loadPageRevisionsAction", "fetchNewestDraftRevisionIdAction", "loadPublishDiffRevisionIdsAction", "loadRevisionDiffAction"], READ],
  ["lib/site-admin/edit-mode/composition-actions.ts", ["loadHomepageCompositionAction"], READ],
  ["lib/site-admin/edit-mode/design-actions.ts", ["loadDesignAction"], READ],
  ["lib/site-admin/edit-mode/section-actions.ts", ["loadSectionForEditAction"], READ],
  ["lib/site-admin/edit-mode/talent-picker-action.ts", ["searchTenantTalent"], READ],
  ["lib/site-admin/edit-mode/assets-actions.ts", ["scanAssetUsageAction"], READ],
  ["lib/site-admin/edit-mode/aria-landmark-action.ts", ["runAriaLandmarkCheck"], READ],
  ["lib/site-admin/edit-mode/comment-actions.ts", ["listCommentsAction"], READ],
  ["lib/site-admin/edit-mode/talent-design-actions.ts", ["loadTalentDesignAction"], READ],
  ["lib/site-admin/edit-mode/cms-pages-list-action.ts", ["loadCmsPagesForLinkPicker"], READ],
  ["lib/site-admin/edit-mode/link-validate-action.ts", ["validateLinkUrl"], READ],
  ["lib/site-admin/edit-mode/heading-lint-action.ts", ["loadHeadingProbeForLint"], READ],
  ["lib/site-admin/edit-mode/workspace-templates-action.ts", ["listWorkspaceTemplates"], READ],
  ["lib/site-admin/edit-mode/schedule-actions.ts", ["loadScheduledPublishAction"], READ],
  ["lib/site-admin/edit-mode/talent-search.ts", ["searchAgencyTalentAction", "resolveTalentByCodesAction", "resolveTalentByIdsAction"], READ],
  ["lib/site-admin/edit-mode/publish-preflight-action.ts", ["runPublishPreflight"], READ],
  ["lib/site-admin/collections/actions.ts", ["listCollectionsAction", "getCollectionAction"], READ],
  ["lib/search/global-search.ts", ["globalSearch"], READ],
  ["lib/sessions/roster-actions.ts", ["loadSessionParticipants"], READ],
  ["lib/sessions/schedule-actions.ts", ["loadSchedule", "loadSchedulableEvents"], READ],
  ["lib/support/guest-actions.ts", ["getGuestSupportThreadAction", "listGuestSupportThreadsAction"], READ],
  ["lib/support/hq-actions.ts", ["hqLoadTicketDetailAction"], READ],
  ["lib/support/insights/actions.ts", ["hqLoadTicketInsightAction"], READ],
  ["lib/support/attachment-actions.ts", ["getSupportAttachmentUrlAction"], READ],
  ["lib/support/replay/replay-actions.ts", ["loadSupportReplayBufferSetting", "hqListReplaySessionsAction"], READ],
  ["lib/talent-calendar/actions.ts", ["listTalentAvailabilityBlocks"], READ],
  ["lib/talent-calendar/hold-actions.ts", ["loadHoldsForInquiry", "checkTalentAvailability"], READ],
  ["lib/menu-import/import-actions.ts", ["previewMenuImport"], READ],
  ["lib/client-integrations/actions.ts", ["fetchClientConnectionSettingsAction"], READ],
  ["lib/account/deletion-actions.ts", ["getAccountDeletionStatus"], READ],
  ["lib/talent-policies/actions.ts", ["loadPolicyScreen"], READ],
  ["lib/notifications/my-notifications-actions.ts", ["loadMyNotifications"], READ],
  ["lib/talent/profile-embeds/actions.ts", ["fetchTalentProfileExtrasAction"], READ],
  ["lib/reviews/review-owner-actions.ts", ["loadOwnerReceivedReviewsAction", "loadOwnerPrivateNoteThemesAction", "loadReviewAnalyticsAction"], READ],
  ["lib/reviews/review-moderation-queue-actions.ts", ["loadReportedReviewsAction", "loadModerationIntegritySignalsAction"], READ],
  ["lib/reviews/review-request-actions.ts", ["loadReviewRequestsForOwnerAction", "reviewsEnabledForTenantAction"], READ],
  ["lib/reviews/review-token-actions.ts", ["loadReviewInviteByToken"], READ],
  ["lib/channels/pairing-actions.ts", ["loadWhatsAppConnection"], READ],
  ["lib/media/asset-assignments-actions.ts", ["actionListAssetAssignments"], READ],
  ["app/auth/actions.ts", ["signOut"], "SIGN-OUT: ends the session; must keep working while impersonating (PM exception)"],
  ["lib/server-actions/admin-impersonation.ts", ["endImpersonationToAdmin"], "STOP-IMPERSONATION: ends the viewing-as session; must keep working while impersonating (PM exception)"],
  ["lib/support/desk/desk-sign-out.ts", ["deskSignOutToLogin"], "SIGN-OUT: ends the support desk session; must keep working while impersonating (PM exception)"],
];

/**
 * Route handlers (route.ts exporting POST/PUT/PATCH/DELETE) that are NOT guarded,
 * with a one-line reason. Everything else under src/app must call the guard first.
 */
export const ROUTE_ALLOW: Array<[suffix: string, reason: string]> = [
  ["auth/sign-out/route.ts", "SIGN-OUT: ends the session; must keep working while impersonating (PM exception)"],
  ["api/discover/subscriptions/webhook/route.ts", "webhook: Stripe-signature authenticated, no user session"],
  ["api/webhooks/stripe-v2/route.ts", "webhook: Stripe-signature authenticated, no user session"],
  ["api/webhooks/stripe-mx/route.ts", "webhook: Stripe-signature authenticated, no user session"],
  ["api/webhooks/stripe/route.ts", "webhook: Stripe-signature authenticated, no user session"],
  ["api/stripe/webhook/route.ts", "webhook: Stripe-signature authenticated, no user session"],
  ["api/webhooks/messaging/[channel]/route.ts", "webhook: provider-signature authenticated, no user session"],
  ["api/webhooks/resend/route.ts", "webhook: Svix-signature authenticated, no user session"],
  ["api/hooks/auth-email/route.ts", "Supabase auth hook: secret authenticated, no user session"],
  ["api/cron/revalidate-talent-site/route.ts", "cron: secret authenticated, no user session"],
  ["api/unsubscribe/[token]/route.ts", "token-authenticated unsubscribe link, no user session"],
  ["api/analytics/events/route.ts", "anonymous telemetry beacon, no actor identity and no user data written"],
  ["api/ai/search/route.ts", "POST used as a read: search query in, results out, nothing stored"],
  ["api/ai/interpret-search/route.ts", "POST used as a read: interprets a query, nothing stored"],
  ["api/ai/refine-suggestions/route.ts", "POST used as a read: returns suggestions, nothing stored"],
  ["api/directory/talents-by-ids/route.ts", "POST used as a read: batch lookup of public talent cards"],
];
