/**
 * Strings for Website settings > Policies and privacy. English is the key,
 * Spanish (tú) the value. Kept beside the screen, not in the grandfathered
 * dashboard map, so the map's size budget is untouched. No em dashes.
 */

export const POLICIES_ES: Record<string, string> = {
  "Policies and privacy": "Políticas y privacidad",
  "Cancelling, deposit and what your clients read before they book": "Cancelación, anticipo y lo que leen tus clientas antes de reservar",
  PROPOSED: "PROPUESTO",
  "Published · version {n}": "Publicadas · versión {n}",
  "Not published yet": "Aún sin publicar",
  "Your clients read these rules before they book. Most of it comes from settings you already have; you only answer the two questions below.":
    "Tus clientas leen estas reglas antes de reservar. Casi todo viene de ajustes que ya tienes; solo respondes las dos preguntas de abajo.",
  "Taken from your settings": "Tomado de tus ajustes",
  "From your settings": "De tus ajustes",
  "Payment when booking": "Pago al reservar",
  "Payment in person": "Pago en persona",
  "Cancelling and changes": "Cancelación y cambios",
  "Where you work": "Dónde trabajas",
  Contact: "Contacto",
  "{pct}% deposit": "Anticipo del {pct}%",
  "No deposit": "Sin anticipo",
  "Not set": "Sin definir",
  "Free until {h} h before": "Gratis hasta {h} h antes",
  "Flexible": "Flexible",
  "Chat": "Chat",
  "Cash": "Efectivo",
  "Bank transfer": "Transferencia",
  "Card on your terminal": "Tarjeta con tu terminal",
  "At your studio": "En tu estudio",
  "At the client's place": "En casa de la clienta",
  "Online": "En línea",
  "Edit in Payments": "Editar en Pagos",
  "Edit in Client self-service": "Editar en Autogestión",
  "Edit in Services": "Editar en Servicios",
  "Edit in Chat and inquiries": "Editar en Chat y consultas",
  "Your answers": "Tus respuestas",
  "If a client cancels late or does not show up": "Si una clienta cancela tarde o no llega",
  "The deposit is not returned": "No se devuelve el anticipo",
  "Half of the deposit is returned": "Se devuelve la mitad del anticipo",
  "Everything is returned": "Se devuelve todo",
  "Applies to cancellations inside your free window.": "Aplica a cancelaciones dentro de tu ventana gratuita.",
  "You take no deposit, so nothing is held. These choices apply once you ask for one.": "No pides anticipo, así que no se retiene nada. Estas opciones aplican cuando pidas uno.",
  "Tolerance for arriving late": "Tolerancia por llegada tarde",
  "After this the appointment can be shortened.": "Pasado este tiempo la cita puede acortarse.",
  "How your clients will read it": "Así lo leerán tus clientas",
  "Spanish": "Español",
  "English": "Inglés",
  "Privacy and documents": "Privacidad y documentos",
  "Payments and personal data are covered by Tulala's own documents. They open on tulala.digital.":
    "Los pagos y los datos personales los cubren los documentos de Tulala. Se abren en tulala.digital.",
  "Terms of service": "Términos del servicio",
  "Privacy notice": "Aviso de privacidad",
  Discard: "Descartar",
  "Review and publish": "Revisar y publicar",
  "Nothing new to publish.": "No hay nada nuevo que publicar.",
  "Publish version {n}?": "¿Publicar la versión {n}?",
  "This is what changes for your clients:": "Esto es lo que cambia para tus clientas:",
  "First version. Your clients will read all {n} points.": "Primera versión. Tus clientas leerán los {n} puntos.",
  Before: "Antes",
  After: "Ahora",
  New: "Nuevo",
  Removed: "Quitado",
  "Publish version {n}": "Publicar versión {n}",
  Publishing: "Publicando",
  "Keep editing": "Seguir editando",
  "Could not publish. Try again in a moment.": "No se pudo publicar. Inténtalo de nuevo en un momento.",
  "Published · version {n} is live.": "Publicada la versión {n}. Ya está en vivo.",
  "Your settings could not load. Try again in a moment.": "Tus ajustes no se pudieron cargar. Inténtalo de nuevo en un momento.",
  "Loading…": "Cargando…",
  "Settings": "Ajustes",
  Less: "Menos",
  More: "Más",
  "Your own rules (optional)": "Tus propias reglas (opcional)",
  "Write one rule per line. They appear after the points above, as a numbered list. Up to {n} rules, {c} characters each.":
    "Escribe una regla por línea. Aparecen después de los puntos de arriba, en una lista numerada. Hasta {n} reglas, de {c} caracteres cada una.",
  "If a language is empty, your clients read the other one.": "Si un idioma está vacío, tus clientas leen el otro.",
  "Saved. Your rules are live.": "Guardado. Tus reglas ya están en vivo.",
  "Too many rules. The most is {n} per language.": "Demasiadas reglas. El máximo es {n} por idioma.",
  "One rule is too long. The most is {c} characters.": "Una regla es demasiado larga. El máximo es {c} caracteres.",
  "Could not save. Try again in a moment.": "No se pudo guardar. Inténtalo de nuevo en un momento.",
  Saving: "Guardando",
  "Save rules": "Guardar reglas",
  "Preview your policies page": "Ver tu página de políticas",
  "Language of the preview": "Idioma de la vista previa",
};
