/** EN/ES copy for Maison Choose-a-design + Theme detail (PR4). */
export type MaisonSetupLocale = "en" | "es";

const ES: Record<string, string> = {
  "Choose a design": "Elige un diseño",
  Today: "Hoy",
  "Your free website": "Tu sitio web gratis",
  "Find your website style": "Encuentra el estilo de tu sitio",
  // TUL-331 / G12: honest finished-gallery count (no aspirational library size).
  "{n} designs ready today. Preview any with your photos and services.":
    "{n} diseños listos hoy. Previsualiza cualquiera con tus fotos y servicios.",
  "1 design ready today. Preview it with your photos and services.":
    "1 diseño listo hoy. Previsualízalo con tus fotos y servicios.",
  "Explore designs, then see them with your photos and services.":
    "Explora diseños y míralos con tus fotos y servicios.",
  "Featured demo:": "Demo destacada:",
  "1 demo": "1 demo",
  "Explore theme →": "Explorar tema →",
  "Every design works for any profession: you will see it with your own photos and services before choosing.":
    "Cada diseño sirve para cualquier oficio: lo verás con tus fotos y servicios antes de elegir.",
  "Designs": "Diseños",
  "Demos · 1": "Demos · 1",
  "THEME": "TEMA",
  "Demo:": "Demo:",
  "Show": "Mostrar",
  Demo: "Demo",
  "My content": "Mi contenido",
  "Demo photos, text and prices. Nothing is added to your site unless you import it.":
    "Fotos, textos y precios de demo. Nada se agrega a tu sitio salvo que importes.",
  "Your profile, services and photos in this design. Sections without content are hidden.":
    "Tu perfil, servicios y fotos en este diseño. Las secciones sin contenido se ocultan.",
  Colors: "Colores",
  "Demo colors": "Colores de la demo",
  "Use demo colors": "Usar colores de la demo",
  "Custom colors": "Colores personalizados",
  Personalise: "Personalizar",
  "Import starter content · 13 available ›": "Importar contenido inicial · 13 disponibles ›",
  "Optional. Imported items are saved as drafts.":
    "Opcional. Lo importado se guarda como borradores.",
  "Use this design": "Usar este diseño",
  Preview: "Vista previa",
  "Choices saved": "Elecciones guardadas",
  "Draft saved": "Borrador guardado",
  Live: "En vivo",
  Desktop: "Escritorio",
  Phone: "Teléfono",
  "DEMO CONTENT": "CONTENIDO DEMO",
  "Only colors change. Photos, content and layout stay.":
    "Solo cambian los colores. Fotos, contenido y diseño se quedan.",
  "About this theme": "Sobre este tema",
  "Switching demos changes sample photos, text and prices — not your saved site.":
    "Cambiar de demo cambia fotos, textos y precios de muestra — no tu sitio guardado.",
  Close: "Cerrar",
  Editorial: "Editorial",
  Warm: "Cálido",
  "Service menu": "Menú de servicios",
  "Booking-ready": "Listo para reservar",
  Portfolio: "Portafolio",
  "Import opens in a later step.": "La importación llega en un paso posterior.",
  "Apply & review land in the next release. Your choices are saved.":
    "Aplicar y revisar llegan en la siguiente versión. Tus elecciones están guardadas.",
  "Review your website": "Revisa tu sitio",
  "Ready to publish": "Listo para publicar",
  "1 thing before publishing": "1 cosa antes de publicar",
  Publish: "Publicar",
  "Publish site": "Publicar sitio",
  "Publishing…": "Publicando…",
  Undo: "Deshacer",
  "Design applied to your draft": "Diseño aplicado a tu borrador",
  "Nothing is public until you publish. After publishing you can change the design at any time.":
    "Nada es público hasta que publiques. Después puedes cambiar el diseño cuando quieras.",
  "My website": "Mi sitio web",
  "Your content": "Tu contenido",
  "Demo content": "Contenido demo",
  "Design:": "Diseño:",
  "Maison (original)": "Maison (original)",
  "Custom design": "Diseño personalizado",
  "Your colors": "Tus colores",
  since: "desde",
  "Website preview": "Vista previa del sitio",
  "Unpublished changes": "Cambios sin publicar",
  "No unpublished changes": "Sin cambios sin publicar",
  "Edit site": "Editar sitio",
  Republish: "Republicar",
  Published: "Publicado",
  "View site": "Ver sitio",
  "Review before publishing": "Revisar antes de publicar",
  "Apply a design before publishing.": "Aplica un diseño antes de publicar.",
  "View website": "Ver sitio",
  "Change design": "Cambiar diseño",
  "Design options": "Opciones de diseño",
  "Design options open in a later step.":
    "Las opciones de diseño llegan en un paso posterior.",
  "Your website is live": "Tu sitio ya está en vivo",
  "Could not publish. Try again.": "No se pudo publicar. Inténtalo de nuevo.",
  "Try again": "Intentar de nuevo",
  Address: "Dirección",
  Design: "Diseño",
  "Publish new colors?": "¿Publicar colores nuevos?",
  "Publish changes": "Publicar cambios",
  "Keep editing": "Seguir editando",
  "Change design in draft": "Cambiar diseño en el borrador",
  "Change and publish now": "Cambiar y publicar ahora",
  "Only colors change. Your services, photos, text, sections and layout stay exactly as they are.":
    "Solo cambian los colores. Tus servicios, fotos, textos, secciones y diseño se quedan exactamente igual.",
  "Your live site stays as it is until you publish.":
    "Tu sitio en vivo se queda igual hasta que publiques.",
  "The preview didn't load": "La vista previa no cargó",
  "Your choices are saved. Try again.":
    "Tus elecciones están guardadas. Inténtalo de nuevo.",
  "Reset colors": "Restablecer colores",
  "Back to the demo colors, Pink & Lipstick.":
    "Vuelve a los colores de la demo, Rosa y labial.",
  Reset: "Restablecer",
  "Reapply demo layout": "Reaplicar diseño de la demo",
  "Section order and menu style return to the demo's. Your content stays.":
    "El orden de secciones y el estilo del menú vuelven a los de la demo. Tu contenido se queda.",
  Reapply: "Reaplicar",
  "Refresh from my profile": "Actualizar desde mi perfil",
  "Pull your latest photos, name, bio and services into this design.":
    "Trae tus fotos, nombre, bio y servicios más recientes a este diseño.",
  Refresh: "Actualizar",
  "Content refreshed from your profile": "Contenido actualizado desde tu perfil",
  "Discard design changes": "Descartar cambios de diseño",
  "Drop unpublished design changes.": "Descarta los cambios de diseño sin publicar.",
  "No unpublished design changes right now.":
    "No hay cambios de diseño sin publicar ahora.",
  Discard: "Descartar",
  "Undo import": "Deshacer importación",
  "Restore previous design": "Restaurar diseño anterior",
  "Bring back a published version as a draft.":
    "Trae de vuelta una versión publicada como borrador.",
  Choose: "Elegir",
  Restore: "Restaurar",
  "Restoring puts that design in your draft. The live site changes only when you publish.":
    "Restaurar pone ese diseño en tu borrador. El sitio en vivo cambia solo cuando publiques.",
  "Colors reset to draft": "Colores restablecidos en el borrador",
  "Demo layout reapplied": "Diseño de la demo reaplicado",
  "Unpublished design changes discarded": "Cambios de diseño sin publicar descartados",
  "Import undone": "Importación deshecha",
  "Previous design restored to your draft": "Diseño anterior restaurado en tu borrador",
  "Demo only · nothing was booked": "Solo demo · no se reservó nada",
  // P3 browse gallery
  "Search a profession or theme": "Busca una profesión o un tema",
  "Clear search": "Borrar búsqueda",
  All: "Todas",
  Beauty: "Belleza",
  Models: "Modelos",
  Music: "Música",
  Food: "Comida",
  Fitness: "Fitness",
  Wellness: "Bienestar",
  Creative: "Creativos",
  Events: "Eventos",
  "Home & local": "Hogar y local",
  Tech: "Tecnología",
  "Visual style": "Estilo visual",
  Tags: "Etiquetas",
  Any: "Cualquiera",
  "Combined talents": "Talentos combinados",
  "Reset filters": "Restablecer filtros",
  Style: "Estilo",
  "Layout and features": "Diseño y funciones",
  "Show {n} themes": "Ver {n} temas",
  "Show 1 theme": "Ver 1 tema",
  Minimal: "Minimalista",
  Bold: "Audaz",
  "Image-led": "Con foco en imágenes",
  Dark: "Oscuro",
  "Project stories": "Historias de proyectos",
  "Service list": "Lista de servicios",
  "Text-first": "Texto primero",
  "Video & media": "Video y multimedia",
  "Quote requests": "Solicitudes de cotización",
  Chapters: "Capítulos",
  "Bento tiles": "Mosaico bento",
  Packages: "Paquetes",
  "Personal story": "Historia personal",
  Classes: "Clases",
  "Multi-talent": "Multitalento",
  "Suggested from your profile: {a} and {b}. Every theme stays open to you.":
    "Sugeridos por tu perfil: {a} y {b}. Todos los temas siguen disponibles.",
  "Suggested from your profile: {a}. Every theme stays open to you.":
    "Sugerido por tu perfil: {a}. Todos los temas siguen disponibles.",
  "{n} demos in {m} themes": "{n} demos en {m} temas",
  "{n} demos in 1 theme": "{n} demos en 1 tema",
  "1 demo in 1 theme": "1 demo en 1 tema",
  for: "para",
  " or ": " o ",
  " · matching either": " · coincide cualquiera",
  "{m} themes · {n} demos": "{m} temas · {n} demos",
  "1 theme · {n} demos": "1 tema · {n} demos",
  Suggested: "Sugerido",
  "Last viewed": "Visto por último",
  "Combines both": "Combina ambos",
  "Also matches one of them": "También coincide con uno",
  "Matching demo:": "Demo que coincide:",
  "{n} demos": "{n} demos",
  "{n} matching demos": "{n} demos coinciden",
  "1 matching demo": "1 demo coincide",
  Explore: "Explorar",
  "{n} demos · {m} themes": "{n} demos · {m} temas",
  "{n} demos · 1 theme": "{n} demos · 1 tema",
  "same results as {x}": "mismos resultados que {x}",
  "{x} (Spanish)": "{x} (español)",
  "{x} (English)": "{x} (inglés)",
  "No demos for “{q}” with these filters": "Ningún demo para “{q}” con estos filtros",
  "No themes with these filters": "Ningún tema con estos filtros",
  "Every theme works for any profession. Try a nearby word, or reset the filters to see all {n} themes.":
    "Todos los temas sirven para cualquier profesión. Prueba una palabra cercana o restablece los filtros para ver los {n} temas.",
  "Changing the design of {address}. The live site stays as it is until you publish.":
    "Cambiando el diseño de {address}. El sitio publicado no cambia hasta que publiques.",
  "Back to My website": "Volver a Mi sitio",
  "Remove {x}": "Quitar {x}",
  Search: "Buscar",
  // Wave 3 gallery redesign
  Filters: "Filtros",
  "Suggested for you": "Sugerido para ti",
  Unpublished: "Sin publicar",
  "See with my content": "Ver con mi contenido",
  "Use demo content": "Usar contenido del demo",
  Advanced: "Avanzado",
  Domain: "Dominio",
  Questions: "Preguntas",
  Settings: "Ajustes",
  Apps: "Apps",
  History: "Historial",
  "Copy address": "Copiar dirección",
  "Open site": "Abrir sitio",
  "Save colors": "Guardar colores",
  "Text is readable": "El texto se lee bien",
  "Adjust button contrast": "Ajustar contraste del botón",
  "Adjust text contrast": "Ajustar contraste del texto",
  "Use this adjustment": "Usar este ajuste",
  "Keep my color": "Conservar mi color",
  "Contrast details": "Detalles de contraste",
  "Palette name": "Nombre de la paleta",
  "Page background": "Fondo de página",
  Text: "Texto",
  "Buttons and accents": "Botones y acentos",
  "Section background": "Fondo de sección",
  "My colors": "Mis colores",
};

export function maisonSetupT(locale: MaisonSetupLocale, key: string): string {
  if (locale === "es") return ES[key] ?? key;
  return key;
}

export function tagLabel(locale: MaisonSetupLocale, key: string): string {
  const map: Record<string, { en: string; es: string }> = {
    editorial: { en: "Editorial", es: "Editorial" },
    warm: { en: "Warm", es: "Cálido" },
    menu: { en: "Service menu", es: "Menú de servicios" },
    booking: { en: "Booking-ready", es: "Listo para reservar" },
    portfolio: { en: "Portfolio", es: "Portafolio" },
  };
  const row = map[key];
  if (!row) return key;
  return locale === "es" ? row.es : row.en;
}
