/**
 * Jor week fixture — Wed 23 Sep 2026 09:50 America/Cancun.
 * Numbers match the prototype scenario sheet.
 */

import type { TalentAgendaItem } from "../types";

export const JOR_CLOCK = new Date("2026-09-23T09:50:00-05:00");
export const JOR_DAY_KEY = "2026-09-23";
export const JOR_TZ = "America/Cancun";

function item(partial: TalentAgendaItem): TalentAgendaItem {
  return partial;
}

/** Prototype: 3 confirmed today 60+135+90 = 285 min; still to collect 1050+950+620. */
export const JOR_WEEK: TalentAgendaItem[] = [
  item({
    id: "jor-today-1",
    kind: "booking",
    ref: { table: "talent_bookings", id: "jor-today-1" },
    client: { name: "Camila Ruiz", initials: "CR" },
    title: "Gel set",
    lines: [{ label: "Gel set", cents: 105000 }],
    startsAt: "2026-09-23T10:00:00-05:00",
    endsAt: "2026-09-23T11:00:00-05:00",
    allDay: false,
    tz: JOR_TZ,
    where: { mode: "studio", label: "Studio" },
    bufferAfterMin: 15,
    booking: "confirmed",
    payment: "due",
    money: { totalCents: 105000, paidCents: 0, dueCents: 105000, currency: "MXN" },
    source: "website",
    blocksTime: true,
    history: [],
  }),
  item({
    id: "jor-today-2",
    kind: "booking",
    ref: { table: "talent_bookings", id: "jor-today-2" },
    client: { name: "Ana López", initials: "AL" },
    title: "Volume lashes",
    lines: [{ label: "Volume lashes", cents: 180000 }],
    startsAt: "2026-09-23T12:00:00-05:00",
    endsAt: "2026-09-23T14:15:00-05:00",
    allDay: false,
    tz: JOR_TZ,
    where: { mode: "studio", label: "Studio" },
    bufferAfterMin: 15,
    booking: "confirmed",
    payment: "partial",
    money: {
      totalCents: 180000,
      paidCents: 85000,
      depositCents: 85000,
      dueCents: 95000,
      currency: "MXN",
    },
    source: "manual",
    blocksTime: true,
    history: [],
  }),
  item({
    id: "jor-today-3",
    kind: "booking",
    ref: { table: "talent_bookings", id: "jor-today-3" },
    client: { name: "Lucía Méndez", initials: "LM" },
    title: "Brows",
    lines: [{ label: "Brows", cents: 62000 }],
    startsAt: "2026-09-23T16:00:00-05:00",
    endsAt: "2026-09-23T17:30:00-05:00",
    allDay: false,
    tz: JOR_TZ,
    where: { mode: "studio", label: "Studio" },
    bufferAfterMin: 15,
    booking: "confirmed",
    payment: "overdue",
    money: { totalCents: 62000, paidCents: 0, dueCents: 62000, currency: "MXN" },
    source: "manual",
    blocksTime: true,
    history: [],
  }),
  item({
    id: "jor-hold-sofia",
    kind: "hold",
    ref: { table: "talent_holds", id: "jor-hold-sofia" },
    client: { name: "Sofía Vega", initials: "SV" },
    title: "Full set",
    lines: [{ label: "Deposit", cents: 50000 }],
    startsAt: "2026-09-24T11:00:00-05:00",
    endsAt: "2026-09-24T13:00:00-05:00",
    allDay: false,
    tz: JOR_TZ,
    where: { mode: "studio", label: "Studio" },
    bufferAfterMin: 15,
    booking: "hold",
    payment: "awaiting",
    money: { totalCents: 200000, paidCents: 0, depositCents: 50000, dueCents: 50000, currency: "MXN" },
    source: "website",
    holdUntil: "2026-09-23T11:40:00-05:00",
    blocksTime: true,
    history: [],
  }),
  item({
    id: "jor-req-1",
    kind: "request",
    ref: { table: "inquiries", id: "jor-req-1" },
    client: { name: "María Pérez", initials: "MP" },
    title: "Gel refill",
    lines: [],
    startsAt: "2026-09-25T15:00:00-05:00",
    endsAt: "2026-09-25T16:00:00-05:00",
    allDay: false,
    tz: JOR_TZ,
    where: { mode: "studio", label: "Studio" },
    bufferAfterMin: 15,
    booking: "requested",
    payment: "none",
    money: { totalCents: 0, paidCents: 0, dueCents: 0, currency: "MXN" },
    source: "website",
    blocksTime: false,
    history: [],
  }),
  item({
    id: "jor-week-c1",
    kind: "booking",
    ref: { table: "talent_bookings", id: "jor-week-c1" },
    client: { name: "Elena Soto", initials: "ES" },
    title: "Classic lashes",
    lines: [{ label: "Classic lashes", cents: 140000 }],
    startsAt: "2026-09-22T11:00:00-05:00",
    endsAt: "2026-09-22T12:30:00-05:00",
    allDay: false,
    tz: JOR_TZ,
    where: { mode: "studio", label: "Studio" },
    bufferAfterMin: 15,
    booking: "completed",
    payment: "paid",
    money: { totalCents: 140000, paidCents: 140000, dueCents: 0, currency: "MXN" },
    source: "tulala",
    blocksTime: true,
    history: [],
  }),
  item({
    id: "jor-week-c2",
    kind: "booking",
    ref: { table: "talent_bookings", id: "jor-week-c2" },
    client: { name: "Paula Díaz", initials: "PD" },
    title: "Gel",
    lines: [{ label: "Gel", cents: 90000 }],
    startsAt: "2026-09-26T10:00:00-05:00",
    endsAt: "2026-09-26T11:00:00-05:00",
    allDay: false,
    tz: JOR_TZ,
    where: { mode: "studio", label: "Studio" },
    bufferAfterMin: 15,
    booking: "confirmed",
    payment: "due",
    money: { totalCents: 90000, paidCents: 0, dueCents: 90000, currency: "MXN" },
    source: "manual",
    blocksTime: true,
    history: [],
  }),
  item({
    id: "jor-done-1",
    kind: "booking",
    ref: { table: "talent_bookings", id: "jor-done-1" },
    client: { name: "Rita Nava", initials: "RN" },
    title: "Brows",
    lines: [{ label: "Brows", cents: 55000 }],
    startsAt: "2026-09-21T14:00:00-05:00",
    endsAt: "2026-09-21T15:00:00-05:00",
    allDay: false,
    tz: JOR_TZ,
    where: { mode: "studio", label: "Studio" },
    bufferAfterMin: 15,
    booking: "completed",
    payment: "paid",
    money: { totalCents: 55000, paidCents: 55000, dueCents: 0, currency: "MXN" },
    source: "website",
    blocksTime: true,
    history: [],
  }),
  item({
    id: "jor-agency-1",
    kind: "booking",
    ref: { table: "agency_bookings", id: "jor-agency-1" },
    client: { name: "Vogue shoot", initials: "VG" },
    title: "Agency job",
    lines: [],
    startsAt: "2026-09-27T09:00:00-05:00",
    endsAt: "2026-09-27T13:00:00-05:00",
    allDay: false,
    tz: JOR_TZ,
    where: { mode: "away", label: "Studio Roca" },
    bufferAfterMin: 0,
    booking: "confirmed",
    payment: "agency",
    money: { totalCents: 0, paidCents: 0, dueCents: 0, currency: "MXN" },
    source: "agency",
    managedBy: { agencyId: "ag1", name: "Impronta" },
    blocksTime: true,
    history: [],
  }),
];
