/** EN + ES copy for the Talent Template Factory (no em dashes). */
import type { FactoryStatus } from "./factory-model";

export type FactoryLang = "en" | "es";

export const FACTORY_COPY = {
  en: {
    tabName: "Talent Template Factory",
    tabSubtitle: "Talent sites (Maison v2, Folio, Gridline)",
    catalogName: "Catalog",
    catalogSubtitle: "Agency and business sites",
    title: "Talent Template Factory",
    lead: "The one place to run the talent theme factory: sync, rebuild demos, compare with the mockup. Talent designs only. Agency starters live under Catalog.",
    loading: "Loading...",
    sync: "Sync catalog",
    syncing: "Syncing...",
    syncLead: "Writes draft releases for changed designs. Never flips the live catalog.",
    syncResult: "Sync result",
    status: { up_to_date: "Up to date", code_ahead: "Code is ahead (sync needed)", not_synced: "Not synced yet" } satisfies Record<FactoryStatus, string>,
    catalogVersion: "Catalog",
    codeVersion: "Code",
    demos: "Demos",
    gallery: "In gallery",
    yes: "Yes",
    no: "No",
    openReleases: "Open releases",
    noRelease: "No release yet",
    previewCode: "Preview from code",
    mockup: "Mockup",
    parityMap: "Parity map",
    present: "present",
    missing: "missing",
    openBuilder: "Edit design in builder",
    builderNote: (code: string | null) =>
      `Opens the Talent design editor on this design draft${code ? `, previewing ${code}` : ""}. Edits stay in the draft until a new version is published; they never touch a talent site.`,
    noReference: "no reference demo",
    lastComparison: "Last mockup comparison",
    noRun: "No run found on this machine yet.",
    productionHint: "Mockup comparison runs locally. Run this on your machine:",
    openDeltas: "Open deltas",
    layers: "By layer",
    report: "Report",
    copy: "Copy command",
    copied: "Copied",
    howTitle: "How to add a new theme",
    steps: {
      mockup: "Put the mockup in design-references/<slug>.",
      parityMap: "Add parity-map.json next to it.",
      collection: "Write theme-catalog/collection/<slug>.ts (the design payload).",
      register: "Register it in COLLECTION_DESIGNS.",
      demos: "Add its demos to the demos registry and fixtures.",
      sync: "Sync catalog.",
      rebuild: "Rebuild demos (preview first, then apply).",
      parity: "Run the mockup parity check and clear the deltas.",
      ship: "Publish to demos, then Open to talents, then add to the gallery.",
    },
    language: "Español",
    error: "Something went wrong.",
  },
  es: {
    tabName: "Fábrica de plantillas de talento",
    tabSubtitle: "Sitios de talento (Maison v2, Folio, Gridline)",
    catalogName: "Catálogo",
    catalogSubtitle: "Sitios de agencia y negocio",
    title: "Fábrica de plantillas de talento",
    lead: "El único lugar para operar la fábrica de temas de talento: sincronizar, reconstruir demos y comparar con la maqueta. Solo diseños de talento. Las plantillas de agencia están en Catálogo.",
    loading: "Cargando...",
    sync: "Sincronizar catálogo",
    syncing: "Sincronizando...",
    syncLead: "Escribe lanzamientos en borrador para los diseños que cambiaron. Nunca cambia el catálogo en vivo.",
    syncResult: "Resultado de la sincronización",
    status: { up_to_date: "Al día", code_ahead: "El código va adelante (falta sincronizar)", not_synced: "Aún sin sincronizar" } satisfies Record<FactoryStatus, string>,
    catalogVersion: "Catálogo",
    codeVersion: "Código",
    demos: "Demos",
    gallery: "En la galería",
    yes: "Sí",
    no: "No",
    openReleases: "Abrir lanzamientos",
    noRelease: "Aún sin lanzamiento",
    previewCode: "Vista previa desde el código",
    mockup: "Maqueta",
    parityMap: "Mapa de paridad",
    present: "presente",
    missing: "falta",
    openBuilder: "Editar diseño en el editor",
    builderNote: (code: string | null) =>
      `Abre el editor de diseños de talento sobre el borrador de este diseño${code ? `, con vista previa de ${code}` : ""}. Los cambios quedan en el borrador hasta publicar una nueva versión; nunca tocan el sitio de un talento.`,
    noReference: "sin demo de referencia",
    lastComparison: "Última comparación con la maqueta",
    noRun: "Aún no hay una ejecución en esta máquina.",
    productionHint: "La comparación con la maqueta se ejecuta en local. Ejecuta esto en tu máquina:",
    openDeltas: "Diferencias abiertas",
    layers: "Por capa",
    report: "Informe",
    copy: "Copiar comando",
    copied: "Copiado",
    howTitle: "Cómo agregar un tema nuevo",
    steps: {
      mockup: "Pon la maqueta en design-references/<slug>.",
      parityMap: "Agrega parity-map.json al lado.",
      collection: "Escribe theme-catalog/collection/<slug>.ts (el contenido del diseño).",
      register: "Regístralo en COLLECTION_DESIGNS.",
      demos: "Agrega sus demos al registro de demos y a los fixtures.",
      sync: "Sincroniza el catálogo.",
      rebuild: "Reconstruye las demos (primero la vista previa, luego aplicar).",
      parity: "Ejecuta la comparación de paridad y limpia las diferencias.",
      ship: "Publica en demos, luego abre a talentos, luego agrega a la galería.",
    },
    language: "English",
    error: "Algo salió mal.",
  },
} as const;
