/** EN + ES copy for the Talent Template Factory (no em dashes). */
import type { FactoryStatus } from "./factory-model";

export type FactoryLang = "en" | "es";

export const FACTORY_COPY = {
  en: {
    tabName: "Talent Template Factory",
    tabSubtitle: "Talent sites (Maison v2, Folio, Gridline)",
    catalogName: "Catalog",
    catalogSubtitle: "Agency and business sites",
    title: "Talent Template Factory",
    lead: "The one place to run the talent theme factory: sync, rebuild demos, compare with the mockup. Talent designs only. Agency starters live under Catalog.",
    loading: "Loading...",
    sync: "Sync catalog",
    syncing: "Syncing...",
    syncLead: "Writes draft releases for changed designs. Never flips the live catalog.",
    syncResult: "Sync summary",
    syncCounts: (c: number, u: number, n: number) =>
      `${c} created, ${u} updated, ${n} unchanged. Catalog default was not flipped.`,
    syncQuiet: "Nothing to sync. Catalog default was not flipped.",
    syncHeldBack: "Held back (catalog stays put until Make default)",
    syncSkippedAuthored: "Skipped authored designs",
    syncAuthoredPending: "Editor ahead of code (pull before syncing these)",
    syncAuthoredConflict: "Editor and code both moved (resolve before syncing)",
    status: { up_to_date: "Up to date", code_ahead: "Code is ahead (sync needed)", not_synced: "Not synced yet", authored_pending: "Editor version not in code yet (sync skips it)", authored_hidden: "Authored, hidden" } satisfies Record<FactoryStatus, string>,
    catalogVersion: "Catalog default",
    codeVersion: "Code",
    releasedVersion: "Open to talents",
    versionLagHint: "Catalog default can lag until Make default. Talents see the open-to-talents version.",
    releasedInCatalog: (v: number | null) => (v === null ? "Released in catalog" : `Released in catalog (v${v})`),
    pendingHint: "The editor version is ahead of the code. Pull it into the repo with:",
    hiddenDrafts: (n: number) => `Hidden drafts (${n})`,
    demos: "Demos",
    gallery: "In gallery",
    yes: "Yes",
    no: "No",
    openReleases: "Open releases",
    noRelease: "No release yet",
    previewCode: "Preview from code",
    mockup: "Mockup",
    parityMap: "Parity map",
    present: "present",
    missing: "missing",
    openBuilder: "Edit design in builder",
    editDesign: "Edit design",
    builderNote: (code: string | null) =>
      `Opens the Talent design editor on this design draft${code ? `, previewing ${code}` : ""}. Edits stay in the draft until a new version is published; they never touch a talent site.`,
    noReference: "no reference demo",
    lastComparison: "Last mockup comparison",
    noRun: "No run found on this machine yet.",
    productionHint: "Mockup comparison runs locally. Run this on your machine:",
    openDeltas: "Open deltas",
    layers: "By layer",
    report: "Report",
    copy: "Copy command",
    copied: "Copied",
    howTitle: "How to add a new theme",
    steps: {
      edit: "Edit design in builder (or start from the closest design and Save as new design).",
      work: "Pick a demo and a look, then edit sections, text, sizes, spacing and fonts.",
      publish: "Publish and update demos.",
      check: "Check the release page and the demos.",
      parity: "If there is a mockup, run the mockup comparison (npm run qa:parity-loop or npm run qa:mockup-parity).",
      open: "Open to talents when it is ready.",
      commit: "Commit the overlay with: npm run theme:pull-authored -- --design <slug>",
    },
    fullGuide: "Full guide: docs/factory/how-to-make-a-new-theme.md",
    language: "Español",
    error: "Something went wrong.",
  },
  es: {
    tabName: "Fábrica de plantillas de talento",
    tabSubtitle: "Sitios de talento (Maison v2, Folio, Gridline)",
    catalogName: "Catálogo",
    catalogSubtitle: "Sitios de agencia y negocio",
    title: "Fábrica de plantillas de talento",
    lead: "El único lugar para operar la fábrica de temas de talento: sincronizar, reconstruir demos y comparar con la maqueta. Solo diseños de talento. Las plantillas de agencia están en Catálogo.",
    loading: "Cargando...",
    sync: "Sincronizar catálogo",
    syncing: "Sincronizando...",
    syncLead: "Escribe lanzamientos en borrador para los diseños que cambiaron. Nunca cambia el catálogo en vivo.",
    syncResult: "Resumen de la sincronización",
    syncCounts: (c: number, u: number, n: number) =>
      `${c} creados, ${u} actualizados, ${n} sin cambios. El catálogo predeterminado no se movió.`,
    syncQuiet: "Nada que sincronizar. El catálogo predeterminado no se movió.",
    syncHeldBack: "Retenidos (el catálogo sigue igual hasta Hacer predeterminado)",
    syncSkippedAuthored: "Diseños creados aquí omitidos",
    syncAuthoredPending: "El editor va por delante del código (tráelos antes de sincronizar)",
    syncAuthoredConflict: "El editor y el código se movieron (resuelve antes de sincronizar)",
    status: { up_to_date: "Al día", code_ahead: "El código va adelante (falta sincronizar)", not_synced: "Aún sin sincronizar", authored_pending: "Versión del editor aún no está en el código (la sincronización la omite)", authored_hidden: "Creado aquí, oculto" } satisfies Record<FactoryStatus, string>,
    catalogVersion: "Catálogo predeterminado",
    codeVersion: "Código",
    releasedVersion: "Abierto a talentos",
    versionLagHint: "El catálogo predeterminado puede retrasarse hasta Hacer predeterminado. Los talentos ven la versión abierta a talentos.",
    releasedInCatalog: (v: number | null) => (v === null ? "Publicada en el catálogo" : `Publicada en el catálogo (v${v})`),
    pendingHint: "La versión del editor va por delante del código. Tráela al repositorio con:",
    hiddenDrafts: (n: number) => `Borradores ocultos (${n})`,
    demos: "Demos",
    gallery: "En la galería",
    yes: "Sí",
    no: "No",
    openReleases: "Abrir lanzamientos",
    noRelease: "Aún sin lanzamiento",
    previewCode: "Vista previa desde el código",
    mockup: "Maqueta",
    parityMap: "Mapa de paridad",
    present: "presente",
    missing: "falta",
    openBuilder: "Editar diseño en el editor",
    editDesign: "Editar diseño",
    builderNote: (code: string | null) =>
      `Abre el editor de diseños de talento sobre el borrador de este diseño${code ? `, con vista previa de ${code}` : ""}. Los cambios quedan en el borrador hasta publicar una nueva versión; nunca tocan el sitio de un talento.`,
    noReference: "sin demo de referencia",
    lastComparison: "Última comparación con la maqueta",
    noRun: "Aún no hay una ejecución en esta máquina.",
    productionHint: "La comparación con la maqueta se ejecuta en local. Ejecuta esto en tu máquina:",
    openDeltas: "Diferencias abiertas",
    layers: "Por capa",
    report: "Informe",
    copy: "Copiar comando",
    copied: "Copiado",
    howTitle: "Cómo agregar un tema nuevo",
    steps: {
      edit: "Edita el diseño en el editor (o parte del diseño más cercano y usa Guardar como diseño nuevo).",
      work: "Elige una demo y un estilo, luego edita secciones, textos, tamaños, espaciado y fuentes.",
      publish: "Publica y actualiza las demos.",
      check: "Revisa la página de versión y las demos.",
      parity: "Si hay maqueta, ejecuta la comparación con la maqueta (npm run qa:parity-loop o npm run qa:mockup-parity).",
      open: "Abre a talentos cuando esté listo.",
      commit: "Confirma el overlay con: npm run theme:pull-authored -- --design <slug>",
    },
    fullGuide: "Guía completa: docs/factory/how-to-make-a-new-theme.md",
    language: "English",
    error: "Algo salió mal.",
  },
} as const;
