import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

import { createServiceRoleClient } from "@/lib/supabase/admin";
import { logServerError } from "@/lib/server/safe-error";

export {
  FEATURE_REQUEST_STATUSES,
  type FeatureRequestStatus,
  type FeatureRequestRow,
  type HqFeatureRequestRow,
} from "./feature-request-types";

import {
  FEATURE_REQUEST_STATUSES as STATUSES,
  type FeatureRequestRow as Row,
  type FeatureRequestStatus as Status,
  type HqFeatureRequestRow as HqRow,
} from "./feature-request-types";

/** Untyped table access: database.types.ts is regenerated by the integrator. */
export function featureFrom(client: SupabaseClient, table: string) {
  return (client as unknown as {
    from: (t: string) => ReturnType<SupabaseClient["from"]>;
  }).from(table);
}

function str(row: Record<string, unknown>, key: string): string | null {
  const v = row[key];
  return typeof v === "string" ? v : null;
}

export function mapFeatureRequestRow(raw: unknown): Row | null {
  if (!raw || typeof raw !== "object") return null;
  const row = raw as Record<string, unknown>;
  const id = str(row, "id");
  const requester = str(row, "requester_user_id");
  if (!id || !requester) return null;
  const surface = str(row, "surface");
  const status = str(row, "status");
  return {
    id,
    requestNumber: typeof row.request_number === "number" ? row.request_number : 0,
    tenantId: str(row, "tenant_id"),
    surface:
      surface === "talent" || surface === "client" ? surface : "workspace",
    requesterUserId: requester,
    title: str(row, "title") ?? "",
    body: str(row, "body") ?? "",
    area: str(row, "area"),
    contactPhone: str(row, "contact_phone"),
    contactEmail: str(row, "contact_email"),
    status: (STATUSES as readonly string[]).includes(status ?? "")
      ? (status as Status)
      : "new",
    priority: str(row, "priority") ?? "normal",
    voteCount: typeof row.vote_count === "number" ? row.vote_count : 0,
    ownerNote: str(row, "owner_note"),
    shippedRef: str(row, "shipped_ref"),
    createdAt: str(row, "created_at") ?? new Date().toISOString(),
    updatedAt: str(row, "updated_at") ?? new Date().toISOString(),
  };
}

/** HQ list: every request with requester + workspace context for follow-up. */
export async function loadHqFeatureRequests(): Promise<HqRow[]> {
  try {
    const admin = createServiceRoleClient();
    if (!admin) return [];
    const { data, error } = await featureFrom(admin, "support_feature_requests")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(300);
    if (error) {
      logServerError("support.featureRequests.loadHq", error);
      return [];
    }
    const rows = ((data ?? []) as unknown[])
      .map(mapFeatureRequestRow)
      .filter((r): r is Row => Boolean(r));
    if (rows.length === 0) return [];

    const tenantIds = [...new Set(rows.map((r) => r.tenantId).filter(Boolean))] as string[];
    const userIds = [...new Set(rows.map((r) => r.requesterUserId))];
    const [agencies, profiles] = await Promise.all([
      tenantIds.length
        ? admin.from("agencies").select("id, display_name, slug").in("id", tenantIds)
        : Promise.resolve({ data: [] as unknown[] }),
      userIds.length
        ? admin.from("profiles").select("id, display_name").in("id", userIds)
        : Promise.resolve({ data: [] as unknown[] }),
    ]);
    const tenantById = new Map<string, { name: string | null; slug: string | null }>();
    for (const a of (agencies.data ?? []) as Array<Record<string, unknown>>) {
      const id = str(a, "id");
      if (id) tenantById.set(id, { name: str(a, "display_name"), slug: str(a, "slug") });
    }
    const nameById = new Map<string, string | null>();
    for (const p of (profiles.data ?? []) as Array<Record<string, unknown>>) {
      const id = str(p, "id");
      if (id) nameById.set(id, str(p, "display_name"));
    }

    return rows.map((request) => {
      const tenant = request.tenantId ? tenantById.get(request.tenantId) : undefined;
      return {
        request,
        tenantName: tenant?.name ?? null,
        tenantSlug: tenant?.slug ?? null,
        requesterName: nameById.get(request.requesterUserId) ?? null,
      };
    });
  } catch (err) {
    logServerError("support.featureRequests.loadHq", err);
    return [];
  }
}

/** Panel list: what this user has asked for, newest first. */
export async function loadMyFeatureRequests(userId: string): Promise<Row[]> {
  try {
    const admin = createServiceRoleClient();
    if (!admin) return [];
    const { data, error } = await featureFrom(admin, "support_feature_requests")
      .select("*")
      .eq("requester_user_id", userId)
      .order("created_at", { ascending: false })
      .limit(20);
    if (error) {
      logServerError("support.featureRequests.loadMine", error);
      return [];
    }
    return ((data ?? []) as unknown[])
      .map(mapFeatureRequestRow)
      .filter((r): r is Row => Boolean(r));
  } catch (err) {
    logServerError("support.featureRequests.loadMine", err);
    return [];
  }
}
