/**
 * Layout tab — THE STACK MODEL, as pure functions.
 *
 * The engine already only speaks in layouts that work: a container lays its
 * children out as an ordered stack, a row, or a grid, with a token gap, and a
 * drag reorders through the drop resolver. There is no pixel-coordinate base
 * model to fall out of. What the inspector was missing is that it did not SAY
 * so: direction, gap and alignment sat in a two-by-two chip grid beside
 * "Display mode" and "HTML tag", with wrap and justification not present at
 * all and only reachable from a collapsed spec-named block in another tab.
 *
 * This module is the part of the stack-first pass that can be WRONG in a way a
 * screenshot cannot show, so it lives apart from the component and is unit
 * tested: what the panel says the current layout IS, and how the two escapes
 * (a grid's minimum column width, an off-scale gap) read back.
 *
 * ── THE HARD INVARIANT, same as the field kit's ────────────────────────────
 * Nothing here returns a value to store from a READ. `describeStack` and
 * `parseMinColumnWidth` are pure reads over whatever the tree already holds;
 * a hand-authored `grid-template-columns` comes back as `null` (meaning "this
 * control has no opinion about it") rather than being re-expressed as the
 * nearest thing the control can draw. Only `minColumnWidthTemplate` and
 * `gapPatchValue` produce a value, and both run from a press.
 *
 * Pure data + pure functions. No React.
 */

import type { LengthUnit } from "../../kit/number-unit";
import type { FieldValue } from "../field-kit/preset-state";

/** The kinds whose Layout tab leads with the stack group. */
export const STACK_LAYOUT_KINDS: ReadonlySet<string> = new Set([
  "container",
  "split",
  "card",
  "cta_group",
  "carousel",
  "masonry",
]);

/**
 * Only the built-in tiers have a breakpoint lane for arbitrary style keys.
 * A custom tier gets container-prop lanes (`layout`/`gap`/`columns`/`align`)
 * generated by `custom-breakpoint-css.ts` and nothing else, so a wrap or a
 * justification authored there would save, read back, and render nothing.
 */
export const STYLE_BACKED_TIERS: ReadonlySet<string> = new Set([
  "desktop",
  "tablet",
  "mobile",
]);

export function tierSupportsStyleOverrides(device: string): boolean {
  return STYLE_BACKED_TIERS.has(device);
}

// ── Gap ─────────────────────────────────────────────────────────────────────

/**
 * The container/card/split gap prop as a field-kit value.
 *
 * `props.gap` is an `s`/`m`/`l` enum, so it is either on the scale or absent.
 * Absent is passed in as the renderer's own default by the caller rather than
 * shown as "unset": the CSS says `var(--bn-gap,1.25rem)`, which IS M, and a
 * readout that said "Auto" over a box that is visibly gapped by 20px would be
 * the panel telling a small lie. Reading it as M writes nothing.
 */
export function gapFieldValue(gap: string | undefined): FieldValue {
  if (!gap) return { kind: "unset" };
  return { kind: "preset", id: gap };
}

/**
 * What a stepper press stores. The stepper walks GAP_PRESETS, which carries no
 * "unset" entry, so a press below the first step returns `{kind:"unset"}` and
 * that becomes `undefined` — the field cleared back to the renderer default.
 * A `custom` value cannot arise from this scale, and is refused rather than
 * coerced into an enum the schema does not accept.
 */
export function gapPatchValue(next: FieldValue): string | undefined | false {
  if (next.kind === "unset") return undefined;
  if (next.kind === "preset") return next.id;
  return false;
}

// ── Grid: minimum column width ──────────────────────────────────────────────

/**
 * The template the "minimum column width" control writes.
 *
 * `repeat(auto-fit, minmax(<min>, 1fr))` is the whole primitive: the grid fits
 * as many columns as clear the minimum and reflows to fewer when it cannot,
 * instead of squashing a fixed count into a phone. The renderer already honors
 * `style.gridTemplateColumns` at base, tablet and mobile (an `!important` rule
 * over the fixed `repeat(var(--bn-columns),…)` default), so this is inspector
 * UI riding a value the schema already accepts.
 */
export function minColumnWidthTemplate(value: number, unit: LengthUnit): string {
  return `repeat(auto-fit, minmax(${value}${unit}, 1fr))`;
}

export interface MinColumnWidth {
  readonly value: number;
  readonly unit: LengthUnit;
}

const AUTO_FIT_RE =
  /^repeat\(\s*auto-(?:fit|fill)\s*,\s*minmax\(\s*(-?\d+(?:\.\d+)?)(px|rem|em|%|vw|vh)\s*,\s*1fr\s*\)\s*\)$/;

const KNOWN_UNITS: ReadonlySet<string> = new Set([
  "px",
  "rem",
  "em",
  "%",
  "vw",
  "vh",
]);

/**
 * Read a stored template back into the control, or `null` when the control has
 * no opinion about it.
 *
 * `null` covers both "nothing is set" and "somebody hand-authored
 * `2fr 1fr`" — and the second case is the one that matters. Returning a
 * guessed number there would light a control over a value it does not
 * describe, and the next press would silently replace a template the operator
 * wrote. The panel shows the raw template instead and says so.
 */
export function parseMinColumnWidth(
  template: string | undefined | null,
): MinColumnWidth | null {
  if (!template) return null;
  const match = AUTO_FIT_RE.exec(template.trim());
  if (!match) return null;
  const value = Number.parseFloat(match[1]!);
  if (!Number.isFinite(value) || value <= 0) return null;
  const unit = match[2]!;
  if (!KNOWN_UNITS.has(unit)) return null;
  return { value, unit: unit as LengthUnit };
}

/** True when a stored template is something this control did not author. */
export function isForeignGridTemplate(
  template: string | undefined | null,
): boolean {
  return Boolean(template && template.trim()) && parseMinColumnWidth(template) === null;
}

// ── "What is this block doing right now" ────────────────────────────────────

/** One phrase of the summary: a catalog key plus the values to substitute. */
export interface StackClause {
  readonly key: string;
  readonly vars?: Readonly<Record<string, string>>;
}

/** Fill a clause's `{token}` slots. Caller-side, the catalog's own convention. */
export function fillClause(text: string, vars: StackClause["vars"]): string {
  if (!vars) return text;
  let out = text;
  for (const [token, value] of Object.entries(vars)) out = out.split(token).join(value);
  return out;
}

export interface StackShape {
  /** `stack` / `row` / `grid`, already resolved for the active tier. */
  readonly direction: string;
  /** `style.flexWrap` for the active tier, or undefined. */
  readonly wrap?: string;
  /** The container `align` prop (cross axis), or undefined. */
  readonly align?: string;
  /** `style.justifyContent` for the active tier, or undefined. */
  readonly justify?: string;
  /** Grid column count, when the direction is a grid. */
  readonly columns?: number;
  /** A grid's minimum column width, when one is set. */
  readonly minColumnWidth?: MinColumnWidth | null;
  /** True when the container is rendering as a horizontal slider. */
  readonly slider?: boolean;
}

const DIRECTION_PHRASE: Record<string, string> = {
  stack: "Stacked top to bottom",
  row: "In a row, left to right",
  grid: "In a grid",
};

const ALIGN_PHRASE: Record<string, string> = {
  start: "aligned to the start",
  center: "aligned to the center",
  end: "aligned to the end",
  stretch: "stretched to fill",
};

const JUSTIFY_PHRASE: Record<string, string> = {
  "flex-start": "packed to the start",
  start: "packed to the start",
  center: "centered along the flow",
  "flex-end": "packed to the end",
  end: "packed to the end",
  "space-between": "spread edge to edge",
  "space-around": "spaced around",
  "space-evenly": "spaced evenly",
};

/**
 * The one-line answer to "how does this block arrange its children", built out
 * of the values that are actually set. Nothing is invented: a clause appears
 * only when the value behind it exists, so the line grows as the operator
 * makes decisions instead of asserting defaults they never chose.
 *
 * Returned as clauses rather than one string, and as a translation KEY plus
 * its variables rather than as finished text: a clause with a number in it
 * ("3 columns") has to reach the catalog as a template, or the Spanish panel
 * falls back to English on exactly the clauses carrying the most information.
 */
export function describeStack(shape: StackShape): StackClause[] {
  const out: StackClause[] = [];

  if (shape.slider) {
    out.push({ key: "Side to side, one scrolling row" });
  } else {
    out.push({ key: DIRECTION_PHRASE[shape.direction] ?? DIRECTION_PHRASE.stack! });
  }

  if (shape.direction === "grid" && !shape.slider) {
    const min = shape.minColumnWidth;
    if (min) {
      out.push({
        key: "reflowing at {size} per column",
        vars: { "{size}": `${min.value}${min.unit}` },
      });
    } else if (typeof shape.columns === "number") {
      out.push(
        shape.columns === 1
          ? { key: "1 column" }
          : { key: "{count} columns", vars: { "{count}": String(shape.columns) } },
      );
    }
  }

  if (shape.direction === "row" && !shape.slider) {
    // The renderer's row rule is `flex-wrap:wrap`, so wrapping is the default
    // and only its ABSENCE is worth a clause.
    out.push({
      key: shape.wrap === "nowrap" ? "on one line, no wrapping" : "wrapping onto new lines",
    });
  }

  if (shape.justify && JUSTIFY_PHRASE[shape.justify]) {
    out.push({ key: JUSTIFY_PHRASE[shape.justify]! });
  }

  if (shape.align && ALIGN_PHRASE[shape.align]) {
    out.push({ key: ALIGN_PHRASE[shape.align]! });
  }

  return out;
}
