import type { AddGalleryItem } from "./types";
import { el, roadmap } from "./registry-helpers";

export const ADD_GALLERY_ELEMENT_ITEMS: ReadonlyArray<AddGalleryItem> = [
  // ── Elements / Text ─────────────────────────────────────────────────────
  el({
    id: "el-text",
    label: "Text",
    description: "Heading or paragraph — switch style in the bottom toolbar.",
    category: "text",
    icon: "text",
    insertMethod: "nativeNode",
    nativeKind: "paragraph",
    searchTerms: ["title", "subtitle", "intro", "heading", "paragraph", "body"],
  }),
  el({
    id: "el-title",
    label: "Title",
    description: "Use Text + toolbar H1 instead.",
    category: "text",
    icon: "title",
    insertMethod: "nativeNode",
    nativeKind: "heading",
    nativeVariant: "title",
    availability: "advanced-hidden",
    searchTerms: ["heading", "h1"],
  }),
  el({
    id: "el-subtitle",
    label: "Subtitle",
    description: "Use Text + toolbar H2 instead.",
    category: "text",
    icon: "subtitle",
    insertMethod: "nativeNode",
    nativeKind: "heading",
    nativeVariant: "subtitle",
    availability: "advanced-hidden",
    searchTerms: ["heading", "h2"],
  }),
  el({
    id: "el-intro",
    label: "Intro Text",
    description: "Use Text + toolbar Paragraph instead.",
    category: "text",
    icon: "intro",
    insertMethod: "nativeNode",
    nativeKind: "paragraph",
    nativeVariant: "intro",
    availability: "advanced-hidden",
  }),
  el({
    id: "el-paragraph",
    label: "Paragraph",
    description: "Use unified Text element instead.",
    category: "text",
    icon: "paragraph",
    insertMethod: "nativeNode",
    nativeKind: "paragraph",
    availability: "advanced-hidden",
  }),
  el({
    id: "el-rich-text",
    label: "Rich Text",
    description: "Formatted multi-paragraph content.",
    category: "text",
    icon: "rich-text",
    insertMethod: "nativeNode",
    nativeKind: "rich_text",
  }),
  el({
    id: "el-caption",
    label: "Caption",
    description: "Small supporting text under media.",
    category: "text",
    icon: "caption",
    insertMethod: "nativeNode",
    nativeKind: "paragraph",
    nativeVariant: "caption",
  }),
  el({
    id: "el-badge",
    label: "Badge",
    description: "Small label or status tag.",
    category: "text",
    icon: "badge",
    insertMethod: "nativeNode",
    nativeKind: "icon",
    nativeVariant: "badge",
  }),
  el({
    id: "el-quote",
    label: "Quote",
    description: "Pull quote or blockquote.",
    category: "text",
    icon: "quote",
    insertMethod: "nativeNode",
    nativeKind: "paragraph",
    nativeVariant: "quote",
  }),

  // ── Elements / Buttons ──────────────────────────────────────────────────
  el({
    id: "el-button",
    label: "Button",
    description: "Primary call-to-action button.",
    category: "buttons",
    icon: "button",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "button",
  }),
  el({
    id: "el-button-group",
    label: "Button Group",
    description: "Grouped primary and secondary actions.",
    category: "buttons",
    icon: "button-group",
    insertMethod: "nativeNode",
    nativeKind: "cta_group",
    nativeVariant: "button-group",
  }),
  el({
    id: "el-text-link",
    label: "Text Link",
    description: "Inline text link styled as a button.",
    category: "buttons",
    icon: "text-link",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "text-link",
  }),
  el({
    id: "el-icon-button",
    label: "Icon Button",
    description: "Compact icon-forward action.",
    category: "buttons",
    icon: "icon-button",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "icon-button",
  }),
  roadmap({
    id: "el-inquiry-button",
    label: "Inquiry Button",
    description: "Use Connected → Inquiry Button or Sections → CTA Banner instead.",
    category: "buttons",
    icon: "inquiry",
  }),
  el({
    id: "el-booking-button",
    label: "Booking Button",
    description: "Embedded booking widget CTA.",
    category: "buttons",
    icon: "booking",
    insertMethod: "sectionEmbed",
    sectionEmbedKey: "booking_widget",
    sourceType: "section-embed",
  }),
  el({
    id: "el-download-link",
    label: "Download Link",
    description: "Button that links to a downloadable file.",
    category: "buttons",
    icon: "download",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "download-link",
  }),

  // ── Elements / Media ────────────────────────────────────────────────────
  el({
    id: "el-image",
    label: "Image",
    description: "Single responsive image.",
    category: "media",
    icon: "image",
    insertMethod: "nativeNode",
    nativeKind: "image",
  }),
  el({
    id: "el-cover-image",
    label: "Cover Image",
    description: "Wide hero-style image.",
    category: "media",
    icon: "cover",
    insertMethod: "nativeNode",
    nativeKind: "image",
    nativeVariant: "cover-image",
  }),
  el({
    id: "el-logo",
    label: "Logo",
    description: "Brand mark image.",
    category: "media",
    icon: "logo",
    insertMethod: "nativeNode",
    nativeKind: "image",
    nativeVariant: "logo",
  }),
  el({
    id: "el-icon",
    label: "Icon",
    description: "Decorative or functional icon.",
    category: "media",
    icon: "icon",
    insertMethod: "nativeNode",
    nativeKind: "icon",
  }),
  el({
    id: "el-video",
    label: "Video",
    description: "Hosted or uploaded video.",
    category: "media",
    icon: "video",
    insertMethod: "nativeNode",
    nativeKind: "video",
  }),
  roadmap({
    id: "el-gallery",
    label: "Gallery",
    description: "Use Sections → Gallery Grid or Gallery Strip instead.",
    category: "media",
    icon: "gallery",
  }),
  el({
    id: "el-image-grid",
    label: "Image Grid",
    description: "Responsive masonry image grid.",
    category: "media",
    icon: "image-grid",
    insertMethod: "nativeNode",
    nativeKind: "masonry",
    nativeVariant: "image-grid",
  }),
  el({
    id: "el-carousel",
    label: "Carousel",
    description: "Swipeable media carousel.",
    category: "media",
    icon: "carousel",
    insertMethod: "nativeNode",
    nativeKind: "carousel",
  }),

  // ── Elements / Layout ───────────────────────────────────────────────────
  el({
    id: "el-section",
    label: "Section",
    description: "Top-level page section row.",
    category: "layout",
    icon: "section",
    insertMethod: "nativeNode",
    nativeKind: "section",
  }),
  el({
    id: "el-container",
    label: "Container",
    description: "Stack or row content wrapper.",
    category: "layout",
    icon: "container",
    insertMethod: "nativeNode",
    nativeKind: "container",
  }),
  el({
    id: "el-columns",
    label: "Columns",
    description: "Two-column split layout.",
    category: "layout",
    icon: "columns",
    insertMethod: "nativeNode",
    nativeKind: "split",
  }),
  el({
    id: "el-grid",
    label: "Grid",
    description: "CSS grid layout block.",
    category: "layout",
    icon: "grid",
    insertMethod: "nativeNode",
    nativeKind: "container",
    nativeVariant: "grid",
  }),
  el({
    id: "el-stack",
    label: "Stack",
    description: "Vertical stack container.",
    category: "layout",
    icon: "stack",
    insertMethod: "nativeNode",
    nativeKind: "container",
    nativeVariant: "stack",
  }),
  el({
    id: "el-row",
    label: "Row",
    description: "Horizontal row container.",
    category: "layout",
    icon: "row",
    insertMethod: "nativeNode",
    nativeKind: "container",
    nativeVariant: "row",
  }),
  el({
    id: "el-card",
    label: "Card",
    description: "Bordered content card.",
    category: "layout",
    icon: "card",
    insertMethod: "nativeNode",
    nativeKind: "card",
  }),
  el({
    id: "el-card-group",
    label: "Card Group",
    description: "Row of related cards.",
    category: "layout",
    icon: "card-group",
    insertMethod: "nativeNode",
    nativeKind: "container",
    nativeVariant: "card-group",
  }),
  el({
    id: "el-spacer",
    label: "Spacer",
    description: "Vertical breathing room.",
    category: "layout",
    icon: "spacer",
    insertMethod: "nativeNode",
    nativeKind: "spacer",
  }),
  el({
    id: "el-divider",
    label: "Divider",
    description: "Horizontal rule between blocks.",
    category: "layout",
    icon: "divider",
    insertMethod: "nativeNode",
    nativeKind: "divider",
  }),

  // ── Elements / Cards ────────────────────────────────────────────────────
  el({
    id: "el-image-card",
    label: "Image Card",
    description: "Card with image and supporting copy.",
    category: "cards",
    icon: "image-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "image-card",
  }),
  el({
    id: "el-text-card",
    label: "Text Card",
    description: "Copy-forward content card.",
    category: "cards",
    icon: "text-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
  }),
  el({
    id: "el-icon-card",
    label: "Icon Card",
    description: "Icon-led feature or service card.",
    category: "cards",
    icon: "icon-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "icon-card",
  }),
  el({
    id: "el-profile-card",
    label: "Profile Card",
    description: "Portrait and bio card layout.",
    category: "cards",
    icon: "profile-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "profile-card",
  }),
  el({
    id: "el-service-card",
    label: "Service Card",
    description: "Service title with short description.",
    category: "cards",
    icon: "service-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "service-card",
  }),
  el({
    id: "el-testimonial-card",
    label: "Testimonial Card",
    description: "Client quote in a card.",
    category: "cards",
    icon: "testimonial-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "testimonial-card",
  }),
  el({
    id: "el-pricing-card",
    label: "Pricing Card",
    description: "Plan summary with price and CTA.",
    category: "cards",
    icon: "pricing-card",
    insertMethod: "nativeNode",
    nativeKind: "pricing_table",
  }),
  el({
    id: "el-cta-card",
    label: "CTA Card",
    description: "Compact conversion card.",
    category: "cards",
    icon: "cta-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "cta-card",
  }),

  // ── Elements / Interactive ──────────────────────────────────────────────
  el({
    id: "el-accordion",
    label: "Accordion",
    description: "Expandable Q&A or detail panels.",
    category: "interactive",
    icon: "accordion",
    insertMethod: "nativeNode",
    nativeKind: "accordion",
  }),
  el({
    id: "el-tabs",
    label: "Tabs",
    description: "Tabbed content panels.",
    category: "interactive",
    icon: "tabs",
    insertMethod: "nativeNode",
    nativeKind: "tabs",
  }),

  // ── Elements / Forms ────────────────────────────────────────────────────
  el({
    id: "el-contact-form",
    label: "Contact Form",
    description: "Name, email, and message fields.",
    category: "forms",
    icon: "contact-form",
    insertMethod: "nativeNode",
    nativeKind: "form",
    searchTerms: ["inquiry form"],
  }),
  el({
    id: "el-submit-button",
    label: "Submit Button",
    description: "Form submit action.",
    category: "forms",
    icon: "submit-button",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "button",
    searchTerms: ["form submit"],
  }),

  // ── Elements / Marketing ────────────────────────────────────────────────
  roadmap({
    id: "el-cta-banner",
    label: "CTA Banner",
    description: "Use Sections → CTA Banner instead.",
    category: "marketing",
    icon: "cta-banner",
  }),
  roadmap({
    id: "el-stats-counter",
    label: "Stats Counter",
    description: "Use Sections → About Stats instead.",
    category: "marketing",
    icon: "stats",
  }),
  roadmap({
    id: "el-testimonial",
    label: "Testimonial",
    description: "Use Sections → Testimonials Trio instead.",
    category: "marketing",
    icon: "testimonial",
  }),
  roadmap({
    id: "el-faq-group",
    label: "FAQ Group",
    description: "Use Sections → FAQ Accordion instead.",
    category: "marketing",
    icon: "faq",
  }),
  roadmap({
    id: "el-logo-strip",
    label: "Logo Strip",
    description: "Use Connected → Agency Logo instead.",
    category: "marketing",
    icon: "logo-strip",
  }),

  // ── Elements / Utility ──────────────────────────────────────────────────
  el({
    id: "el-breadcrumb",
    label: "Breadcrumb",
    description: "Page hierarchy navigation trail.",
    category: "utility",
    icon: "breadcrumb",
    insertMethod: "nativeNode",
    nativeKind: "nav",
    nativeVariant: "breadcrumb",
  }),
  el({
    id: "el-search-bar",
    label: "Search Bar",
    description: "Site or directory search input.",
    category: "utility",
    icon: "search",
    insertMethod: "sectionEmbed",
    sectionEmbedKey: "directory",
    sourceType: "section-embed",
  }),

  // ── Elements / Social & Embed ───────────────────────────────────────────
  el({
    id: "el-youtube",
    label: "YouTube Video",
    description: "Embedded YouTube player.",
    category: "social-embed",
    icon: "youtube",
    insertMethod: "nativeNode",
    nativeKind: "embed",
    nativeVariant: "youtube",
  }),
  el({
    id: "el-embed-url",
    label: "Embed URL",
    description: "Generic iframe embed block.",
    category: "social-embed",
    icon: "embed",
    insertMethod: "nativeNode",
    nativeKind: "embed",
  }),
  el({
    id: "el-external-link",
    label: "External Website Link",
    description: "Button linking to an external URL.",
    category: "social-embed",
    icon: "external-link",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "text-link",
    searchTerms: ["website link"],
  }),
];
