import type { AddGalleryItem } from "./types";
import { el, roadmap } from "./registry-helpers";

export const ADD_GALLERY_ELEMENT_ITEMS: ReadonlyArray<AddGalleryItem> = [
  // ── Elements / Text ─────────────────────────────────────────────────────
  el({
    id: "el-text",
    label: "Text",
    description: "Heading or paragraph — switch style in the bottom toolbar.",
    category: "text",
    icon: "text",
    insertMethod: "nativeNode",
    nativeKind: "paragraph",
    searchTerms: ["title", "subtitle", "intro", "heading", "paragraph", "body"],
  }),
  el({
    id: "el-rich-text",
    label: "Rich Text",
    description: "Formatted multi-paragraph content.",
    category: "text",
    icon: "rich-text",
    insertMethod: "nativeNode",
    nativeKind: "rich_text",
  }),
  el({
    id: "el-caption",
    label: "Caption",
    description: "Small supporting text under media.",
    category: "text",
    icon: "caption",
    insertMethod: "nativeNode",
    nativeKind: "paragraph",
    nativeVariant: "caption",
  }),
  el({
    id: "el-badge",
    label: "Badge",
    description: "Small label or status tag.",
    category: "text",
    icon: "badge",
    insertMethod: "nativeNode",
    nativeKind: "icon",
    nativeVariant: "badge",
  }),
  el({
    id: "el-quote",
    label: "Quote",
    description: "Pull quote or blockquote.",
    category: "text",
    icon: "quote",
    insertMethod: "nativeNode",
    nativeKind: "paragraph",
    nativeVariant: "quote",
  }),

  // ── Elements / Buttons ──────────────────────────────────────────────────
  el({
    id: "el-button",
    label: "Button",
    description: "Primary call-to-action button.",
    category: "buttons",
    icon: "button",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "button",
  }),
  el({
    id: "el-button-group",
    label: "Button Group",
    description: "Grouped primary and secondary actions.",
    category: "buttons",
    icon: "button-group",
    insertMethod: "nativeNode",
    nativeKind: "cta_group",
    nativeVariant: "button-group",
  }),
  el({
    id: "el-text-link",
    label: "Text Link",
    description: "Inline text link styled as a button.",
    category: "buttons",
    icon: "text-link",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "text-link",
  }),
  el({
    id: "el-icon-button",
    label: "Icon Button",
    description: "Compact icon-forward action.",
    category: "buttons",
    icon: "icon-button",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "icon-button",
  }),
  el({
    id: "el-book-now",
    label: "Book now",
    description: "Opens the existing booking page.",
    category: "buttons",
    icon: "booking",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "booking-button",
  }),
  roadmap({
    id: "el-inquiry-button",
    label: "Inquiry Button",
    description: "Use Connected → Inquiry Button or Sections → CTA Banner instead.",
    category: "buttons",
    icon: "inquiry",
  }),
  el({
    id: "el-booking-button",
    label: "Booking Button",
    description: "Embedded booking widget CTA.",
    category: "buttons",
    icon: "booking",
    insertMethod: "sectionEmbed",
    sectionEmbedKey: "booking_widget",
    sourceType: "section-embed",
  }),
  el({
    id: "el-download-link",
    label: "Download Link",
    description: "Button that links to a downloadable file.",
    category: "buttons",
    icon: "download",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "download-link",
  }),

  // ── Elements / Media ────────────────────────────────────────────────────
  el({
    id: "el-image",
    label: "Image",
    description: "Single responsive image.",
    category: "media",
    icon: "image",
    insertMethod: "nativeNode",
    nativeKind: "image",
  }),
  el({
    id: "el-cover-image",
    label: "Cover Image",
    description: "Wide hero-style image.",
    category: "media",
    icon: "cover",
    insertMethod: "nativeNode",
    nativeKind: "image",
    nativeVariant: "cover-image",
  }),
  el({
    id: "el-logo",
    label: "Logo",
    description: "Brand mark image.",
    category: "media",
    icon: "logo",
    insertMethod: "nativeNode",
    nativeKind: "image",
    nativeVariant: "logo",
  }),
  el({
    id: "el-icon",
    label: "Icon",
    description: "Decorative or functional icon.",
    category: "media",
    icon: "icon",
    insertMethod: "nativeNode",
    nativeKind: "icon",
  }),
  el({
    id: "el-video",
    label: "Video",
    description: "Hosted or uploaded video.",
    category: "media",
    icon: "video",
    insertMethod: "nativeNode",
    nativeKind: "video",
  }),
  roadmap({
    id: "el-gallery",
    label: "Gallery",
    description: "Use Sections → Gallery Grid or Gallery Strip instead.",
    category: "media",
    icon: "gallery",
  }),
  el({
    id: "el-image-grid",
    label: "Image Grid",
    description: "Responsive masonry image grid.",
    category: "media",
    icon: "image-grid",
    insertMethod: "nativeNode",
    nativeKind: "masonry",
    nativeVariant: "image-grid",
  }),
  el({
    id: "el-carousel",
    label: "Carousel",
    description: "Swipeable media carousel.",
    category: "media",
    icon: "carousel",
    insertMethod: "nativeNode",
    nativeKind: "carousel",
  }),

  // ── Layout ──────────────────────────────────────────────────────────────
  el({
    id: "el-section",
    label: "Section",
    description: "Top-level page section row.",
    tab: "blocks",
    category: "layout",
    icon: "section",
    insertMethod: "nativeNode",
    nativeKind: "section",
  }),
  el({
    id: "el-container",
    label: "Container",
    description: "Stack or row content wrapper.",
    tab: "blocks",
    category: "layout",
    icon: "container",
    insertMethod: "nativeNode",
    nativeKind: "container",
  }),
  el({
    id: "el-columns",
    label: "Columns",
    description: "Two-column split layout.",
    tab: "blocks",
    category: "layout",
    icon: "columns",
    insertMethod: "nativeNode",
    nativeKind: "split",
  }),
  el({
    id: "el-grid",
    label: "Grid",
    description: "CSS grid layout block.",
    tab: "blocks",
    category: "layout",
    icon: "grid",
    insertMethod: "nativeNode",
    nativeKind: "container",
    nativeVariant: "grid",
  }),
  el({
    id: "el-stack",
    label: "Stack",
    description: "Vertical stack container.",
    tab: "blocks",
    category: "layout",
    icon: "stack",
    insertMethod: "nativeNode",
    nativeKind: "container",
    nativeVariant: "stack",
  }),
  el({
    id: "el-row",
    label: "Row",
    description: "Horizontal row container.",
    tab: "blocks",
    category: "layout",
    icon: "row",
    insertMethod: "nativeNode",
    nativeKind: "container",
    nativeVariant: "row",
  }),
  el({
    id: "el-card",
    label: "Card",
    description: "Bordered content card.",
    tab: "blocks",
    category: "layout",
    icon: "card",
    insertMethod: "nativeNode",
    nativeKind: "card",
  }),
  el({
    id: "el-card-group",
    label: "Card Group",
    description: "Row of related cards.",
    tab: "blocks",
    category: "layout",
    icon: "card-group",
    insertMethod: "nativeNode",
    nativeKind: "container",
    nativeVariant: "card-group",
  }),
  el({
    id: "el-spacer",
    label: "Spacer",
    description: "Vertical breathing room.",
    tab: "blocks",
    category: "layout",
    icon: "spacer",
    insertMethod: "nativeNode",
    nativeKind: "spacer",
  }),
  el({
    id: "el-divider",
    label: "Divider",
    description: "Horizontal rule between blocks.",
    tab: "blocks",
    category: "layout",
    icon: "divider",
    insertMethod: "nativeNode",
    nativeKind: "divider",
  }),

  // ── Elements / Cards ────────────────────────────────────────────────────
  el({
    id: "el-image-card",
    label: "Image Card",
    description: "Card with image and supporting copy.",
    category: "cards",
    icon: "image-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "image-card",
  }),
  el({
    id: "el-text-card",
    label: "Text Card",
    description: "Copy-forward content card.",
    category: "cards",
    icon: "text-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
  }),
  el({
    id: "el-icon-card",
    label: "Icon Card",
    description: "Icon-led feature or service card.",
    category: "cards",
    icon: "icon-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "icon-card",
  }),
  el({
    id: "el-profile-card",
    label: "Profile Card",
    description: "Portrait and bio card layout.",
    category: "cards",
    icon: "profile-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "profile-card",
  }),
  el({
    id: "el-service-card",
    label: "Service Card",
    description: "Service title with short description.",
    category: "cards",
    icon: "service-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "service-card",
  }),
  el({
    id: "el-testimonial-card",
    label: "Testimonial Card",
    description: "Client quote in a card.",
    category: "cards",
    icon: "testimonial-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "testimonial-card",
  }),
  el({
    id: "el-pricing-card",
    label: "Pricing Card",
    description: "Plan summary with price and CTA.",
    category: "cards",
    icon: "pricing-card",
    insertMethod: "nativeNode",
    nativeKind: "pricing_table",
  }),
  el({
    id: "el-cta-card",
    label: "CTA Card",
    description: "Compact conversion card.",
    category: "cards",
    icon: "cta-card",
    insertMethod: "nativeNode",
    nativeKind: "card",
    nativeVariant: "cta-card",
  }),

  // ── Elements / Interactive ──────────────────────────────────────────────
  el({
    id: "el-accordion",
    label: "Accordion",
    description: "Expandable Q&A or detail panels.",
    category: "interactive",
    icon: "accordion",
    insertMethod: "nativeNode",
    nativeKind: "accordion",
  }),
  el({
    id: "el-tabs",
    label: "Tabs",
    description: "Tabbed content panels.",
    category: "interactive",
    icon: "tabs",
    insertMethod: "nativeNode",
    nativeKind: "tabs",
  }),

  // ── Elements / Forms ────────────────────────────────────────────────────
  el({
    id: "el-contact-form",
    label: "Contact Form",
    description: "Name, email, and message fields.",
    category: "forms",
    icon: "contact-form",
    insertMethod: "nativeNode",
    nativeKind: "form",
    searchTerms: ["inquiry form"],
  }),
  el({
    id: "el-submit-button",
    label: "Submit Button",
    description: "Form submit action.",
    category: "forms",
    icon: "submit-button",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "button",
    searchTerms: ["form submit"],
  }),

  // ── Elements / Utility ──────────────────────────────────────────────────
  el({
    id: "el-breadcrumb",
    label: "Breadcrumb",
    description: "Page hierarchy navigation trail.",
    category: "utility",
    icon: "breadcrumb",
    insertMethod: "nativeNode",
    nativeKind: "nav",
    nativeVariant: "breadcrumb",
  }),
  el({
    id: "el-search-bar",
    label: "Search Bar",
    description: "Site or directory search input.",
    category: "utility",
    icon: "search",
    insertMethod: "sectionEmbed",
    sectionEmbedKey: "directory",
    sourceType: "section-embed",
  }),

  // ── Elements / Social & Embed ───────────────────────────────────────────
  // Two entries for ONE node kind: an operator looks for "Instagram", not for a
  // generic "social post" they then have to configure. Each seeds its provider.
  el({
    id: "el-instagram-post",
    label: "Instagram Post",
    description: "Feature one Instagram post or reel.",
    category: "social-embed",
    icon: "instagram",
    insertMethod: "nativeNode",
    nativeKind: "social_post",
    nativeVariant: "instagram",
    searchTerms: ["instagram", "reel", "ig", "social"],
  }),
  el({
    id: "el-tiktok-post",
    label: "TikTok Video",
    description: "Feature one TikTok video.",
    category: "social-embed",
    icon: "video",
    insertMethod: "nativeNode",
    nativeKind: "social_post",
    nativeVariant: "tiktok",
    searchTerms: ["tiktok", "tik tok", "social", "video"],
  }),
  el({
    id: "el-social-feed-grid",
    label: "Instagram Grid",
    description: "Gallery grid of posts with lightbox. Paid plans.",
    category: "social-embed",
    icon: "instagram",
    insertMethod: "nativeNode",
    nativeKind: "social_feed",
    nativeVariant: "feed-grid",
    requiresPaidPlan: true,
    searchTerms: ["instagram", "feed", "gallery", "grid", "social"],
  }),
  el({
    id: "el-social-feed-masonry",
    label: "Social Masonry",
    description: "Waterfall gallery of posts and reels. Paid plans.",
    category: "social-embed",
    icon: "image",
    insertMethod: "nativeNode",
    nativeKind: "social_feed",
    nativeVariant: "feed-masonry",
    requiresPaidPlan: true,
    searchTerms: ["masonry", "instagram", "feed", "portfolio", "social"],
  }),
  el({
    id: "el-social-feed-slider",
    label: "Feed Slider",
    description: "Swipeable rail of posts with arrows. Paid plans.",
    category: "social-embed",
    icon: "carousel",
    insertMethod: "nativeNode",
    nativeKind: "social_feed",
    nativeVariant: "feed-slider",
    requiresPaidPlan: true,
    searchTerms: ["slider", "carousel", "swipe", "instagram", "tiktok", "feed"],
  }),
  el({
    id: "el-social-feed-stories",
    label: "Reels Strip",
    description: "Tall 9:16 reels rail, autoplay on view. Paid plans.",
    category: "social-embed",
    icon: "video",
    insertMethod: "nativeNode",
    nativeKind: "social_feed",
    nativeVariant: "feed-stories",
    requiresPaidPlan: true,
    searchTerms: ["reels", "stories", "tiktok", "video", "feed", "social"],
  }),
  el({
    id: "el-youtube",
    label: "YouTube Video",
    description: "Embedded YouTube player.",
    category: "social-embed",
    icon: "youtube",
    insertMethod: "nativeNode",
    nativeKind: "embed",
    nativeVariant: "youtube",
  }),
  el({
    id: "el-embed-url",
    label: "Embed URL",
    description: "Generic iframe embed block.",
    category: "social-embed",
    icon: "embed",
    insertMethod: "nativeNode",
    nativeKind: "embed",
  }),
  el({
    id: "el-external-link",
    label: "External Website Link",
    description: "Button linking to an external URL.",
    category: "social-embed",
    icon: "external-link",
    insertMethod: "nativeNode",
    nativeKind: "button",
    nativeVariant: "text-link",
    searchTerms: ["website link"],
  }),

  // ── Elements / Header Widgets (WS-A A5 — shell interactive embeds) ────────
  // Curated section_embed presets that wrap the live header's interactive
  // widgets. They render a placeholder on the editor canvas and the real widget
  // on the published shell (see sections/header_*/Component.tsx).
  el({
    id: "el-header-search",
    label: "Header Search",
    description: "The header's talent-search affordance (search icon → directory).",
    category: "header-widgets",
    icon: "search",
    insertMethod: "sectionEmbed",
    sectionEmbedKey: "header_search",
    sourceType: "section-embed",
    searchTerms: ["search", "directory", "header widget", "find talent"],
  }),
  el({
    id: "el-header-account",
    label: "Header Account",
    description: "The header's account menu / sign-in affordance.",
    category: "header-widgets",
    icon: "account",
    insertMethod: "sectionEmbed",
    sectionEmbedKey: "header_account",
    sourceType: "section-embed",
    searchTerms: ["account", "login", "sign in", "profile", "header widget"],
  }),
  el({
    id: "el-header-inquiry",
    label: "Header Inquiry",
    description: "The header's inquiry-cart affordance (plane icon → inquiry drawer).",
    category: "header-widgets",
    icon: "inquiry",
    insertMethod: "sectionEmbed",
    sectionEmbedKey: "header_inquiry",
    sourceType: "section-embed",
    searchTerms: ["inquiry", "cart", "shortlist", "header widget"],
  }),
  el({
    id: "el-header-favorites",
    label: "Header Favorites",
    description: "The header's saved-talent / favorites affordance (bookmark icon).",
    category: "header-widgets",
    icon: "bookmark",
    insertMethod: "sectionEmbed",
    sectionEmbedKey: "header_favorites",
    sourceType: "section-embed",
    searchTerms: ["favorites", "saved", "bookmark", "shortlist", "header widget"],
  }),
  el({
    id: "el-header-language",
    label: "Header Language",
    description: "The header's EN | ES language toggle for bilingual sites.",
    category: "header-widgets",
    icon: "globe",
    insertMethod: "sectionEmbed",
    sectionEmbedKey: "header_language",
    sourceType: "section-embed",
    searchTerms: ["language", "locale", "translate", "spanish", "english", "en es", "header widget"],
  }),
];
