import type { AddGalleryItem } from "./types";
import { connected } from "./registry-helpers";
import { AREA_DEFAULT_PROPS, LOCATION_DEFAULT_PROPS } from "../builder-node/visit-defaults";
import { PORTFOLIO_DEFAULT_PROPS } from "../builder-node/portfolio-defaults";
import { SERVICES_CATALOG_DEFAULT_PROPS } from "../builder-node/services-catalog-defaults";
import { RECENT_JOBS_LABEL } from "@/lib/talent-site/theme-catalog/seed-i18n";

export const ADD_GALLERY_SECTIONS_CONNECTED_BOOKING_BEFORE_ITEMS: ReadonlyArray<AddGalleryItem> = [
  // ── Connected / Booking & Inquiry ─────────────────────────────────────────
  connected({
    id: "conn-inquiry-button",
    label: "Inquiry Button",
    description: "Compact inquiry CTA with editable copy.",
    category: "booking",
    icon: "inquiry",
    insertMethod: "sectionTemplate",
    sectionTemplateId: "inquiry-cta",
    sourceType: "native-freeform",
    connectedSource: "Inquiry Collection",
  }),
  connected({
    id: "conn-booking-button",
    label: "Booking Button",
    description: "Embedded booking widget (dynamic embed).",
    category: "booking",
    icon: "booking",
    sectionEmbedKey: "booking_widget",
    connectedSource: "Booking",
  }),
  connected({
    id: "conn-menu-board-native",
    label: "Menu - orderable",
    description: "Workspace menu with quantity steppers and an order form for published items.",
    category: "booking",
    icon: "booking",
    insertMethod: "nativeNode",
    nativeKind: "menu_board",
    sourceType: "native-freeform",
    connectedSource: "Workspace Menu",
    searchTerms: ["menu board", "menu_order", "order food", "catering", "workspace menu"],
  }),
  connected({
    id: "conn-services-catalog-native",
    label: "Services menu",
    description: "The talent's live catalogue of services, packages and products.",
    category: "booking",
    icon: "booking",
    insertMethod: "nativeNode",
    nativeKind: "services_catalog",
    sourceType: "native-freeform",
    connectedSource: "Your services",
    searchTerms: ["services", "menu", "prices", "catalog", "offerings"],
  }),
  connected({
    id: "conn-services-matrix-native",
    label: "Services comparison",
    description:
      "Your services side by side: price, length, how it is booked, materials, warranty and response. A table on desktop, stacked cards on a phone.",
    category: "booking",
    icon: "booking",
    insertMethod: "nativeNode",
    nativeKind: "services_catalog",
    // Same node kind as `conn-services-catalog-native`; this card starts in the matrix layout.
    defaultProps: { ...SERVICES_CATALOG_DEFAULT_PROPS, layout: "matrix", categoryNav: "none", showStats: false },
    sourceType: "native-freeform",
    connectedSource: "Your services",
    searchTerms: ["comparison", "compare", "matrix", "table", "servicios", "comparar", "garantia", "warranty", "materials"],
  }),
  connected({
    id: "conn-portfolio-native",
    label: "Portfolio",
    description:
      "Live photos from your media library. Filmstrip, grid, masonry or contact sheet; each shot can open a service.",
    category: "dynamic",
    icon: "gallery",
    insertMethod: "nativeNode",
    nativeKind: "portfolio",
    sourceType: "native-freeform",
    connectedSource: "Your media",
    searchTerms: [
      "portfolio",
      "gallery",
      "filmstrip",
      "masonry",
      "contact sheet",
      "recent work",
      "photos",
    ],
  }),
  connected({
    id: "conn-reviews-native",
    label: "Reviews",
    description:
      "Live client reviews as quote cards. Trio, single, or row on the shared slider. Hidden when there are none.",
    category: "dynamic",
    icon: "testimonials",
    insertMethod: "nativeNode",
    nativeKind: "reviews",
    sourceType: "native-freeform",
    connectedSource: "Your reviews",
    searchTerms: [
      "reviews",
      "testimonials",
      "quotes",
      "clients",
      "feedback",
      "stars",
      "rating",
    ],
  }),
  connected({
    id: "conn-visit-native",
    label: "Visit",
    description:
      "Where you work, days, and languages from your profile. Optional map beside the facts. Hidden when empty.",
    category: "dynamic",
    icon: "about",
    insertMethod: "nativeNode",
    nativeKind: "visit",
    sourceType: "native-freeform",
    connectedSource: "Your profile",
    searchTerms: [
      "visit",
      "your visit",
      "service areas",
      "hours",
      "languages",
      "map",
      "where",
      "travels",
    ],
  }),
  connected({
    id: "conn-location-native",
    label: "Location",
    description:
      "Where to find you: studio kind, your zone, how to arrive, and a map area drawn from your city. Follows your address setting. Hidden when empty.",
    category: "dynamic",
    icon: "about",
    insertMethod: "nativeNode",
    nativeKind: "visit",
    // Same node kind as `conn-visit-native` (listed first, so it stays the
    // canonical card for `visit`); this card starts in the location layout.
    defaultProps: { ...LOCATION_DEFAULT_PROPS },
    sourceType: "native-freeform",
    connectedSource: "Your profile",
    searchTerms: ["location", "ubicacion", "address", "map", "where", "studio", "directions", "find me"],
  }),
  connected({
    id: "conn-area-native",
    label: "Area card",
    description:
      "An approximate service area: a drawn grid, the places you travel to as chips and your arrival note. Never an address. Hidden when empty.",
    category: "dynamic",
    icon: "about",
    insertMethod: "nativeNode",
    nativeKind: "visit",
    // Same node kind as `conn-visit-native`; this card starts in the area layout.
    defaultProps: { ...AREA_DEFAULT_PROPS },
    sourceType: "native-freeform",
    connectedSource: "Your profile",
    searchTerms: ["area", "zona", "service area", "municipalities", "travel", "radius", "coverage", "where i work"],
  }),
];

export const ADD_GALLERY_SECTIONS_CONNECTED_BOOKING_AFTER_ITEMS: ReadonlyArray<AddGalleryItem> = [
  connected({
    id: "conn-portfolio-work-order-native",
    label: "Job cards",
    description:
      "Your photos as work-order job cards: the job on the first caption line, the order detail on the second. No faces, no client names.",
    category: "dynamic",
    icon: "gallery",
    insertMethod: "nativeNode",
    nativeKind: "portfolio",
    // Same node kind as `conn-portfolio-native`; this card starts in the work_order layout.
    defaultProps: { ...PORTFOLIO_DEFAULT_PROPS, layout: "work_order", title: RECENT_JOBS_LABEL.en, limit: 6 },
    sourceType: "native-freeform",
    connectedSource: "Your media",
    searchTerms: ["jobs", "work order", "job cards", "trabajos", "orden de trabajo", "portfolio", "recent work"],
  }),
  connected({
    id: "conn-comp-card-native",
    label: "Comp card",
    description:
      "Measure strip from your public profile fields (height, bust, and more). Choose which measures show. Hidden when empty.",
    category: "dynamic",
    icon: "about",
    insertMethod: "nativeNode",
    nativeKind: "comp_card",
    sourceType: "native-freeform",
    connectedSource: "Your profile",
    searchTerms: [
      "comp card",
      "measure strip",
      "measurements",
      "height",
      "bust",
      "waist",
      "hips",
      "vitals",
      "ficha",
      "details",
    ],
  }),
  connected({
    id: "conn-next-free-chip-native",
    label: "Next free time",
    description:
      "Shows the next open booking slot from your live calendar. Hidden when nothing is free.",
    category: "booking",
    icon: "booking",
    insertMethod: "nativeNode",
    nativeKind: "next_free_chip",
    sourceType: "native-freeform",
    connectedSource: "Your calendar",
    searchTerms: [
      "next free",
      "next free time",
      "availability",
      "slot",
      "chip",
      "calendar",
      "open",
    ],
  }),
  connected({
    id: "conn-reserve-table-native",
    label: "Reserve a table",
    description:
      "A guest picks party size, date and time and books a real table, held as an order the host stand can see.",
    category: "booking",
    icon: "booking",
    insertMethod: "nativeNode",
    nativeKind: "reserve_table",
    sourceType: "native-freeform",
    connectedSource: "Reservations",
    searchTerms: [
      "reserve",
      "reservation",
      "book a table",
      "booking",
      "restaurant",
      "party size",
      "availability",
    ],
  }),
  connected({
    id: "conn-session-picker-native",
    label: "Book a session",
    description:
      "A guest picks an upcoming session or class and books a seat, held as an order; the seat past capacity is refused.",
    category: "booking",
    icon: "booking",
    insertMethod: "nativeNode",
    nativeKind: "session_picker",
    sourceType: "native-freeform",
    connectedSource: "Sessions",
    searchTerms: [
      "session",
      "class",
      "book a seat",
      "booking",
      "schedule",
      "sign up",
      "capacity",
    ],
  }),
  connected({
    id: "conn-ticket-picker-native",
    label: "Buy tickets",
    description:
      "Tier cards with what each includes, a quantity bar with a live total, one details sheet, then card checkout. Optional sticky Buy button that opens a bottom sheet on phones. A seat past capacity is refused.",
    category: "booking",
    icon: "booking",
    insertMethod: "nativeNode",
    nativeKind: "ticket_picker",
    sourceType: "native-freeform",
    connectedSource: "Events",
    searchTerms: [
      "ticket",
      "tickets",
      "event",
      "night",
      "buy",
      "checkout",
      "door",
      "tiers",
      "vip",
      "table",
      "mesa",
      "sheet",
    ],
  }),
  connected({
    id: "conn-event-program-native",
    label: "Event program",
    description:
      "The event's timed program: sets, talks, doors and close by night, with performer and cover. Timeline, cards or compact. Binds to the event this page belongs to.",
    category: "booking",
    icon: "booking",
    insertMethod: "nativeNode",
    nativeKind: "event_program",
    sourceType: "native-freeform",
    connectedSource: "Events",
    searchTerms: [
      "program",
      "programa",
      "schedule",
      "lineup",
      "agenda",
      "set times",
      "timeline",
      "performers",
      "night",
      "stage",
    ],
  }),
  connected({
    id: "conn-qr-code-native",
    label: "QR code",
    description:
      "A scannable code for one of your links. Point a phone at it and it opens the link.",
    category: "booking",
    icon: "booking",
    insertMethod: "nativeNode",
    nativeKind: "qr_code",
    sourceType: "native-freeform",
    connectedSource: "QR & Links",
    searchTerms: [
      "qr",
      "qr code",
      "scan",
      "link",
      "print",
      "table tent",
      "share",
    ],
  }),

];
