import { buildLook } from "./shared";

/** Look `bold` — Scale and contrast: oversized display, full-bleed bands. */
export const boldLook = buildLook({
  id: "bold",
  title: { es: "Audaz", en: "Bold" },
  axis: { es: "Escala y contraste: display grande, bandas a sangre", en: "Scale and contrast: oversized display, full-bleed bands" },
  themePatch: {
    "color.background": "#ffffff",
    "color.ink": "#0a0a0a",
    "color.neutral": "#0a0a0a",
    "color.primary": "#0a0a0a",
    "color.secondary": "#444444",
    "color.accent": "#ffcc00",
    "color.muted": "#555555",
    "color.line": "#111111",
    "color.surface-raised": "#f2f2f2",
    "typography.heading-preset": "display",
    "typography.body-preset": "sans",
    "typography.scale-preset": "editorial",
    "typography.tracking-preset": "tight",
    "radius.scale-preset": "sharp",
    "shadow.preset": "crisp",
    "motion.preset": "snappy",
    "density.section-padding": "tight",
    "density.container-width": "wide",
    "background.mode": "plain",
    "shell.header-variant": "classic-solid",
    "shell.footer-variant": "espresso-column",
  },
  recipe: {
    hero: "banded",
    heroBand: "accent",
    heroMinHeight: "60svh",
    offer: "list",
    proofBand: "contrast",
    closing: "contrast",
    gallery: "grid",
    cardVariant: "outline",
    imageRadius: "none",
    header: "split",
    footer: "stacked",
    headingStyle: {"fontWeight": 800, "textTransform": "uppercase", "letterSpacing": "-0.02em"},
    displayStyle: {"size": "display", "fontWeight": 900, "textTransform": "uppercase", "letterSpacing": "-0.04em", "lineHeight": "0.95"},
    sectionPadding: "l",
  },
  copyOverrides: {
    "home.offer.headline": { es: "Directo al grano", en: "Straight to the point" },
    "home.closing.headline": { es: "Hablemos hoy", en: "Let us talk today" },
  },
});
