import { buildLook } from "./shared";

/** Look `bold` — Looks v2 (D-TPL-36): Fitness: black, electric lime, display sans, energy. Cinematic hero, marquee, statement, sticky story, gallery rail, slide-up reveals. */
export const boldLook = buildLook({
  id: "bold",
  title: { es: "Audaz", en: "Bold" },
  axis: { es: "Fitness: negro, lima eléctrica, display sans, energía", en: "Fitness: black, electric lime, display sans, energy" },
  themePatch: {
    "color.background": "#0a0a0b",
    "color.ink": "#ffffff",
    "color.neutral": "#ffffff",
    "color.primary": "#c8ff3d",
    "color.secondary": "#9aa0a6",
    "color.accent": "#ff4d4d",
    "color.muted": "#a6a9ad",
    "color.line": "#232427",
    "color.surface-raised": "#141517",
    "typography.heading-preset": "display",
    "typography.body-preset": "sans",
    "typography.scale-preset": "editorial",
    "radius.scale-preset": "pill",
    "shadow.preset": "crisp",
    "motion.preset": "snappy",
    "density.section-padding": "standard",
    "background.mode": "plain",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "espresso-column",
  },
  recipe: {
    hero: "cinematic",
    heroBand: "none",
    heroMinHeight: "100svh",
    offer: "cards",
    proofBand: "surface",
    closing: "accent",
    gallery: "rail",
    cardVariant: "ghost",
    imageRadius: "lg",
    header: "split",
    footer: "line",
    headingStyle: { fontWeight: 800, letterSpacing: "-0.03em", textTransform: "uppercase" },
    displayStyle: { size: "display", fontWeight: 900, letterSpacing: "-0.04em", textTransform: "uppercase", textWrap: "balance" },
    eyebrowStyle: { letterSpacing: "0.2em", textTransform: "uppercase" },
    sectionPadding: "l",
    motion: "slide-up",
    marquee: true,
    statement: true,
    story: "sticky",
    lift: true,
  },
  copyOverrides: {
    "home.statement": { es: "Más fuerte cada semana.", en: "Stronger every week." },
    "home.offer.headline": { es: "Directo al grano", en: "Straight to the point" },
    "home.closing.headline": { es: "Empieza hoy", en: "Start today" },
  },
});
