import { buildLook } from "./shared";

/** Look `classic` — Symmetry: centred, serif and sans, framed images. */
export const classicLook = buildLook({
  id: "classic",
  title: { es: "Clásico", en: "Classic" },
  axis: { es: "Simetría: centrado, serif y sans, imágenes enmarcadas", en: "Symmetry: centred, serif and sans, framed images" },
  themePatch: {
    "color.background": "#fcfbf8",
    "color.ink": "#1e2430",
    "color.neutral": "#1e2430",
    "color.primary": "#1e3a5f",
    "color.secondary": "#5c6675",
    "color.accent": "#b08d57",
    "color.muted": "#6a7280",
    "color.line": "#dfe2e8",
    "color.surface-raised": "#f3f4f6",
    "typography.heading-preset": "serif",
    "typography.body-preset": "sans",
    "typography.scale-preset": "standard",
    "typography.tracking-preset": "normal",
    "radius.scale-preset": "soft",
    "shadow.preset": "soft",
    "motion.preset": "refined",
    "density.section-padding": "standard",
    "density.container-width": "standard",
    "background.mode": "plain",
    "shell.header-variant": "centered-editorial",
    "shell.footer-variant": "classic-minimal",
  },
  recipe: {
    hero: "centered",
    heroBand: "none",
    heroMinHeight: "60svh",
    offer: "split",
    proofBand: "muted",
    closing: "muted",
    gallery: "grid",
    cardVariant: "outline",
    imageRadius: "sm",
    header: "centered",
    footer: "columns",
    headingStyle: {"fontWeight": 500, "align": "center"},
    displayStyle: {"size": "xl", "fontWeight": 500, "align": "center", "textWrap": "balance"},
    eyebrowStyle: {"align": "center"},
    sectionPadding: "xl",
    rulesBetweenSections: true,
  },
  copyOverrides: {
    "home.offer.headline": { es: "Bien hecho, desde siempre", en: "Done well, as always" },
  },
});
