import { buildLook } from "./shared";

/** Look `classic` — Looks v2 (D-TPL-36): Professionals: navy, sky, serif and sans, centred. Cinematic hero, marquee, statement, sticky story, gallery rail, rise reveals. */
export const classicLook = buildLook({
  id: "classic",
  title: { es: "Clásico", en: "Classic" },
  axis: { es: "Profesionales: azul marino, cielo, serif y sans, centrado", en: "Professionals: navy, sky, serif and sans, centred" },
  themePatch: {
    "color.background": "#0e1b2b",
    "color.ink": "#f2f4f7",
    "color.neutral": "#f2f4f7",
    "color.primary": "#4fa3ff",
    "color.secondary": "#9fb3c8",
    "color.accent": "#ffd166",
    "color.muted": "#a9b6c6",
    "color.line": "#1d2f45",
    "color.surface-raised": "#152538",
    "typography.heading-preset": "editorial-serif",
    "typography.body-preset": "refined-sans",
    "typography.scale-preset": "editorial",
    "radius.scale-preset": "soft",
    "shadow.preset": "ambient",
    "motion.preset": "refined",
    "density.section-padding": "airy",
    "background.mode": "plain",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "espresso-column",
  },
  recipe: {
    hero: "cinematic",
    heroBand: "none",
    heroMinHeight: "100svh",
    offer: "cards",
    proofBand: "surface",
    closing: "accent",
    gallery: "rail",
    cardVariant: "elevated",
    imageRadius: "md",
    header: "centered",
    footer: "columns",
    headingStyle: { fontWeight: 500 },
    displayStyle: { size: "display", fontWeight: 500, letterSpacing: "-0.02em", textWrap: "balance" },
    eyebrowStyle: { letterSpacing: "0.22em", textTransform: "uppercase" },
    sectionPadding: "xl",
    motion: "rise",
    marquee: true,
    statement: true,
    story: "sticky",
    lift: true,
  },
  copyOverrides: {
    "home.statement": { es: "Bien hecho, desde siempre.", en: "Done well, as always." },
    "home.offer.headline": { es: "Bien hecho, desde siempre", en: "Done well, as always" },
  },
});
