import { buildLook } from "./shared";

/** Look `coastal` — Place: wide photos, sage and sand, a moving strip. */
export const coastalLook = buildLook({
  id: "coastal",
  title: { es: "Costero", en: "Coastal" },
  axis: { es: "Lugar: fotos anchas, salvia y arena, franja en movimiento", en: "Place: wide photos, sage and sand, a moving strip" },
  themePatch: {
    "color.background": "#fbfaf6",
    "color.ink": "#1f2a2a",
    "color.neutral": "#1f2a2a",
    "color.primary": "#2f6f6a",
    "color.secondary": "#7b8f8c",
    "color.accent": "#d8b98a",
    "color.muted": "#6e7d7b",
    "color.line": "#e2e6e1",
    "color.surface-raised": "#eef2ee",
    "typography.heading-preset": "serif",
    "typography.body-preset": "sans",
    "typography.scale-preset": "standard",
    "typography.tracking-preset": "normal",
    "radius.scale-preset": "soft",
    "shadow.preset": "soft",
    "motion.preset": "editorial",
    "density.section-padding": "airy",
    "density.container-width": "wide",
    "background.mode": "plain",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "ivory-minimal",
  },
  recipe: {
    hero: "fullbleed",
    heroBand: "none",
    heroMinHeight: "80svh",
    offer: "prose",
    proofBand: "surface",
    closing: "surface",
    gallery: "strip",
    cardVariant: "ghost",
    imageRadius: "md",
    header: "left-nav",
    footer: "columns",
    headingStyle: {"fontWeight": 400},
    displayStyle: {"size": "display", "fontWeight": 400, "textWrap": "balance"},
    sectionPadding: "xl",
  },
  copyOverrides: {
    "home.closing.headline": { es: "Ven cuando quieras", en: "Come whenever you like" },
  },
});
