import { buildLook } from "./shared";

/** Look `coastal` — Looks v2 (D-TPL-36): Tours: white, turquoise, amber, wide photos and air. Cinematic hero, marquee, statement, sticky story, gallery rail, slide-up reveals. */
export const coastalLook = buildLook({
  id: "coastal",
  title: { es: "Costero", en: "Coastal" },
  axis: { es: "Tours: blanco, turquesa, ámbar, fotos anchas y aire", en: "Tours: white, turquoise, amber, wide photos and air" },
  themePatch: {
    "color.background": "#f7fbfc",
    "color.ink": "#062a3a",
    "color.neutral": "#062a3a",
    "color.primary": "#0aa6c9",
    "color.secondary": "#4d7c8a",
    "color.accent": "#ffb703",
    "color.muted": "#5b7683",
    "color.line": "#dbe9ee",
    "color.surface-raised": "#ffffff",
    "typography.heading-preset": "display",
    "typography.body-preset": "sans",
    "typography.scale-preset": "editorial",
    "radius.scale-preset": "pillowy",
    "shadow.preset": "soft",
    "motion.preset": "refined",
    "density.section-padding": "airy",
    "background.mode": "aurora",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "classic-minimal",
  },
  recipe: {
    hero: "cinematic",
    heroBand: "none",
    heroMinHeight: "100svh",
    offer: "cards",
    proofBand: "surface",
    closing: "accent",
    gallery: "rail",
    cardVariant: "elevated",
    imageRadius: "lg",
    header: "split",
    footer: "columns",
    headingStyle: { fontWeight: 700, letterSpacing: "-0.02em" },
    displayStyle: { size: "display", fontWeight: 800, letterSpacing: "-0.04em", textWrap: "balance" },
    eyebrowStyle: { letterSpacing: "0.22em", textTransform: "uppercase" },
    sectionPadding: "xl",
    motion: "slide-up",
    marquee: true,
    statement: true,
    story: "sticky",
    lift: true,
  },
  copyOverrides: {
    "home.statement": { es: "Sal. El día es largo y el agua está cerca.", en: "Go out. The day is long and the water is near." },
    "home.closing.headline": { es: "Ven cuando quieras", en: "Come whenever you like" },
  },
});
