import { buildLook } from "./shared";

/** Look `dark` — Looks v2 (D-TPL-36): Polarity: charcoal, one saturated accent, motion. Cinematic hero, marquee, statement, sticky story, gallery rail, rise reveals. */
export const darkLook = buildLook({
  id: "dark",
  title: { es: "Oscuro", en: "Dark" },
  axis: { es: "Polaridad: carbón, un acento saturado, movimiento", en: "Polarity: charcoal, one saturated accent, motion" },
  themePatch: {
    "color.background": "#0c0c0d",
    "color.ink": "#f4f4f4",
    "color.neutral": "#f4f4f4",
    "color.primary": "#ff5c39",
    "color.secondary": "#8c8c8c",
    "color.accent": "#ffd166",
    "color.muted": "#9a9a9a",
    "color.line": "#232326",
    "color.surface-raised": "#161618",
    "typography.heading-preset": "sans",
    "typography.body-preset": "sans",
    "typography.scale-preset": "editorial",
    "radius.scale-preset": "soft",
    "shadow.preset": "crisp",
    "motion.preset": "snappy",
    "density.section-padding": "standard",
    "background.mode": "plain",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "espresso-column",
  },
  recipe: {
    hero: "cinematic",
    heroBand: "none",
    heroMinHeight: "100svh",
    offer: "cards",
    proofBand: "surface",
    closing: "accent",
    gallery: "rail",
    cardVariant: "elevated",
    imageRadius: "md",
    header: "split",
    footer: "line",
    headingStyle: { fontWeight: 700, letterSpacing: "-0.02em" },
    displayStyle: { size: "display", fontWeight: 800, letterSpacing: "-0.04em", textWrap: "balance" },
    eyebrowStyle: { letterSpacing: "0.2em", textTransform: "uppercase" },
    sectionPadding: "l",
    motion: "rise",
    marquee: true,
    statement: true,
    story: "sticky",
    lift: true,
  },
  copyOverrides: {
    "home.statement": { es: "Un acento. Nada más.", en: "One accent. Nothing else." },
  },
});
