import { buildLook } from "./shared";

/** Look `editorial` — Looks v2 (D-TPL-36): Agencies: pure white, black, orange, editorial serif, air. Cinematic hero, marquee, statement, sticky story, gallery rail, fade-left reveals. */
export const editorialLook = buildLook({
  id: "editorial",
  title: { es: "Editorial", en: "Editorial" },
  axis: { es: "Agencias: blanco puro, negro, naranja, serif editorial, aire", en: "Agencies: pure white, black, orange, editorial serif, air" },
  themePatch: {
    "color.background": "#fbfaf7",
    "color.ink": "#0f0f0f",
    "color.neutral": "#0f0f0f",
    "color.primary": "#0f0f0f",
    "color.secondary": "#6b6b6b",
    "color.accent": "#ff5a1f",
    "color.muted": "#6f6f6f",
    "color.line": "#e6e3dc",
    "color.surface-raised": "#ffffff",
    "typography.heading-preset": "editorial-serif",
    "typography.body-preset": "refined-sans",
    "typography.scale-preset": "editorial",
    "radius.scale-preset": "sharp",
    "shadow.preset": "none",
    "motion.preset": "editorial",
    "density.section-padding": "airy",
    "background.mode": "plain",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "serif-editorial",
  },
  recipe: {
    hero: "cinematic",
    heroBand: "none",
    heroMinHeight: "100svh",
    offer: "cards",
    proofBand: "surface",
    closing: "contrast",
    gallery: "rail",
    cardVariant: "ghost",
    imageRadius: "none",
    header: "centered",
    footer: "columns",
    headingStyle: { fontWeight: 400, letterSpacing: "-0.01em" },
    displayStyle: { size: "display", fontWeight: 400, letterSpacing: "-0.03em", textWrap: "balance" },
    eyebrowStyle: { letterSpacing: "0.26em", textTransform: "uppercase" },
    sectionPadding: "xl",
    motion: "fade-left",
    marquee: true,
    statement: true,
    story: "sticky",
    lift: true,
  },
  copyOverrides: {
    "home.statement": { es: "Con calma y con oficio.", en: "Unhurried, and done properly." },
    "home.offer.headline": { es: "Con calma y con oficio", en: "Unhurried, and done properly" },
  },
});
