import { buildLook } from "./shared";

/** Look `editorial` — Type-led restraint: serif, air, hairlines. */
export const editorialLook = buildLook({
  id: "editorial",
  title: { es: "Editorial", en: "Editorial" },
  axis: { es: "Restricción tipográfica: serif, aire, líneas finas", en: "Type-led restraint: serif, air, hairlines" },
  themePatch: {
    "color.background": "#fbfaf7",
    "color.ink": "#1b1a17",
    "color.neutral": "#1b1a17",
    "color.primary": "#1b1a17",
    "color.secondary": "#6b6660",
    "color.accent": "#8a6a3e",
    "color.muted": "#6b6660",
    "color.line": "#e6e1d8",
    "color.surface-raised": "#f3efe8",
    "typography.heading-preset": "editorial-serif",
    "typography.body-preset": "serif",
    "typography.scale-preset": "editorial",
    "typography.tracking-preset": "editorial",
    "radius.scale-preset": "sharp",
    "shadow.preset": "none",
    "motion.preset": "editorial",
    "density.section-padding": "airy",
    "density.container-width": "editorial",
    "background.mode": "editorial-ivory",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "ivory-minimal",
  },
  recipe: {
    hero: "left",
    heroBand: "none",
    heroMinHeight: "70svh",
    offer: "split",
    proofBand: "none",
    closing: "muted",
    gallery: "masonry",
    cardVariant: "ghost",
    imageRadius: "none",
    header: "left-nav",
    footer: "columns",
    headingStyle: {"fontWeight": 400, "letterSpacing": "-0.01em"},
    displayStyle: {"size": "display", "fontWeight": 400, "letterSpacing": "-0.02em", "textWrap": "balance"},
    eyebrowStyle: {"fontStyle": "italic", "textTransform": "none", "letterSpacing": "0"},
    sectionPadding: "xl",
    rulesBetweenSections: true,
  },
  copyOverrides: {
    "home.offer.headline": { es: "Con calma y con oficio", en: "Unhurried, and done properly" },
  },
});
