import { buildLook } from "./shared";

/** Look `minimal` — Looks v2 (D-TPL-36): Neutral: white, black, one blue; subtraction in motion. Cinematic hero, marquee, statement, sticky story, gallery rail, fade-in reveals. */
export const minimalLook = buildLook({
  id: "minimal",
  title: { es: "Mínimo", en: "Minimal" },
  axis: { es: "Neutral: blanco, negro, un azul; sustracción con movimiento", en: "Neutral: white, black, one blue; subtraction in motion" },
  themePatch: {
    "color.background": "#ffffff",
    "color.ink": "#0a0a0a",
    "color.neutral": "#0a0a0a",
    "color.primary": "#0a0a0a",
    "color.secondary": "#6a6a6a",
    "color.accent": "#2f6bff",
    "color.muted": "#6f6f6f",
    "color.line": "#ececec",
    "color.surface-raised": "#f7f7f7",
    "typography.heading-preset": "sans",
    "typography.body-preset": "refined-sans",
    "typography.scale-preset": "editorial",
    "radius.scale-preset": "sharp",
    "shadow.preset": "none",
    "motion.preset": "editorial",
    "density.section-padding": "airy",
    "background.mode": "plain",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "classic-minimal",
  },
  recipe: {
    hero: "cinematic",
    heroBand: "none",
    heroMinHeight: "100svh",
    offer: "cards",
    proofBand: "surface",
    closing: "contrast",
    gallery: "rail",
    cardVariant: "ghost",
    imageRadius: "none",
    header: "minimal",
    footer: "line",
    headingStyle: { fontWeight: 500, letterSpacing: "-0.02em" },
    displayStyle: { size: "display", fontWeight: 500, letterSpacing: "-0.04em", textWrap: "balance" },
    eyebrowStyle: { letterSpacing: "0.24em", textTransform: "uppercase" },
    sectionPadding: "xl",
    motion: "fade-in",
    marquee: true,
    statement: true,
    story: "sticky",
    lift: true,
  },
  copyOverrides: {
    "home.statement": { es: "Lo esencial, bien hecho.", en: "The essentials, done well." },
    "home.offer.headline": { es: "Lo esencial", en: "The essentials" },
  },
});
