import { buildLook } from "./shared";

/** Look `minimal` — Subtraction: monochrome, small type, lots of air. */
export const minimalLook = buildLook({
  id: "minimal",
  title: { es: "Mínimo", en: "Minimal" },
  axis: { es: "Sustracción: monocromo, tipografía pequeña, mucho aire", en: "Subtraction: monochrome, small type, lots of air" },
  themePatch: {
    "color.background": "#ffffff",
    "color.ink": "#111111",
    "color.neutral": "#111111",
    "color.primary": "#111111",
    "color.secondary": "#777777",
    "color.accent": "#111111",
    "color.muted": "#8a8a8a",
    "color.line": "#ececec",
    "color.surface-raised": "#fafafa",
    "typography.heading-preset": "sans",
    "typography.body-preset": "sans",
    "typography.scale-preset": "compact",
    "typography.tracking-preset": "normal",
    "radius.scale-preset": "sharp",
    "shadow.preset": "none",
    "motion.preset": "none",
    "density.section-padding": "airy",
    "density.container-width": "narrow",
    "background.mode": "plain",
    "shell.header-variant": "minimal",
    "shell.footer-variant": "classic-minimal",
  },
  recipe: {
    hero: "stacked",
    heroBand: "none",
    heroMinHeight: "50svh",
    offer: "prose",
    proofBand: "none",
    closing: "surface",
    gallery: "grid",
    cardVariant: "ghost",
    imageRadius: "none",
    header: "minimal",
    footer: "line",
    headingStyle: {"fontWeight": 500, "size": "md"},
    displayStyle: {"size": "lg", "fontWeight": 500, "letterSpacing": "-0.01em"},
    eyebrowStyle: {"textTransform": "none", "letterSpacing": "0"},
    sectionPadding: "xl",
  },
  copyOverrides: {
    "home.offer.headline": { es: "Lo esencial", en: "The essentials" },
  },
});
