import { buildLook } from "./shared";

/** Look `night` — Motion: dark with a neon accent, tight rhythm. */
export const nightLook = buildLook({
  id: "night",
  title: { es: "Noche", en: "Night" },
  axis: { es: "Movimiento: oscuro con acento neón, ritmo apretado", en: "Motion: dark with a neon accent, tight rhythm" },
  themePatch: {
    "color.background": "#0b0b12",
    "color.ink": "#f5f2ff",
    "color.neutral": "#f5f2ff",
    "color.primary": "#c8ff3d",
    "color.secondary": "#a99ad6",
    "color.accent": "#ff4fd8",
    "color.muted": "#8d86a8",
    "color.line": "#241f36",
    "color.surface-raised": "#15122a",
    "typography.heading-preset": "display",
    "typography.body-preset": "sans",
    "typography.scale-preset": "editorial",
    "typography.tracking-preset": "tight",
    "radius.scale-preset": "pillowy",
    "shadow.preset": "ambient",
    "motion.preset": "snappy",
    "density.section-padding": "tight",
    "density.container-width": "wide",
    "background.mode": "aurora",
    "shell.header-variant": "espresso-column",
    "shell.footer-variant": "espresso-column",
  },
  recipe: {
    hero: "banded",
    heroBand: "contrast",
    heroMinHeight: "58svh",
    offer: "cards",
    proofBand: "surface",
    closing: "accent",
    gallery: "masonry",
    cardVariant: "elevated",
    imageRadius: "lg",
    header: "split",
    footer: "stacked",
    headingStyle: {"fontWeight": 700, "letterSpacing": "-0.02em"},
    displayStyle: {"size": "display", "fontWeight": 800, "textTransform": "uppercase", "letterSpacing": "-0.03em", "lineHeight": "0.95"},
    sectionPadding: "l",
  },
  copyOverrides: {
    "home.closing.headline": { es: "Nos vemos esta noche", en: "See you tonight" },
  },
});
