import { buildLook } from "./shared";

/** Look `night` — Looks v2 (D-TPL-36): Events: deep indigo, neon magenta, zoom and light. Cinematic hero, marquee, statement, sticky story, gallery rail, zoom-in reveals. */
export const nightLook = buildLook({
  id: "night",
  title: { es: "Noche", en: "Night" },
  axis: { es: "Eventos: índigo profundo, neón magenta, zoom y luz", en: "Events: deep indigo, neon magenta, zoom and light" },
  themePatch: {
    "color.background": "#0b0a1a",
    "color.ink": "#f4f2ff",
    "color.neutral": "#f4f2ff",
    "color.primary": "#ff3ea5",
    "color.secondary": "#9b8cff",
    "color.accent": "#7c5cff",
    "color.muted": "#aaa6c9",
    "color.line": "#231f45",
    "color.surface-raised": "#151332",
    "typography.heading-preset": "display",
    "typography.body-preset": "sans",
    "typography.scale-preset": "editorial",
    "radius.scale-preset": "pill",
    "shadow.preset": "ambient",
    "motion.preset": "snappy",
    "density.section-padding": "standard",
    "background.mode": "mesh-noir",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "espresso-column",
  },
  recipe: {
    hero: "cinematic",
    heroBand: "none",
    heroMinHeight: "100svh",
    offer: "cards",
    proofBand: "surface",
    closing: "accent",
    gallery: "rail",
    cardVariant: "elevated",
    imageRadius: "lg",
    header: "split",
    footer: "columns",
    headingStyle: { fontWeight: 700, letterSpacing: "-0.02em" },
    displayStyle: { size: "display", fontWeight: 800, letterSpacing: "-0.04em", textWrap: "balance" },
    eyebrowStyle: { letterSpacing: "0.22em", textTransform: "uppercase" },
    sectionPadding: "l",
    motion: "zoom-in",
    marquee: true,
    statement: true,
    story: "sticky",
    lift: true,
  },
  copyOverrides: {
    "home.statement": { es: "La noche empieza aquí.", en: "The night starts here." },
    "home.closing.headline": { es: "Nos vemos esta noche", en: "See you tonight" },
  },
});
