import { buildLook } from "./shared";

/** Look `playful` — Looks v2 (D-TPL-36): Education: white, coral, yellow, bounce and colour. Cinematic hero, marquee, statement, sticky story, gallery rail, bounce-in reveals. */
export const playfulLook = buildLook({
  id: "playful",
  title: { es: "Juguetón", en: "Playful" },
  axis: { es: "Educación: blanco, coral, amarillo, rebote y color", en: "Education: white, coral, yellow, bounce and colour" },
  themePatch: {
    "color.background": "#ffffff",
    "color.ink": "#14213d",
    "color.neutral": "#14213d",
    "color.primary": "#ff6b35",
    "color.secondary": "#3a86ff",
    "color.accent": "#ffd60a",
    "color.muted": "#5b6478",
    "color.line": "#e9ecf2",
    "color.surface-raised": "#f6f7fb",
    "typography.heading-preset": "display",
    "typography.body-preset": "sans",
    "typography.scale-preset": "standard",
    "radius.scale-preset": "pillowy",
    "shadow.preset": "soft",
    "motion.preset": "snappy",
    "density.section-padding": "standard",
    "background.mode": "aurora",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "classic-minimal",
  },
  recipe: {
    hero: "cinematic",
    heroBand: "none",
    heroMinHeight: "100svh",
    offer: "cards",
    proofBand: "surface",
    closing: "accent",
    gallery: "rail",
    cardVariant: "elevated",
    imageRadius: "lg",
    header: "left-nav",
    footer: "stacked",
    headingStyle: { fontWeight: 800, letterSpacing: "-0.02em" },
    displayStyle: { size: "display", fontWeight: 900, letterSpacing: "-0.04em", textWrap: "balance" },
    eyebrowStyle: { letterSpacing: "0.18em", textTransform: "uppercase" },
    sectionPadding: "l",
    motion: "bounce-in",
    marquee: true,
    statement: true,
    story: "sticky",
    lift: true,
  },
  copyOverrides: {
    "home.statement": { es: "Aprender también puede ser divertido.", en: "Learning can be fun too." },
    "home.closing.headline": { es: "¡Escríbenos!", en: "Say hello!" },
    "home.offer.headline": { es: "Con ganas y con gusto", en: "With energy and taste" },
  },
});
