import { buildLook } from "./shared";

/** Look `playful` — Colour rhythm: pill buttons, bright secondary, colour cards. */
export const playfulLook = buildLook({
  id: "playful",
  title: { es: "Juguetón", en: "Playful" },
  axis: { es: "Ritmo de color: botones píldora, secundario brillante, tarjetas de color", en: "Colour rhythm: pill buttons, bright secondary, colour cards" },
  themePatch: {
    "color.background": "#fffdf7",
    "color.ink": "#1f1b2e",
    "color.neutral": "#1f1b2e",
    "color.primary": "#5b3df5",
    "color.secondary": "#ff7a59",
    "color.accent": "#ffd23f",
    "color.muted": "#5f5a73",
    "color.line": "#eae5f6",
    "color.surface-raised": "#f4f0ff",
    "typography.heading-preset": "display",
    "typography.body-preset": "sans",
    "typography.scale-preset": "standard",
    "radius.scale-preset": "pill",
    "shadow.preset": "crisp",
    "motion.preset": "snappy",
    "density.section-padding": "standard",
    "background.mode": "mesh-blush",
    "shell.header-variant": "classic-solid",
    "shell.footer-variant": "classic-minimal",
  },
  recipe: {
    hero: "centered",
    heroBand: "surface",
    heroMinHeight: "62svh",
    offer: "cards",
    proofBand: "accent",
    closing: "accent",
    gallery: "grid",
    cardVariant: "elevated",
    imageRadius: "lg",
    header: "centered",
    footer: "stacked",
    headingStyle: {"fontWeight": 700},
    displayStyle: {"size": "display", "fontWeight": 800, "textWrap": "balance"},
    sectionPadding: "l",
  },
  copyOverrides: {
    "home.closing.headline": { es: "¡Escríbenos!", en: "Say hello!" },
    "home.offer.headline": { es: "Con ganas y con gusto", en: "With energy and taste" },
  },
});
