import { buildLook } from "./shared";

/** Look `studio` — Looks v2 (D-TPL-36): Spaces: graphite, white, mint, grid and air. Cinematic hero, marquee, statement, sticky story, gallery rail, blur-in reveals. */
export const studioLook = buildLook({
  id: "studio",
  title: { es: "Estudio", en: "Studio" },
  axis: { es: "Espacios: grafito, blanco, menta, retícula y aire", en: "Spaces: graphite, white, mint, grid and air" },
  themePatch: {
    "color.background": "#17181a",
    "color.ink": "#f3f1ee",
    "color.neutral": "#f3f1ee",
    "color.primary": "#f3f1ee",
    "color.secondary": "#9a9a9a",
    "color.accent": "#9ad3c8",
    "color.muted": "#a5a5a5",
    "color.line": "#2a2c2f",
    "color.surface-raised": "#202225",
    "typography.heading-preset": "sans",
    "typography.body-preset": "refined-sans",
    "typography.scale-preset": "editorial",
    "radius.scale-preset": "soft",
    "shadow.preset": "none",
    "motion.preset": "refined",
    "density.section-padding": "airy",
    "background.mode": "noise-texture",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "espresso-column",
  },
  recipe: {
    hero: "cinematic",
    heroBand: "none",
    heroMinHeight: "100svh",
    offer: "cards",
    proofBand: "surface",
    closing: "contrast",
    gallery: "rail",
    cardVariant: "ghost",
    imageRadius: "sm",
    header: "minimal",
    footer: "line",
    headingStyle: { fontWeight: 600, letterSpacing: "-0.02em" },
    displayStyle: { size: "display", fontWeight: 600, letterSpacing: "-0.04em", textWrap: "balance" },
    eyebrowStyle: { letterSpacing: "0.24em", textTransform: "uppercase" },
    sectionPadding: "xl",
    motion: "blur-in",
    marquee: true,
    statement: true,
    story: "sticky",
    lift: true,
  },
  copyOverrides: {
    "home.statement": { es: "Un lugar hecho para trabajar bien.", en: "A place made for doing good work." },
  },
});
