import { buildLook } from "./shared";

/** Look `warm` — Looks v2 (D-TPL-36): Crafts: dark walnut, amber, soft lime, hands and material. Cinematic hero, marquee, statement, sticky story, gallery rail, rise reveals. */
export const warmLook = buildLook({
  id: "warm",
  title: { es: "Brasa suave", en: "Amber" },
  axis: { es: "Oficios: nogal oscuro, ámbar, lima suave, manos y materia", en: "Crafts: dark walnut, amber, soft lime, hands and material" },
  themePatch: {
    "color.background": "#1f1712",
    "color.ink": "#f8f1e7",
    "color.neutral": "#f8f1e7",
    "color.primary": "#ffb86b",
    "color.secondary": "#b89b84",
    "color.accent": "#c9f27a",
    "color.muted": "#b3a396",
    "color.line": "#3a2c23",
    "color.surface-raised": "#2a1f19",
    "typography.heading-preset": "serif",
    "typography.body-preset": "sans",
    "typography.scale-preset": "editorial",
    "radius.scale-preset": "soft",
    "shadow.preset": "soft",
    "motion.preset": "refined",
    "density.section-padding": "airy",
    "background.mode": "noise-texture",
    "shell.header-variant": "editorial-sticky",
    "shell.footer-variant": "espresso-column",
  },
  recipe: {
    hero: "cinematic",
    heroBand: "none",
    heroMinHeight: "100svh",
    offer: "cards",
    proofBand: "surface",
    closing: "accent",
    gallery: "rail",
    cardVariant: "elevated",
    imageRadius: "lg",
    header: "left-nav",
    footer: "columns",
    headingStyle: { fontWeight: 600 },
    displayStyle: { size: "display", fontWeight: 600, letterSpacing: "-0.02em", textWrap: "balance" },
    eyebrowStyle: { letterSpacing: "0.22em", textTransform: "uppercase" },
    sectionPadding: "xl",
    motion: "rise",
    marquee: true,
    statement: true,
    story: "sticky",
    lift: true,
  },
  copyOverrides: {
    "home.statement": { es: "Hecho a mano, pieza por pieza.", en: "Made by hand, piece by piece." },
    "home.closing.headline": { es: "Te esperamos", en: "We are expecting you" },
  },
});
