-- Catalog field-engine Spanish backfill (2026-06-15).
-- Generated from the catalog-spanish-backfill translation workflow (ES-MX, informal tu).
-- Idempotent: only fills empty ES cells, never overwrites existing translations.

-- label_es (235)
update public.profile_field_definitions as p set label_es = v.label_es, updated_at = now()
from (values
  ('about.bioTone','Tono de la bio'),
  ('about.personality','Personalidad — qué le gusta / qué evita'),
  ('admin.featureInDirectory','Destacar en el directorio'),
  ('admin.fieldLocks','Bloqueos de campos'),
  ('admin.internalNotes','Notas internas'),
  ('agency_fields.placeholder','Campos personalizados de la agencia'),
  ('albums.list','Álbumes'),
  ('availability.advance_notice_hours','Aviso previo requerido (horas)'),
  ('availability.calendar','Calendario de disponibilidad'),
  ('availability.night_work','Disponible para trabajo nocturno'),
  ('availability.recurring','Patrón recurrente'),
  ('availability.same_day_bookings','Acepta reservaciones el mismo día'),
  ('availability.vacation','Periodos de vacaciones'),
  ('bios','Bio (por idioma)'),
  ('chef.allergens_handling','Experiencia en manejo de alérgenos'),
  ('chef.certifications','Certificaciones'),
  ('chef.cleanup_included','Limpieza incluida'),
  ('chef.cleanup_policy','Política de limpieza'),
  ('chef.cuisine_types','Cocinas'),
  ('chef.dietary_specialties','Especialidades dietéticas'),
  ('chef.event_capacity_max','Capacidad máxima del evento (invitados)'),
  ('chef.event_capacity_min','Capacidad mínima del evento (invitados)'),
  ('chef.food_handler_certified','Certificado/a en manejo de alimentos'),
  ('chef.ingredients_provided','Ingredientes incluidos'),
  ('chef.kitchen_requirements','Requisitos de cocina'),
  ('chef.max_guests','Máximo de invitados'),
  ('chef.menu_examples','Ejemplos de menú (enlaces/archivos)'),
  ('chef.min_guests','Mínimo de invitados'),
  ('chef.private_chef_day_rate','Tarifa por día de chef privado'),
  ('chef.service_style','Estilo de servicio'),
  ('chef.staff_available','Personal disponible (sous, mesero)'),
  ('chef.tasting_menu_per_person','Precio del menú degustación (por persona)'),
  ('chef.villa_yacht_experience','Experiencia en villa / yate'),
  ('commerce.servicesMenu','Menú de servicios'),
  ('commercial.askForQuote','Solicitar cotización'),
  ('commercial.lodgingIncluded','Hospedaje incluido'),
  ('commercial.packageRates','Tarifas por paquete'),
  ('commercial.rateCardVisibility','Visibilidad del tarifario'),
  ('commercial.rateTiers','Niveles de tarifa por canal'),
  ('commercial.travelIncluded','Viaje incluido'),
  ('consent.terms','Términos aceptados'),
  ('creator.audience_geo','País principal de la audiencia'),
  ('creator.audience_total','Audiencia total'),
  ('creator.engagement_rate','Tasa de interacción'),
  ('creator.niche','Nicho'),
  ('creator.platforms','Plataformas'),
  ('creator.rate_per_post','Tarifa · publicación patrocinada'),
  ('creator.rate_per_reel','Tarifa · reel / video'),
  ('credits','Créditos'),
  ('documents','Documentos'),
  ('emergency.contact','Contacto de emergencia'),
  ('equipment.notes','Notas del equipo'),
  ('equipment.owns_equipment','Cuenta con equipo propio'),
  ('event.first_aid_certified','¿Certificado/a en primeros auxilios?'),
  ('event.max_shift_hours','Duración máxima del turno'),
  ('event.physical_capability','¿Puede cargar peso?'),
  ('event.role_focus','Enfoque del rol'),
  ('event.uniform_owned','Uniforme propio'),
  ('hosp.event_types','Tipos de evento'),
  ('hosp.mixology_certified','¿Certificado/a en mixología?'),
  ('hosp.pos_systems','Sistemas POS utilizados'),
  ('hosp.uniform','Uniforme propio'),
  ('host.event_types','Tipos de evento en los que te especializas'),
  ('host.max_audience_size','Tamaño máximo de audiencia'),
  ('host.mc_capable','¿Puedes ser MC?'),
  ('host.vibe','Estilo'),
  ('host.wardrobe_owned','Vestuario propio'),
  ('identity.ageDisplayMode','Modo de visualización de la edad'),
  ('identity.businessLine','Giro del negocio'),
  ('identity.contactEmail','Correo de contacto'),
  ('identity.contactPhone','Teléfono de contacto'),
  ('identity.dob','Fecha de nacimiento'),
  ('identity.home_country','País de residencia'),
  ('identity.legalName','Nombre legal'),
  ('identity.nationality','Nacionalidad'),
  ('identity.pronouns','Pronombres'),
  ('identity.pronounsCustom','Pronombres personalizados'),
  ('identity.response_time','Compromiso de tiempo de respuesta'),
  ('identity.stageName','Nombre artístico / profesional'),
  ('identity.tagline','Frase de una línea'),
  ('identity.whatsapp','WhatsApp'),
  ('kids.activity_types','Actividades que ofreces'),
  ('kids.age_groups','Grupos de edad que atiendes'),
  ('kids.background_check','Verificación de antecedentes en archivo'),
  ('kids.background_check_date','Fecha de verificación de antecedentes'),
  ('kids.brings_own_equipment','Lleva su propio equipo / props'),
  ('kids.first_aid_cpr','Certificado/a en primeros auxilios / RCP'),
  ('kids.max_group_size','Tamaño máximo del grupo'),
  ('kids.parent_presence_required','Requiere la presencia de un padre/tutor'),
  ('languages','Idiomas'),
  ('limits','Límites / vestuario'),
  ('logistics.driversLicense','Licencia de conducir'),
  ('logistics.passportStatus','Estado del pasaporte'),
  ('logistics.upcomingVisits','Próximas visitas'),
  ('logistics.visas','Visas vigentes'),
  ('logistics.workEligibility','Países donde puedes trabajar'),
  ('media.cover_photo','Foto de portada'),
  ('media.headshot','Foto headshot'),
  ('media.helloReel','Reel de presentación'),
  ('media.polaroids','Polaroids · naturales'),
  ('media.portfolio','Portafolio'),
  ('media.showreel','Video reel'),
  ('media.social_links','Enlaces de redes sociales'),
  ('media.videoLinks','Enlaces de video'),
  ('model.brand_categories','Categorías de marca con las que has trabajado'),
  ('model.content_rights_available','Derechos de contenido disponibles'),
  ('model.runway_experience','Experiencia en pasarela'),
  ('model.runway_experience_years','Años en pasarela'),
  ('model.shoot_experience','Tipos de experiencia en sesiones'),
  ('model.ugc_content_available','Contenido UGC disponible'),
  ('music.act_format','Formato'),
  ('music.bpm_range','Rango de BPM'),
  ('music.equipment','¿Llevas tu propio equipo?'),
  ('music.genres','Géneros principales'),
  ('music.key_strengths','Fortalezas principales'),
  ('music.set_length','Duración del set'),
  ('music.tech_rider','¿Tech rider adjunto?'),
  ('ops.requirements_notes','Notas de montaje / requisitos'),
  ('ops.requires_parking','Requiere estacionamiento'),
  ('ops.requires_power_outlet','Requiere toma de corriente'),
  ('ops.requires_sound_system','Requiere sistema de sonido'),
  ('ops.requires_stage','Requiere escenario'),
  ('performer.act_types','Tipo de acto'),
  ('performer.age_appropriate','Apto para edades'),
  ('performer.audience_interaction','Interacción con el público'),
  ('performer.choreography_available','Coreografía disponible'),
  ('performer.costume_options','Opciones de vestuario'),
  ('performer.dance_styles','Estilos de baile / performance'),
  ('performer.group_size','Tamaño del grupo'),
  ('performer.has_insurance','¿Cuenta con seguro?'),
  ('performer.max_height_cm','Altura máxima de rigging (m)'),
  ('performer.props_owned','Props / equipo propio'),
  ('performer.requires_rigging','Requiere rigging'),
  ('performer.show_duration_minutes','Duración típica del set'),
  ('performer.solo_or_group','Acto solo o grupal'),
  ('performer.teaching_available','Clases disponibles'),
  ('performer.travels_with_props','¿Viaja con todo el equipo?'),
  ('photo.camera_brands','Marcas de cámara propias'),
  ('photo.deliverables','Tiempo de entrega típico'),
  ('photo.drone_licensed','¿Licencia de dron?'),
  ('photo.formats','Formatos'),
  ('photo.has_insurance','¿Seguro de responsabilidad civil?'),
  ('photo.has_retoucher','¿Retocador propio?'),
  ('photo.has_studio_access','Acceso a estudio'),
  ('photo.kit_owned','Equipo propio'),
  ('physical.bust_cm','Busto'),
  ('physical.hips_cm','Cadera'),
  ('physical.inseam_cm','Entrepierna'),
  ('physical.piercings','Perforaciones'),
  ('physical.shoe_size_uk','Talla de calzado (UK)'),
  ('physical.shoe_size_us','Talla de calzado (US)'),
  ('physical.skin_tone','Tono de piel'),
  ('physical.suit_size','Talla de traje'),
  ('physical.tattoos','Tatuajes'),
  ('physical.tattoos_note','Tatuajes · ubicación y cobertura'),
  ('physical.visible_marks','Marcas distintivas'),
  ('physical.waist_cm','Cintura'),
  ('physical.weight_kg','Peso'),
  ('rates','Tarifario'),
  ('rates.cards','Tarifarios'),
  ('reviews','Reseñas'),
  ('sales.cash_handling_certified','Certificado/a en manejo de efectivo'),
  ('sales.experience_summary','Resumen de experiencia en ventas'),
  ('security.close_protection_certified','¿Certificado/a en protección personal?'),
  ('security.drug_alcohol_clean','¿Libre de drogas y alcohol en turnos?'),
  ('security.has_insurance','¿Seguro de responsabilidad civil?'),
  ('security.security_license','Licencia de seguridad'),
  ('security.training','Capacitación'),
  ('security.weapons_certified','¿Certificado/a en armas?'),
  ('service.has_drivers_license','Licencia de conducir'),
  ('service.owns_vehicle','Cuenta con vehículo'),
  ('serviceArea.homeBase','Ciudad base'),
  ('singer.audio_video_links','Muestras de audio/video'),
  ('singer.backing_tracks_available','Pistas de acompañamiento disponibles'),
  ('singer.mic_provided','Lleva su propio micrófono'),
  ('singer.performance_format','Formato de presentación'),
  ('singer.set_duration_max','Duración máxima del set (minutos)'),
  ('singer.set_duration_min','Duración mínima del set (minutos)'),
  ('singer.song_requests','Acepta peticiones de canciones'),
  ('social_proof.pastClients','Clientes anteriores'),
  ('speaker.audience_size','Tamaño de audiencia cómodo'),
  ('speaker.av_rider','Rider de AV / técnico'),
  ('speaker.credentials','Libros / certificaciones / credenciales'),
  ('speaker.delivery_languages','Idiomas de la ponencia'),
  ('speaker.formats','Formatos de charla'),
  ('speaker.sample_reel','URL de charla de muestra / reel'),
  ('speaker.talk_length','Duración típica de la charla'),
  ('speaker.topics','Áreas temáticas'),
  ('tech.callout_radius_km','Radio de cobertura'),
  ('tech.cert_docs_on_file','Documentos de certificación en archivo'),
  ('tech.emergency_available','Disponible para emergencias / mismo día'),
  ('tech.insurance_held','Seguro de responsabilidad civil vigente'),
  ('tech.licenses','Licencias de oficio / certificaciones'),
  ('tech.owns_tools','Lleva sus propias herramientas / equipo'),
  ('tech.service_categories','Categorías de servicio'),
  ('tech.years_experience','Años de experiencia'),
  ('transport.airport_meet_and_greet','Servicio de recepción en aeropuerto'),
  ('transport.airport_transfer','Servicio de traslado al aeropuerto'),
  ('transport.child_seat_count','Asientos para niños disponibles'),
  ('transport.commercial_license_type','Tipo de licencia comercial'),
  ('transport.formal_attire','¿Cuenta con vestuario formal?'),
  ('transport.full_day_service','Servicio de día completo'),
  ('transport.has_air_conditioning','El vehículo tiene AC'),
  ('transport.has_insurance','¿Seguro comercial?'),
  ('transport.hotel_pickup_experience','Experiencia en recogida en hotel'),
  ('transport.license_class','Clase de licencia'),
  ('transport.luggage_capacity','Capacidad de equipaje'),
  ('transport.max_passengers','Máximo de pasajeros'),
  ('transport.max_run_hours','Máximo de horas continuas de servicio'),
  ('transport.night_service','Servicio nocturno'),
  ('transport.vehicle_type','Tipo de vehículo'),
  ('transport.vehicle_year','Año del vehículo'),
  ('travel.commission_model','Modelo de comisión (admin)'),
  ('travel.destinations_covered','Destinos cubiertos'),
  ('travel.emergency_support_24_7','Soporte de emergencia 24/7'),
  ('travel.itinerary_planning','Planeación de itinerario'),
  ('travel.nightlife_booking','Servicio de reservación de vida nocturna'),
  ('travel.passports','Pasaportes vigentes'),
  ('travel.payment_handling','Métodos de manejo de pagos'),
  ('travel.restaurant_booking','Servicio de reservación de restaurantes'),
  ('travel.tour_categories','Categorías de tour'),
  ('travel.transportation_coordination','Coordinación de transporte'),
  ('travel.vendor_network','Red de proveedores'),
  ('travel.work_authorization','Elegibilidad para trabajar'),
  ('travel.yacht_booking','Servicio de reservación de yates'),
  ('verifications.badges','Insignias de confianza'),
  ('verifications.idVerified','Identidad verificada'),
  ('wellness.certifications','Certificaciones'),
  ('wellness.has_insurance','¿Seguro vigente?'),
  ('wellness.license_country','Jurisdicción de la licencia'),
  ('wellness.max_per_session','Máximo de clientes por sesión'),
  ('wellness.min_session_duration','Duración de la sesión'),
  ('wellness.modalities','Modalidades'),
  ('wellness.session_types','Tipos de sesión'),
  ('wellness.travels_with_kit','¿Viaja con su propio equipo?')
) as v(field_key,label_es)
where p.field_key = v.field_key and (p.label_es is null or btrim(p.label_es) = '');

-- helper_es (15)
update public.profile_field_definitions as p set helper_es = v.helper_es, updated_at = now()
from (values
  ('event_types','Formatos de evento que maneja este talento.'),
  ('fit_labels','Descriptores rápidos que aparecen en la tarjeta del directorio.'),
  ('identity.gender','Faceta pública de filtro por género. Se toma de talent_profiles.gender — nunca es texto libre.'),
  ('industries','Industrias en las que ha trabajado este talento.'),
  ('kids.activity_types','p. ej. pintacaritas, figuras con globos, magia, cuentacuentos.'),
  ('kids.age_groups','Con qué rangos de edad trabaja este talento.'),
  ('kids.background_check','Verificación de antecedentes penales / policiales completada.'),
  ('kids.background_check_date','Cuándo se completó la verificación más reciente.'),
  ('kids.max_group_size','Grupo de niños más grande con el que se siente cómodo trabajando.'),
  ('speaker.av_rider','Equipo, escenario y conectividad que necesita el ponente.'),
  ('speaker.delivery_languages','Idiomas en los que el ponente puede presentar.'),
  ('speaker.topics','Temas que cubre este ponente.'),
  ('tags','Etiquetas de descubrimiento de texto libre.'),
  ('tech.callout_radius_km','Distancia máxima dispuesto a viajar por un trabajo.'),
  ('tech.service_categories','p. ej. AV, electricidad, IT, mantenimiento, estilismo en sitio.')
) as v(field_key,helper_es)
where p.field_key = v.field_key and (p.helper_es is null or btrim(p.helper_es) = '');

-- options_es (83 fields)
update public.profile_field_definitions as p set options_es = v.opts, updated_at = now()
from (values
  ('about.bioTone','{"professional": "Profesional", "warm": "Cercano", "playful": "Divertido", "bold": "Atrevido", "minimal": "Minimalista"}'::jsonb),
  ('availability.status','{"available_now": "Disponible ahora", "available_this_week": "Disponible esta semana", "available_this_month": "Disponible este mes", "limited": "Disponibilidad limitada", "by_request": "Por solicitud", "unavailable": "No disponible"}'::jsonb),
  ('chef.cleanup_included','{"Yes": "Sí", "No": "No", "Add-on": "Adicional"}'::jsonb),
  ('chef.cleanup_policy','{"Included": "Incluida", "Add-on fee": "Costo adicional", "Client handles": "La maneja el cliente", "Negotiable": "Negociable"}'::jsonb),
  ('chef.dietary_specialties','{"Vegan": "Vegano", "Vegetarian": "Vegetariano", "Gluten-free": "Sin gluten", "Kosher": "Kosher", "Halal": "Halal", "Raw": "Crudo"}'::jsonb),
  ('chef.kitchen_requirements','{"Full pro kitchen": "Cocina profesional completa", "Basic home kitchen": "Cocina doméstica básica", "Mobile kitchen OK": "Cocina móvil OK", "Outdoor / fire OK": "Exterior / fuego OK"}'::jsonb),
  ('chef.service_style','{"Plated": "Emplatado", "Family-style": "Estilo familiar", "Tasting menu": "Menú de degustación", "Buffet": "Bufé"}'::jsonb),
  ('commercial.rateCardVisibility','{"public": "Público", "agency-only": "Solo agencia", "on-request": "Por solicitud"}'::jsonb),
  ('creator.audience_total','{"< 10k": "< 10k", "10–50k": "10–50k", "50–250k": "50–250k", "250k–1M": "250k–1M", "1M+": "1M+"}'::jsonb),
  ('creator.engagement_rate','{"< 1%": "< 1%", "1–3%": "1–3%", "3–6%": "3–6%", "6–10%": "6–10%", "10%+": "10%+"}'::jsonb),
  ('creator.platforms','{"Instagram": "Instagram", "TikTok": "TikTok", "YouTube": "YouTube", "Substack": "Substack", "Twitch": "Twitch", "X": "X"}'::jsonb),
  ('event.first_aid_certified','{"Yes · current": "Sí · vigente", "Yes · expired": "Sí · vencido", "No": "No"}'::jsonb),
  ('event.max_shift_hours','{"6h": "6h", "8h": "8h", "10h": "10h", "12h+": "12h+"}'::jsonb),
  ('event.physical_capability','{"Up to 10kg": "Hasta 10kg", "Up to 25kg": "Hasta 25kg", "Heavy lifting OK": "Carga pesada OK"}'::jsonb),
  ('event.role_focus','{"Setup": "Montaje", "Runner": "Apoyo logístico", "Coordinator": "Coordinador", "Stage manager": "Jefe de escenario", "Crowd control": "Control de multitudes"}'::jsonb),
  ('event.uniform_owned','{"Black t-shirt + pants": "Playera negra + pantalón", "All-black formal": "Formal todo negro", "Hi-vis vest": "Chaleco de alta visibilidad", "Branded (provided)": "Con logo (lo proporcionan)"}'::jsonb),
  ('experience.level','{"beginner": "Principiante", "intermediate": "Intermedio", "experienced": "Con experiencia", "professional": "Profesional", "highly_experienced": "Muy experimentado"}'::jsonb),
  ('hosp.event_types','{"Weddings": "Bodas", "Corporate": "Corporativos", "Restaurants": "Restaurantes", "Villas": "Villas", "Festivals": "Festivales", "Yachts": "Yates"}'::jsonb),
  ('hosp.mixology_certified','{"Yes · WSET": "Sí · WSET", "Yes · BarSmarts": "Sí · BarSmarts", "Yes · in-house": "Sí · interna", "No": "No"}'::jsonb),
  ('hosp.uniform','{"Black tie": "Etiqueta", "Whites": "Filipina de chef", "Casual": "Casual", "None": "Ninguno"}'::jsonb),
  ('host.event_types','{"Weddings": "Bodas", "Corporate": "Corporativos", "Launches": "Lanzamientos", "Galas": "Galas", "Private parties": "Fiestas privadas", "Press": "Prensa"}'::jsonb),
  ('host.mc_capable','{"Yes · with mic": "Sí · con micrófono", "Yes · ambient only": "Sí · solo ambiente", "No": "No"}'::jsonb),
  ('host.vibe','{"Energetic": "Enérgico", "Polished": "Pulido", "Warm": "Cercano", "Edgy": "Atrevido"}'::jsonb),
  ('host.wardrobe_owned','{"Tuxedo": "Esmoquin", "Cocktail": "Coctel", "Casual": "Casual", "Branded uniform": "Uniforme con logo", "Black tie": "Etiqueta"}'::jsonb),
  ('identity.ageDisplayMode','{"exact": "Exacta", "range": "Rango", "hidden": "Oculta"}'::jsonb),
  ('identity.gender','{"Woman": "Mujer", "Man": "Hombre", "Non-binary": "No binario", "Trans woman": "Mujer trans", "Trans man": "Hombre trans", "Transgender": "Transgénero", "Genderfluid": "Género fluido", "Genderqueer": "Genderqueer", "Agender": "Sin género", "Bigender": "Bigénero", "Two-Spirit": "Dos espíritus", "Intersex": "Intersexual", "Prefer to self-describe": "Prefiero describirme", "Prefer not to say": "Prefiero no decir"}'::jsonb),
  ('kids.age_groups','{"Toddlers (0–3)": "Bebés (0–3)", "Pre-K (4–5)": "Preescolar (4–5)", "Kids (6–9)": "Niños (6–9)", "Tweens (10–12)": "Preadolescentes (10–12)", "Teens (13+)": "Adolescentes (13+)"}'::jsonb),
  ('logistics.driversLicense','{"none": "Ninguna", "standard": "Estándar", "international": "Internacional", "commercial": "Comercial"}'::jsonb),
  ('logistics.passportStatus','{"valid": "Vigente", "expired": "Vencido", "none": "Ninguno"}'::jsonb),
  ('model.content_rights_available','{"Full buyout": "Cesión total", "Limited usage": "Uso limitado", "Social only": "Solo redes sociales", "Editorial only": "Solo editorial", "Negotiable": "Negociable"}'::jsonb),
  ('music.act_format','{"Solo DJ": "DJ solista", "Live band": "Banda en vivo", "Acoustic duo": "Dúo acústico", "Vocalist + DJ": "Vocalista + DJ", "Producer set": "Set de productor"}'::jsonb),
  ('music.equipment','{"Full setup": "Equipo completo", "Partial": "Parcial", "No equipment": "Sin equipo"}'::jsonb),
  ('music.key_strengths','{"Open format": "Formato abierto", "Vinyl": "Vinilo", "Live mashups": "Mashups en vivo", "Reading the room": "Leer al público", "MC capable": "Capacidad de MC", "Original material": "Material original"}'::jsonb),
  ('music.set_length','{"30 min": "30 min", "60 min": "60 min", "90 min": "90 min", "2 hr": "2 h", "3 hr+": "3 h+"}'::jsonb),
  ('music.tech_rider','{"Yes": "Sí", "No, I work with venue": "No, trabajo con el venue"}'::jsonb),
  ('performer.act_types','{"Solo": "Solo", "Duo": "Dúo", "Group": "Grupo", "Choreographed": "Coreografiado", "Improv": "Improvisación"}'::jsonb),
  ('performer.age_appropriate','{"All ages": "Todas las edades", "Kids events": "Eventos infantiles", "Adults only": "Solo adultos", "18+": "18+"}'::jsonb),
  ('performer.has_insurance','{"Yes · public liability": "Sí · responsabilidad civil", "Yes · public + equipment": "Sí · responsabilidad civil + equipo", "No": "No"}'::jsonb),
  ('performer.requires_rigging','{"No": "No", "Truss": "Truss", "Hard point": "Punto fijo", "Crane / lift": "Grúa / elevador"}'::jsonb),
  ('performer.solo_or_group','{"Solo": "Solo", "Duo": "Dúo", "Group": "Grupo", "Either": "Cualquiera"}'::jsonb),
  ('performer.travels_with_props','{"Yes · checked baggage": "Sí · equipaje documentado", "Yes · ships ahead": "Sí · lo envío con anticipación", "Local rentals only": "Solo rentas locales"}'::jsonb),
  ('photo.camera_brands','{"Sony": "Sony", "Canon": "Canon", "Nikon": "Nikon", "Fuji": "Fuji", "Hasselblad": "Hasselblad", "Phase One": "Phase One", "Leica": "Leica"}'::jsonb),
  ('photo.deliverables','{"24h": "24h", "3 days": "3 días", "1 week": "1 semana", "2 weeks+": "2 semanas+"}'::jsonb),
  ('photo.drone_licensed','{"Yes · EU A2": "Sí · EU A2", "Yes · FAA Part 107": "Sí · FAA Part 107", "Yes · other": "Sí · otra", "No": "No"}'::jsonb),
  ('photo.formats','{"Editorial": "Editorial", "Commercial": "Comercial", "Wedding": "Boda", "Event": "Evento", "Documentary": "Documental", "Fashion": "Moda"}'::jsonb),
  ('photo.has_insurance','{"Yes": "Sí", "No": "No"}'::jsonb),
  ('photo.has_retoucher','{"Yes · same person": "Sí · la misma persona", "Yes · trusted partner": "Sí · colaborador de confianza", "Client provides": "Lo aporta el cliente"}'::jsonb),
  ('photo.has_studio_access','{"Own studio": "Estudio propio", "Member studio": "Estudio con membresía", "Day-rents": "Renta por día", "Outdoor / location only": "Solo exteriores / locación"}'::jsonb),
  ('photo.kit_owned','{"Full studio": "Estudio completo", "Mobile pro": "Equipo móvil profesional", "Camera + lens only": "Solo cámara + lente"}'::jsonb),
  ('physical.body_type','{"Slim": "Delgado", "Athletic": "Atlético", "Curvy": "Curvilíneo", "Plus": "Talla grande", "Muscular": "Musculoso", "Other": "Otro"}'::jsonb),
  ('physical.dress_size','{"XXS": "XXS", "XS": "XS", "S": "S", "M": "M", "L": "L", "XL": "XL", "XXL": "XXL"}'::jsonb),
  ('physical.eye_color','{"Brown": "Café", "Blue": "Azul", "Green": "Verde", "Hazel": "Avellana", "Grey": "Gris", "Amber": "Ámbar", "Black": "Negro", "Other": "Otro"}'::jsonb),
  ('physical.hair_color','{"Black": "Negro", "Dark brown": "Castaño oscuro", "Brown": "Castaño", "Light brown": "Castaño claro", "Blonde": "Rubio", "Red": "Pelirrojo", "Auburn": "Castaño rojizo", "Grey": "Cano", "White": "Blanco", "Other": "Otro"}'::jsonb),
  ('physical.hair_length','{"Shaved": "Rapado", "Short": "Corto", "Medium": "Medio", "Long": "Largo", "Extra long": "Extra largo"}'::jsonb),
  ('physical.piercings','{"None": "Ninguno", "Ears only": "Solo orejas", "Visible": "Visibles", "Multiple": "Múltiples"}'::jsonb),
  ('physical.shoe_size_eu','{"35": "35", "36": "36", "37": "37", "38": "38", "39": "39", "40": "40", "41": "41", "42": "42", "43": "43", "44": "44", "45": "45", "46": "46", "47": "47", "48": "48"}'::jsonb),
  ('physical.shoe_size_uk','{"3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "10": "10", "11": "11", "12": "12", "13": "13"}'::jsonb),
  ('physical.shoe_size_us','{"5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "10": "10", "11": "11", "12": "12", "13": "13", "14": "14", "15": "15"}'::jsonb),
  ('physical.skin_tone','{"Fair": "Muy claro", "Light": "Claro", "Medium": "Medio", "Olive": "Aceitunado", "Tan": "Bronceado", "Brown": "Moreno", "Dark": "Oscuro", "Deep": "Muy oscuro"}'::jsonb),
  ('physical.suit_size','{"34": "34", "36": "36", "38": "38", "40": "40", "42": "42", "44": "44", "46": "46", "48": "48", "50": "50"}'::jsonb),
  ('physical.tattoos','{"None": "Ninguno", "Few / small": "Pocos / pequeños", "Visible": "Visibles", "Extensive": "Extensos"}'::jsonb),
  ('security.close_protection_certified','{"Yes · CP1": "Sí · CP1", "Yes · advanced": "Sí · avanzado", "No": "No"}'::jsonb),
  ('security.drug_alcohol_clean','{"Yes · always": "Sí · siempre", "On request": "A solicitud"}'::jsonb),
  ('security.has_insurance','{"Yes": "Sí", "No": "No"}'::jsonb),
  ('security.security_license','{"SIA / equivalent": "SIA / equivalente", "Armed": "Armado", "Unarmed": "Desarmado", "Pending": "Pendiente"}'::jsonb),
  ('security.training','{"Close protection": "Protección personal", "Crowd control": "Control de multitudes", "First aid": "Primeros auxilios", "De-escalation": "Desescalamiento"}'::jsonb),
  ('security.weapons_certified','{"Yes · firearm": "Sí · arma de fuego", "Yes · less-lethal only": "Sí · solo menos letal", "No": "No"}'::jsonb),
  ('singer.performance_format','{"Solo": "Solista", "With band": "Con banda", "With track": "Con pista", "A cappella": "A capela", "DJ set": "DJ set"}'::jsonb),
  ('speaker.audience_size','{"Under 25": "Menos de 25", "25–100": "25–100", "100–500": "100–500", "500–2,000": "500–2,000", "2,000+": "2,000+"}'::jsonb),
  ('speaker.formats','{"Keynote": "Conferencia magistral", "Workshop": "Taller", "Panel": "Panel", "Fireside chat": "Charla informal", "Webinar": "Webinar", "MC / Host": "MC / Anfitrión"}'::jsonb),
  ('speaker.talk_length','{"≤15 min": "≤15 min", "30 min": "30 min", "45 min": "45 min", "60 min": "60 min", "Half-day": "Medio día", "Full-day": "Día completo"}'::jsonb),
  ('transport.commercial_license_type','{"None": "Ninguna", "Standard": "Estándar", "Commercial (CDL)": "Comercial (CDL)", "Chauffeur / hackney": "Chofer / taxi", "International": "Internacional"}'::jsonb),
  ('transport.formal_attire','{"Yes · suit + tie": "Sí · traje + corbata", "Yes · livery": "Sí · uniforme de chofer", "Casual only": "Solo casual"}'::jsonb),
  ('transport.has_insurance','{"Yes": "Sí", "No": "No"}'::jsonb),
  ('transport.license_class','{"Standard": "Estándar", "Commercial": "Comercial", "Chauffeur": "Chofer"}'::jsonb),
  ('transport.luggage_capacity','{"None": "Ninguna", "1–2 bags": "1–2 maletas", "3–4 bags": "3–4 maletas", "5+ bags": "5+ maletas", "Van / large": "Van / grande"}'::jsonb),
  ('transport.vehicle_type','{"Sedan": "Sedán", "SUV": "SUV", "Van": "Van", "Sprinter": "Sprinter", "Luxury": "De lujo", "Limo": "Limusina"}'::jsonb),
  ('travel.commission_model','{"Flat fee": "Tarifa fija", "Percentage": "Porcentaje", "Tiered": "Por niveles", "Negotiable": "Negociable"}'::jsonb),
  ('travel.scope','{"local": "Local", "region": "Regional", "national": "Nacional", "international": "Internacional"}'::jsonb),
  ('wellness.has_insurance','{"Yes": "Sí", "No": "No"}'::jsonb),
  ('wellness.min_session_duration','{"30 min": "30 min", "60 min": "60 min", "90 min": "90 min", "2 hr": "2 h"}'::jsonb),
  ('wellness.session_types','{"1:1": "1:1", "Couples": "Parejas", "Group (≤6)": "Grupo (≤6)", "Group (≤20)": "Grupo (≤20)", "Workshops": "Talleres", "Retreats": "Retiros"}'::jsonb),
  ('wellness.travels_with_kit','{"Yes · table + linens": "Sí · camilla + sábanas", "Yes · mat / cushions only": "Sí · solo tapete / cojines", "No · client provides": "No · lo aporta el cliente"}'::jsonb)
) as v(field_key,opts)
where p.field_key = v.field_key and p.options_es is null;

-- rail groups + sections (27)
update public.profile_editor_section_groups set label_es='Perfil' where id='5dc7835b-c9e0-45a0-a1f2-19abe3e65927' and label_es is null;
update public.profile_editor_section_groups set label_es='Oficio' where id='325ade4b-deac-408c-b54e-73d38dda369a' and label_es is null;
update public.profile_editor_section_groups set label_es='Logística' where id='68c1d833-443a-4a73-9a31-6642926d2577' and label_es is null;
update public.profile_editor_section_groups set label_es='Portafolio', label_es_alt='Fotos del trabajo / venue' where id='9ec510f8-f66c-424e-9464-c428e8ca7c9a' and label_es is null;
update public.profile_editor_section_groups set label_es='Términos' where id='91f589c1-ed40-474e-a81c-3dcd46ee9ec4' and label_es is null;
update public.profile_editor_section_groups set label_es='Comprobantes' where id='48f1a93f-a1f3-40cb-ad2f-35f9af1a05d2' and label_es is null;
update public.profile_editor_section_groups set label_es='Back office' where id='f4cfd16a-bead-47d7-b394-51dddbf55785' and label_es is null;
update public.profile_editor_sections set label_es='Disponibilidad' where id='93d2db3b-bd94-4ad0-82cb-b84843fb49d7' and label_es is null;
update public.profile_editor_sections set label_es='Créditos' where id='d53ba26e-c3cd-4702-af62-b84140276238' and label_es is null;
update public.profile_editor_sections set label_es='Físico' where id='7dae995a-3b58-435b-a22d-b9868aae57b7' and label_es is null;
update public.profile_editor_sections set label_es='Media' where id='fb276e63-443c-41f7-849b-fb4865206e84' and label_es is null;
update public.profile_editor_sections set label_es='Archivos' where id='a8dae65b-2dcc-4606-965c-0ed31a24a7fd' and label_es is null;
update public.profile_editor_sections set label_es='Identidad' where id='d7c1fb4b-f3c1-4ea3-bf34-4f512109b65e' and label_es is null;
update public.profile_editor_sections set label_es='Tarifas' where id='cafb2397-21e0-482a-87f7-54ccb92b20f3' and label_es is null;
update public.profile_editor_sections set label_es='Álbumes' where id='75cdcc6f-84d3-46e3-a527-1b7e90c464df' and label_es is null;
update public.profile_editor_sections set label_es='Acerca de' where id='339bb11e-7cfd-46d4-a67a-2c8595b43a63' and label_es is null;
update public.profile_editor_sections set label_es='Vestuario' where id='026d6b5b-00c1-481b-b8c6-8ec6cdc7b420' and label_es is null;
update public.profile_editor_sections set label_es='Restricciones' where id='8f3cbb82-443c-4f85-8bad-00e2e20a7103' and label_es is null;
update public.profile_editor_sections set label_es='Clientes anteriores' where id='d195d399-efde-46b4-9f0d-def6ae5ab90e' and label_es is null;
update public.profile_editor_sections set label_es='Campos de agencia' where id='ae573ba3-66e0-4315-aaa4-95bee3228801' and label_es is null;
update public.profile_editor_sections set label_es='Logística' where id='38a34fca-149e-47de-8126-191efabdc41b' and label_es is null;
update public.profile_editor_sections set label_es='Ubicación' where id='65e55dfa-18a8-4354-af84-464a0b9efe10' and label_es is null;
update public.profile_editor_sections set label_es='Detalles' where id='683116c8-37c3-4ebf-8800-194cc4874fd7' and label_es is null;
update public.profile_editor_sections set label_es='Polaroids' where id='54caf40b-4798-4c45-8e20-96b2d6be14d2' and label_es is null;
update public.profile_editor_sections set label_es='Confianza' where id='2a5f8053-b834-4164-a57d-6b6d2ef11d68' and label_es is null;
update public.profile_editor_sections set label_es='Admin' where id='288e84ed-db11-427d-a86a-a604ecad0d45' and label_es is null;
update public.profile_editor_sections set label_es='Servicios' where id='b60bc5e1-3e9a-4717-af10-c529de31ea48' and label_es is null;
