-- Phase 2 · E4b — `receipt_for_code`: what a buyer sees at /r/<code>.
--
-- ONE CALL. The receipt renders an order, its lines and its admissions
-- together, and Front Door's F4 will want the same round trip when it
-- replaces the view. One function per admission would be N calls for a page
-- that always needs all of them.
--
-- SECURITY DEFINER, KEYED ON THE CODE, AND THAT IS THE ENTIRE ACCESS MODEL.
-- `admissions` has no anon policy by design -- a holder's name is not public
-- -- so an anonymous buyer can reach their admissions only through this
-- function, and only by presenting an opaque ~100-bit code that was emailed
-- to them. Possession of the code IS the credential, which is exactly why:
--
--   * THE CODE MUST BE OPAQUE. `orders.receipt_code` is generated by
--     `generateOpaqueCode` (Links Q1). A short readable code here would let
--     anyone enumerate every sale on the platform and hold every admission.
--   * THIS FUNCTION IS READ-ONLY AND MUST NEVER GET A WRITE SIBLING THAT
--     TRUSTS THE CODE. The code is on paper and in forwarded email; "a printed
--     code is not a secret" is already recorded here. Cancelling, changing a
--     party size, anything that mutates, needs fresh proof of the holder --
--     an emailed link or a session -- and is Front Door's to build. Do not
--     add it here.
--   * THE HOLDER'S EMAIL IS NOT RETURNED. Name and QR are what the buyer and
--     the door need; the email is what turns a forwarded ticket into a privacy
--     leak. A surface that genuinely needs it is a second function behind
--     proof of identity, not a field on this one.
--
-- WHAT IS RETURNED PER ADMISSION: id and token_version, which is what
-- `signAdmissionToken(id, version)` needs to draw the QR, and NOT the token
-- itself -- the signing secret lives in the app, and a database function that
-- could mint a valid ticket token is a database function that must never be
-- granted to anyone. The database says which admission and which version;
-- the app signs it.
--
-- Rows come back as one jsonb so the page does one round trip and one shape.

BEGIN;

CREATE OR REPLACE FUNCTION public.receipt_for_code(p_code text)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT jsonb_build_object(
    'order', jsonb_build_object(
      'id',            o.id,
      'tenantId',      o.tenant_id,
      'status',        o.status,
      'currency',      o.currency,
      'subtotalCents', o.subtotal_cents,
      'discountCents', o.discount_cents,
      'taxCents',      o.tax_cents,
      'totalCents',    o.total_cents,
      'createdAt',     o.created_at
    ),
    'lines', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'id',        l.id,
        'label',     l.label,
        'units',     l.units,
        'unitCents', l.unit_cents,
        'totalCents',l.total_cents,
        'sessionId', l.session_id
      ) ORDER BY l.sort_order, l.created_at)
      FROM public.order_lines l WHERE l.order_id = o.id
    ), '[]'::jsonb),
    'admissions', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'id',           a.id,
        'tokenVersion', a.token_version,
        'partySize',    a.party_size,
        'admittedCount',a.admitted_count,
        'status',       a.status,
        'holderName',   a.holder_name,
        -- holder_email DELIBERATELY ABSENT. See the header.
        'sessionId',    a.session_id,
        'startsAt',     a.starts_at,
        'lineSeq',      a.line_seq
      ) ORDER BY a.order_line_id, a.line_seq)
      FROM public.admissions a
      JOIN public.order_lines l2 ON l2.id = a.order_line_id
      WHERE l2.order_id = o.id
    ), '[]'::jsonb),
    'sessions', COALESCE((
      SELECT jsonb_agg(DISTINCT jsonb_build_object(
        'id',       s.id,
        'startsAt', s.starts_at,
        'endsAt',   s.ends_at,
        'status',   s.status,
        'eventId',  s.event_id
      ))
      FROM public.sessions s
      WHERE s.id IN (SELECT l3.session_id FROM public.order_lines l3
                      WHERE l3.order_id = o.id AND l3.session_id IS NOT NULL)
    ), '[]'::jsonb)
  )
  FROM public.orders o
  WHERE o.receipt_code = p_code
    -- A null code never matches. Without this, `p_code = NULL` is NULL, which is
    -- correctly no match -- but stating it means the next reader does not have
    -- to reason about three-valued logic to know old orders are unreachable.
    AND o.receipt_code IS NOT NULL
  LIMIT 1;
$$;

-- Anon CAN execute: this is the public receipt, and the code is the credential.
-- What anon cannot do is enumerate -- the code is ~100 bits -- or read
-- anything the function does not choose to return.
REVOKE ALL ON FUNCTION public.receipt_for_code(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.receipt_for_code(text) TO anon, authenticated;

COMMENT ON FUNCTION public.receipt_for_code(text) IS
  'The public receipt at /r/<code>. Read-only, keyed on the opaque receipt code, which IS the '
  'credential -- so this must never gain a write sibling that trusts the code (it is on paper and in '
  'forwarded email). Returns the order, its lines, its admissions and their sessions in ONE call. '
  'NEVER returns holder_email: name and QR are what a buyer and a door need; the email is what turns a '
  'forwarded ticket into a privacy leak. Returns admission id + token_version, not the token: the '
  'signing secret lives in the app and a DB function that could mint a valid ticket must never exist.';

COMMIT;
