import type { FeaturedTalentV1 } from "./schema";

export const v11FeaturedTalentPreset = {
  eyebrow: "Selected",
  headline: "Featured Talent",
  copy: "",
  sourceMode: "auto_featured_flag",
  limit: 4,
  columnsDesktop: 4,
  variant: "grid",
  layoutPreset: "v11-showcase",
  headerAlign: "center",
  cardChrome: "v11-noir",
  imageTreatment: "cinematic",
  showBookmarkIcon: true,
  actionStyle: "outline-duo",
  cardVariant: "editorial",
  showName: true,
  showPrimaryType: true,
  showSecondaryType: true,
  showCity: true,
  showLanguages: true,
  showAvailability: true,
  showBadge: false,
  parentCategoryDisplay: false,
  requestCta: { label: "Request", href: "/contact" },
  footerCta: { label: "Explore Talent", href: "/directory" },
  emptyStateText: "Featured profiles appear here as talent are added to the roster.",
  presentation: {
    background: "canvas",
    paddingTop: "editorial",
    paddingBottom: "editorial",
    containerWidth: "wide",
    align: "center",
    dividerTop: "thin-line",
  },
} as const satisfies FeaturedTalentV1;
