/**
 * Folio's DEFAULTS for the site style tokens (magazine / editorial type and
 * shape). Everything here is editable in the theme drawer and per block; the
 * talent's value always wins. Colours and type faces stay with the Look
 * (`folio-looks.ts`: Instrument Serif / Archivo / stone).
 *
 * `type.system = "magazine"` switches on the magazine type-system stylesheet
 * (square buttons, ink rules, tracked Archivo Narrow labels) — same pattern
 * as Maison's `editorial`.
 */
export const FOLIO_TOKEN_DEFAULTS: Readonly<Record<string, string>> = {
  "type.system": "magazine",
  "type.display-weight": "400",
  "type.accent-style": "italic",
  "type.accent-weight": "400",
  "type.display-tracking": "-0.02em",
  "type.display-line-height": "0.95",
  "type.body-size": "16px",
  "type.body-line-height": "1.5",
  "type.label-size": "11px",
  "type.label-weight": "600",
  "type.label-tracking": "0.18em",
  "type.hero-size": "56px",
  "type.hero-size-desktop": "110px",
  "type.hero-line-height": "0.92",
  "type.hero-line-height-desktop": "0.9",
  "type.section-title-size": "40px",
  "type.section-title-size-desktop": "72px",
  "type.lede-size": "15px",
  "type.lede-size-desktop": "17px",
  "type.logo-size": "22px",
  "type.logo-size-desktop": "22px",
  "type.nav-size": "11px",
  "type.quote-size": "22px",
  "type.group-title-size": "11px",
  "type.group-title-size-desktop": "11px",
  "type.about-title-size": "clamp(36px,5vw,64px)",
  "type.about-body-size-desktop": "17px",
  "type.footer-title-size": "36px",
  "type.footer-title-size-desktop": "56px",
  "button.variant": "fill",
  "button.radius": "0px",
  "button.height": "44px",
  "button.padding-x": "16px",
  "button.font-size": "11px",
  "button.font-weight": "600",
  "button.compact-height": "40px",
  "button.compact-padding-x": "16px",
  "button.chip-height": "34px",
  "shape.card-radius": "0px",
  "shape.image-radius": "0px",
  "shape.image-radius-desktop": "0px",
  "shape.media-radius": "0px",
  "shape.rule-width": "1px",
  "shape.thumb-radius": "0px",
  "shape.chip-radius": "0px",
  "shape.rail-radius": "0px",
  "shape.feature-radius": "0px",
  "layout.section-pad-top": "90px",
  "layout.section-pad-top-phone": "52px",
  "layout.section-pad-bottom": "0px",
  "layout.section-pad-bottom-phone": "0px",
  "layout.gutter": "40px",
  "layout.gutter-phone": "16px",
  "layout.content-max-width": "none",
  "layout.header-pad-y": "0px",
  "layout.header-pad-y-phone": "0px",
  "layout.menu-rail-width": "200px",
};
