/**
 * Maison v2's DEFAULTS for the site style tokens (the Rose proposal's type
 * and shape layer). Everything here is editable in the theme drawer and per
 * block; the talent's value always wins. Colours stay with the Look.
 */
export const MAISON_V2_TOKEN_DEFAULTS: Readonly<Record<string, string>> = {
  "type.system": "editorial",
  "type.display-weight": "450",
  "type.accent-style": "italic",
  "type.accent-weight": "400",
  "type.display-tracking": "-0.015em",
  "type.display-line-height": "1.02",
  "type.body-size": "15px",
  "type.body-line-height": "1.5",
  "type.label-size": "11px",
  "type.label-weight": "600",
  "type.label-tracking": "0.18em",
  "type.hero-size": "47px",
  "type.hero-size-desktop": "96px",
  "type.hero-line-height": ".98",
  "type.hero-line-height-desktop": ".93",
  "type.section-title-size": "34px",
  "type.section-title-size-desktop": "58px",
  "type.lede-size": "15.5px",
  "type.lede-size-desktop": "18px",
  "type.logo-size": "24px",
  "type.logo-size-desktop": "28px",
  "type.nav-size": "13.5px",
  "type.quote-size": "19px",
  "type.group-title-size": "22px",
  "type.group-title-size-desktop": "28px",
  "type.about-title-size": "clamp(32px,4vw,56px)",
  "type.about-body-size-desktop": "17px",
  "type.footer-title-size": "44px",
  "type.footer-title-size-desktop": "88px",
  "button.variant": "fill",
  "button.radius": "20px",
  "button.height": "48px",
  "button.padding-x": "22px",
  "button.font-size": "15px",
  "button.font-weight": "600",
  "button.compact-height": "36px",
  "button.compact-padding-x": "16px",
  "button.chip-height": "34px",
  "shape.card-radius": "22px",
  "shape.image-radius": "26px",
  "shape.image-radius-desktop": "34px",
  "shape.media-radius": "20px",
  "shape.rule-width": "1px",
  "shape.thumb-radius": "14px",
  "shape.chip-radius": "99px",
  "shape.rail-radius": "12px",
  "shape.feature-radius": "140px",
  "layout.section-pad-top": "84px",
  "layout.section-pad-top-phone": "40px",
  "layout.section-pad-bottom": "10px",
  "layout.section-pad-bottom-phone": "8px",
  "layout.gutter": "48px",
  "layout.gutter-phone": "18px",
  "layout.content-max-width": "none",
  "layout.header-pad-y": "14px",
  "layout.header-pad-y-phone": "10px",
  "layout.menu-rail-width": "240px",
  "layout.menu-row-gap": "17px",
};
