/**
 * disposable.ts — Disposable / throwaway email domain denylist.
 *
 * This is the S2 anti-abuse layer for the guest conversational-inquiry MVP.
 * A disposable email address lets an abusive actor bypass the email gate
 * that would otherwise link guest sessions to a real identity, and invalidates
 * the trust signals Lane E surfaces to talent (e.g. "email verified").
 *
 * ## Design decisions
 *   - Static compiled list: fast (no network), zero dependency, auditable diff.
 *   - Normalized to lowercase ASCII domain. EVERY subdomain level is checked
 *     against the list (the lookup walks each suffix down to name.tld), so a
 *     listed `mailinator.com` also catches `m.mailinator.com` and
 *     `a.b.mailinator.com` without needing each variant in the list.
 *   - The list is starter-quality (~150 well-known throwaway services). It is
 *     NOT exhaustive — new disposable providers appear weekly. For a harder
 *     gate, integrate a commercial API (Abstract API, Kickbox, ZeroBounce) on
 *     top and cache results in Redis; the function signature is stable.
 *   - Free email providers (Gmail, Yahoo, Outlook) are explicitly NOT blocked —
 *     many real clients use them. The goal is blocking throwaway services, not
 *     free providers.
 *
 * ## Usage
 * ```ts
 * import { isDisposableEmail } from "@/lib/email/disposable";
 *
 * if (isDisposableEmail(contactEmail)) {
 *   return { ok: false, code: "disposable_email", message: "..." };
 * }
 * ```
 *
 * ## Integration points (Lane A must wire this)
 * - `startGuestChatInquiry` (guest-chat-actions.ts): call `isDisposableEmail`
 *   on `input.contactEmail` BEFORE `ensureGuestClientByEmail`; return
 *   GuestChatFailure code `"disposable_email"` on match.
 */

// ---------------------------------------------------------------------------
// Starter denylist — registered domains only (no leading dot, all lowercase).
// Sorted alphabetically for easy auditing.
// ---------------------------------------------------------------------------

const DISPOSABLE_DOMAINS = new Set<string>([
  // --- A ---
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "20minutemail.com",
  "33mail.com",
  // --- B ---
  "bccto.me",
  "beefmilk.com",
  "bigstring.com",
  "binkmail.com",
  "biyac.com",
  "blondandfun.com",
  "bspooky.com",
  "bugmenot.com",
  "burnermail.io",
  // --- C ---
  "cfl.ws",
  "chacuo.net",
  "chammy.info",
  "cloakedmail.com",
  "clrmail.com",
  "cool.fr.nf",
  "courriel.fr.nf",
  "crap.2freemail.com",
  "cubiclink.com",
  // --- D ---
  "dayrep.com",
  "deadaddress.com",
  "deadletter.ga",
  "deagot.com",
  "despam.it",
  "devnullmail.com",
  "digitalsanctuary.com",
  "discardmail.com",
  "discardmail.de",
  "disposablemail.com",
  "disposablemails.com",
  "dispostable.com",
  "dodgeit.com",
  "dodgit.com",
  "dontmail.net",
  "dontsendmespam.de",
  "drdrb.com",
  "dropmail.me",
  "dudmail.com",
  "dump-email.info",
  "dumpmail.de",
  "dumpyemail.com",
  // --- E ---
  "e4ward.com",
  "email-fake.com",
  "email60.com",
  "emailfake.com",
  "emailgo.de",
  "emailias.com",
  "emailinfive.com",
  "emailisvalid.com",
  "emailmiser.com",
  "emailondeck.com",
  "emailsensei.com",
  "emailtemporanea.com",
  "emailtemporanea.net",
  "emailthe.net",
  "emailtmp.com",
  "emailwarden.com",
  "emailx.at.hm",
  "emailxfer.com",
  "emkei.cz",
  "emkei.ga",
  "ero-tube.org",
  "etranquil.com",
  "etranquil.net",
  "etranquil.org",
  "evopo.com",
  "expirebox.com",
  "explodemail.com",
  "extra.impostorabogado.com",
  "ezfill.com",
  // --- F ---
  "fakemail.fr",
  "fakemails.org",
  "fakemail.net",
  "fammix.com",
  "fansworldwide.de",
  "fastacura.com",
  "fastchevy.com",
  "fastchrysler.com",
  "fastkawasaki.com",
  "fastmazda.com",
  "fastnissan.com",
  "fastsuzuki.com",
  "fasttoyota.com",
  "fastyamaha.com",
  "filzmail.com",
  "fixmail.tk",
  "fleckens.hu",
  "flurre.com",
  "flyspam.com",
  "foobarbot.net",
  "fr33mail.info",
  "fraimax.com",
  "frapmail.com",
  "freeplnkfornow.com",
  "futuramik.com",
  // --- G ---
  "garbagemail.org",
  "get1mail.com",
  "get2mail.fr",
  "getairmail.com",
  "getmails.eu",
  "getonemail.com",
  "getonemail.net",
  "giantmail.de",
  "girlsindetention.com",
  "gishpuppy.com",
  "glitch.sx",
  "gowikibooks.com",
  "gowikicampus.com",
  "gowikicars.com",
  "gowikifilms.com",
  "gowikigames.com",
  "gowikimusic.com",
  "gowikinetwork.com",
  "gowikitravel.com",
  "gowikitv.com",
  "grandmamail.com",
  "grandmasmail.com",
  "grr.la",
  "gsrv.co.uk",
  "guerillamail.biz",
  "guerillamail.com",
  "guerillamail.de",
  "guerillamail.info",
  "guerillamail.net",
  "guerillamail.org",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "gustr.com",
  // --- H ---
  "h8s.org",
  "haltospam.com",
  "hatespam.org",
  "herp.in",
  "hidemail.de",
  "hidzz.com",
  "hmamail.com",
  "hopemail.biz",
  "humaility.com",
  "hushmail.com",
  // --- I ---
  "ieh-mail.de",
  "imails.info",
  "inbound.plus",
  "inboxalias.com",
  "inboxclean.com",
  "inboxclean.org",
  "incognitomail.com",
  "incognitomail.net",
  "incognitomail.org",
  "infocom.zp.ua",
  "insorg-mail.info",
  "instant-mail.de",
  "instantemailaddress.com",
  "ipoo.org",
  "irish2me.com",
  "iwi.net",
  // --- J ---
  "jetable.com",
  "jetable.fr.nf",
  "jetable.net",
  "jetable.org",
  "jnxjn.com",
  "joymailbox.com",
  "junk1.tk",
  "junkmail.gq",
  "junkmail.ro",
  // --- K ---
  "kasmail.com",
  "kaspop.com",
  "killmail.com",
  "killmail.net",
  "kimsdisk.com",
  "koszmail.pl",
  "kulturbetrieb.info",
  "kurzepost.de",
  // --- L ---
  "l33r.eu",
  "labetteraverouge.at",
  "landmail.co",
  "lastmail.co",
  "letthemeatspam.com",
  "lhsdv.com",
  "libox.fr",
  "lifebyfood.com",
  "link2mail.net",
  "litedrop.com",
  "lol.ovpn.to",
  "lortemail.dk",
  "luv2.us",
  "lzoaq.com",
  // --- M ---
  "m4ilweb.info",
  "mail-filter.com",
  "mail-temporaire.fr",
  "mail.by",
  "mail1a.de",
  "mail1url.com",
  "mail2rss.org",
  "mail333.com",
  "mail4trash.com",
  "mailbidon.com",
  "mailblocks.com",
  "mailbucket.org",
  "mailcat.biz",
  "mailcatch.com",
  "maildrop.cc",
  "mailed.ro",
  "mailexpire.com",
  "mailf5.com",
  "mailfall.com",
  "mailfree.ga",
  "mailfreeonline.com",
  "mailguard.me",
  "mailhazard.com",
  "mailhazard.us",
  "mailhz.me",
  "mailimate.com",
  "mailinator.com",
  "mailinator.gq",
  "mailinator.net",
  "mailinator.org",
  "mailinator.us",
  "mailinator2.com",
  "mailincubator.com",
  "mailismagic.com",
  "mailme.ir",
  "mailme.lv",
  "mailme24.com",
  "mailmetrash.com",
  "mailmoat.com",
  "mailnew.com",
  "mailnull.com",
  "mailpick.biz",
  "mailproxsy.com",
  "mailquack.com",
  "mailrock.biz",
  "mailscrap.com",
  "mailseal.de",
  "mailshell.com",
  "mailsiphon.com",
  "mailslite.com",
  "mailsource.info",
  "mailspam.me",
  "mailspoint.com",
  "mailt.net",
  "mailtemp.info",
  "mailtome.de",
  "mailtothis.com",
  "mailtrash.net",
  "mailtv.net",
  "mailtv.tv",
  "mailunk.com",
  "mailvault.com",
  "mailw.info",
  "mailwithyou.com",
  "mailzilla.com",
  "mailzilla.org",
  "makemetheking.com",
  "manybrain.com",
  "mbx.cc",
  "mega.zik.dj",
  "meltmail.com",
  "messagebeamer.de",
  "mezimages.net",
  "ministry-of-silly-walks.de",
  "mintemail.com",
  "miralemailing.com",
  "mjukglass.nu",
  "mobi.web.id",
  "mockmyid.com",
  "mohmal.com",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "mtmdev.com",
  "mucincanon.com",
  "mugglenet.com",
  "mx0.wwwnew.eu",
  "mycleaninbox.net",
  "mypartyclip.de",
  "myphantomemail.com",
  "mysamp.de",
  "mytempemail.com",
  "mytempmail.com",
  // --- N ---
  "nada.email",
  "nada.ltd",
  "napalm51.com",
  "navarac.com",
  "neomailbox.com",
  "nepwk.com",
  "nervmich.net",
  "nervtmich.net",
  "netmails.com",
  "netmails.net",
  "netzidiot.de",
  "nh3.ro",
  "nice-4u.com",
  "niklasb.com",
  "no-spam.ws",
  "nobulk.com",
  "nomail.pw",
  "nomail.xl.cx",
  "nomail2me.com",
  "nomorespamemails.com",
  "nonspam.eu",
  "nonspammer.de",
  "nospam.ze.tc",
  "nospam4.us",
  "nospamfor.us",
  "nospammail.net",
  "notmailinator.com",
  "nowmymail.net",
  // --- O ---
  "objectmail.com",
  "obobbo.com",
  "odnorazovoe.ru",
  "one-time.email",
  "oneoffemail.com",
  "onewaymail.com",
  "onlatedotcom.info",
  "online.ms",
  "opayq.com",
  "ordinaryamerican.net",
  "otherinbox.com",
  "ourklips.com",
  "outloook.com",
  "ovpn.to",
  "owlpic.com",
  // --- P ---
  "pancakemail.com",
  "paplease.com",
  "pcusers.otherinbox.com",
  "pepbot.com",
  "pfui.ru",
  "pimpedupmyspace.com",
  "pjjkp.com",
  "plexolan.de",
  "poczta.onet.pl",
  "poofy.org",
  "pookmail.com",
  "postacı.com",
  "ppetw.com",
  "privy-mail.com",
  "privymail.de",
  "proxymail.eu",
  "prtnx.com",
  "prtz.eu",
  "publicmail.info",
  "punkass.com",
  // --- Q ---
  "qibl.at",
  "quickinbox.com",
  "quickmail.nl",
  "qs.dp76.com",
  // --- R ---
  "rcpt.at",
  "re-gister.com",
  "reallymymail.com",
  "recode.me",
  "recyclemail.dk",
  "regbypass.com",
  "regbypass.comsafe-mail.net",
  "rejectmail.com",
  "rklips.com",
  "rmqkr.net",
  "rn.com",
  "rpst.de",
  "rtrtr.com",
  // --- S ---
  "s0ny.net",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "selfdestructingmail.com",
  "selfdestructingmail.org",
  "sendspamhere.com",
  "sharklasers.com",
  "shiftmail.com",
  "shitmail.org",
  "shitware.nl",
  "shortmail.net",
  "sibmail.com",
  "sinnlos-mail.de",
  "skeefmail.com",
  "slapsfromlastnight.com",
  "slaskpost.se",
  "slopsbox.com",
  "smellfear.com",
  "smellfear.org",
  "snkmail.com",
  "sofimail.com",
  "sofort-mail.de",
  "sogetthis.com",
  "soisz.com",
  "spam-be-gone.com",
  "spam.la",
  "spam.mn",
  "spam.su",
  "spam4.me",
  "spamavert.com",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spamcero.com",
  "spamcon.org",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "spamgoes.in",
  "spamgourmet.com",
  "spamgourmet.net",
  "spamgourmet.org",
  "spamgroupies.com",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamoff.de",
  "spamslicer.com",
  "spamspot.com",
  "spamstack.net",
  "spamthis.co.uk",
  "spamthisplease.com",
  "spamtrail.com",
  "spamtroll.net",
  "speed.1s.fr",
  "splyc.com",
  "squizzy.de",
  "ssoia.com",
  "startkeys.com",
  "stinkefinger.net",
  "stop-my-spam.com",
  "streetwisemail.com",
  "stumpfwerk.com",
  "stuffmail.de",
  "supergreatmail.com",
  "supermailer.jp",
  "superrito.com",
  "superstachel.de",
  "suremail.info",
  "svk.jp",
  "sweetxxx.de",
  // --- T ---
  "tafmail.com",
  "tapchicuocsong.com",
  "techemail.com",
  "tele2.fr",
  "teleosaurs.xyz",
  "temp-mail.de",
  "temp-mail.io",
  "temp-mail.org",
  "temp-mail.ru",
  "temp.emeraldwebmail.com",
  "temp.headstrong.de",
  "tempalias.com",
  "tempe-mail.com",
  "tempemail.biz",
  "tempemail.co.za",
  "tempemail.com",
  "tempemail.net",
  "tempemail.us",
  "tempes.ga",
  "tempinbox.co.uk",
  "tempinbox.com",
  "tempmail.com",
  "tempmail.de",
  "tempmail.eu",
  "tempmail.io",
  "tempmail.it",
  "tempmail.net",
  "tempmail.org",
  "tempmail.us",
  "tempmail2.com",
  "tempr.email",
  "tempsky.com",
  "thankyou2010.com",
  "thecloudindex.com",
  "thisisnotmyrealemail.com",
  "throwam.com",
  "throwaway.email",
  "throwam.com",
  "throwamailaway.com",
  "throya.com",
  "tilien.com",
  "tittbit.in",
  "tmdlondon.com",
  "tmpjr.me",
  "tmailbox.com",
  "tmail.ws",
  "toiea.com",
  "toomail.biz",
  "totalvista.com",
  "tradermail.info",
  "trash-mail.at",
  "trash-mail.com",
  "trash-mail.de",
  "trash-mail.io",
  "trash-mail.me",
  "trash-me.com",
  "trashcanmail.com",
  "trashdevil.com",
  "trashdevil.de",
  "trashemail.de",
  "trashmail.at",
  "trashmail.com",
  "trashmail.de",
  "trashmail.io",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.xyz",
  "trashmailer.com",
  "trashocean.com",
  "trashtipper.com",
  "trasz.com",
  "trayna.com",
  "trbvm.com",
  "trollproject.com",
  "tryst.ch",
  "ttttt.tk",
  "tuffmail.info",
  "turoid.com",
  "turual.com",
  "twinmail.de",
  "tyldd.com",
  // --- U ---
  "uggsrock.com",
  "umail.net",
  "unids.com",
  "uroid.com",
  // --- V ---
  "valemail.net",
  "venompen.com",
  "viditag.com",
  "viewcastmedia.com",
  "viewcastmedia.net",
  "viewcastmedia.org",
  // --- W ---
  "w3internet.co.uk",
  "webemail.me",
  "webm4il.info",
  "wegwerfadresse.de",
  "wegwerfemail.com",
  "wegwerfemail.de",
  "wegwerfemail.net",
  "wegwerfemail.org",
  "wegwerfmail.com",
  "wegwerfmail.de",
  "wegwerfmail.info",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "welikecookies.com",
  "wh4f.org",
  "whyspam.me",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "wilemail.com",
  "wintersun.us",
  "wizedux.com",
  "wkhaiii.com",
  "wmailco.com",
  "wmrmail.com",
  "wronghead.com",
  "wuzupmail.net",
  // --- X ---
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xmaily.com",
  "xoxy.net",
  "xyzfree.net",
  // --- Y ---
  // NOTE: yandex.com intentionally NOT listed — it is a mainstream consumer
  // mailbox provider (real clients use it); blocking it rejected legitimate
  // senders with "disposable_email".
  "yeah.net",
  "yep.it",
  "youmail.ga",
  "yourdomain.com",
  "yuurok.com",
  "y7mail.com",
  // --- Z ---
  "z1p.biz",
  "za.com",
  "zehnminuten.de",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoemail.net",
  "zoemail.org",
  "zomail.org",
  "ztc-freemail.com",
]);

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Normalize an email string to its domain component, lower-cased.
 * Returns null when the email is malformed (no @ or empty domain).
 */
function extractDomain(email: string): string | null {
  const trimmed = email.trim().toLowerCase();
  const at = trimmed.lastIndexOf("@");
  if (at < 0) return null;
  const domain = trimmed.slice(at + 1);
  return domain.length > 0 ? domain : null;
}

/**
 * Returns true when the email's domain — at ANY subdomain level — is on the
 * disposable-service denylist.
 *
 * Walks every progressively-shorter suffix of the domain, not just one strip:
 * `user@a.b.mailinator.com` is checked as `a.b.mailinator.com`,
 * `b.mailinator.com`, then `mailinator.com` (match). This catches multi-level
 * subdomain throwaways that a single leftmost-strip would miss. The walk stops
 * at two labels (a registrable domain is at least `name.tld`).
 *
 * Does NOT do network I/O — purely set membership.
 */
export function isDisposableEmail(email: string): boolean {
  const domain = extractDomain(email);
  if (!domain) return false;

  const parts = domain.split(".");
  // Check the full domain and every shorter suffix down to the 2-label
  // registrable domain (i < parts.length - 1 keeps at least name.tld).
  for (let i = 0; i <= parts.length - 2; i++) {
    const candidate = parts.slice(i).join(".");
    if (DISPOSABLE_DOMAINS.has(candidate)) return true;
  }

  return false;
}

/**
 * Expose the denylist size for observability / tests.
 */
export function getDisposableDomainCount(): number {
  return DISPOSABLE_DOMAINS.size;
}
