/** EN + ES copy for the theme release manager (no em dashes). */
export type Lang = "en" | "es";

export const COPY = {
  en: {
    eyebrow: "Builder Lab",
    designsTitle: "Designs",
    designsLead:
      "Every talent design with its current version, how many sites sit on each version, and its open releases.",
    back: "Builder Lab",
    current: "Current version",
    sitesOn: "Sites per version",
    noSites: "No sites yet",
    openReleases: "Open releases",
    noReleases: "No open release",
    open: "Open",
    unpinned: "unpinned",
    channel: { draft: "Draft", demos: "Demos", optin: "Opt-in", default: "Default" },
    status: { draft: "draft", published: "published", paused: "paused", archived: "archived" },
    releaseTitle: "Release",
    designsLink: "Designs",
    versionMove: "Version",
    notesTitle: "Release notes",
    notesEn: "Notes (English)",
    notesEs: "Notes (Spanish)",
    itemsTitle: "What changed",
    itemsLead: "Generated from the design diff. Set the type, write the notes, add a screenshot if it helps.",
    noItems: "No items were generated for this release.",
    noBase: "sites have no exact base version (no snapshot for their pinned version). For them only new blocks can be offered.",
    type: "Type",
    typeNames: {
      code: "Code fix",
      "token-default": "Style default",
      "variant-default": "Section default",
      "new-block": "New block",
      layout: "Layout",
      critical: "Critical",
    },
    critical: "Critical (forced, announced)",
    noteEn: "Note (EN)",
    noteEs: "Note (ES)",
    screenshot: "Screenshot URL (https)",
    missingNotes: "items still need an EN and ES note",
    save: "Save changes",
    saved: "Saved.",
    dryTitle: "Dry run",
    dryLead: "Merges this release into every site on the design in memory. Nothing is written.",
    dryRun: "Run dry run",
    running: "Running...",
    dryNone: "No dry run yet. Run one before any channel change.",
    dryStale: "Items changed since this report. Run it again.",
    dryAt: "Generated",
    clean: "Clean",
    kept: "Kept edits",
    conflicts: "Conflicts",
    errors: "Errors",
    total: "Total",
    demosRow: "Demos",
    allRow: "All sites",
    drill: "Per site",
    demoTag: "demo",
    keptWhat: "Kept",
    conflictWhat: "Conflict",
    channelsTitle: "Channels",
    channelsLead: "One step at a time. Each step needs a fresh dry run with no failed sites.",
    toDemos: "Publish to demos",
    toOptin: "Open to talents (opt-in)",
    toDefault: "Make default",
    confirmOptin: "This notifies talents on this design. Continue?",
    confirmDemos: "This re-applies the design to every demo of this design. Continue?",
    confirmDefault: "Make this release the default for new applies?",
    rolloutTitle: "Rollout",
    rolloutLead: "Share of talent sites that get the notice. Raising it later notifies only the newly included sites.",
    rolloutSet: "Set rollout",
    pause: "Pause release",
    resume: "Resume release",
    done: "Done.",
    demosDone: "demos updated",
    noticesDone: "notices created",
    bellsDone: "bell entries",
    cacheWarn: "Warning, page cache not cleared",
  },
  es: {
    eyebrow: "Builder Lab",
    designsTitle: "Diseños",
    designsLead:
      "Cada diseño de talento con su versión actual, cuántos sitios hay en cada versión y sus lanzamientos abiertos.",
    back: "Builder Lab",
    current: "Versión actual",
    sitesOn: "Sitios por versión",
    noSites: "Aún no hay sitios",
    openReleases: "Lanzamientos abiertos",
    noReleases: "Sin lanzamientos abiertos",
    open: "Abrir",
    unpinned: "sin fijar",
    channel: { draft: "Borrador", demos: "Demos", optin: "Opcional", default: "Predeterminado" },
    status: { draft: "borrador", published: "publicado", paused: "en pausa", archived: "archivado" },
    releaseTitle: "Lanzamiento",
    designsLink: "Diseños",
    versionMove: "Versión",
    notesTitle: "Notas del lanzamiento",
    notesEn: "Notas (inglés)",
    notesEs: "Notas (español)",
    itemsTitle: "Qué cambió",
    itemsLead: "Generado a partir de la diferencia del diseño. Elige el tipo, escribe las notas y agrega una captura si ayuda.",
    noItems: "No se generaron elementos para este lanzamiento.",
    noBase: "sitios no tienen versión base exacta (sin instantánea de su versión fijada). Para ellos solo se pueden ofrecer bloques nuevos.",
    type: "Tipo",
    typeNames: {
      code: "Arreglo de código",
      "token-default": "Estilo predeterminado",
      "variant-default": "Sección predeterminada",
      "new-block": "Bloque nuevo",
      layout: "Distribución",
      critical: "Crítico",
    },
    critical: "Crítico (forzado, se anuncia)",
    noteEn: "Nota (EN)",
    noteEs: "Nota (ES)",
    screenshot: "URL de captura (https)",
    missingNotes: "elementos aún necesitan nota en EN y ES",
    save: "Guardar cambios",
    saved: "Guardado.",
    dryTitle: "Prueba en seco",
    dryLead: "Combina este lanzamiento con cada sitio del diseño en memoria. No se escribe nada.",
    dryRun: "Ejecutar prueba",
    running: "Ejecutando...",
    dryNone: "Aún no hay prueba. Ejecuta una antes de cambiar de canal.",
    dryStale: "Los elementos cambiaron desde este informe. Ejecútalo de nuevo.",
    dryAt: "Generado",
    clean: "Limpios",
    kept: "Ediciones conservadas",
    conflicts: "Conflictos",
    errors: "Errores",
    total: "Total",
    demosRow: "Demos",
    allRow: "Todos los sitios",
    drill: "Por sitio",
    demoTag: "demo",
    keptWhat: "Conservado",
    conflictWhat: "Conflicto",
    channelsTitle: "Canales",
    channelsLead: "Un paso a la vez. Cada paso pide una prueba reciente sin sitios fallidos.",
    toDemos: "Publicar en demos",
    toOptin: "Abrir a talentos (opcional)",
    toDefault: "Hacer predeterminado",
    confirmOptin: "Esto avisa a los talentos de este diseño. ¿Continuar?",
    confirmDemos: "Esto vuelve a aplicar el diseño a cada demo de este diseño. ¿Continuar?",
    confirmDefault: "¿Hacer este lanzamiento el predeterminado para nuevas aplicaciones?",
    rolloutTitle: "Despliegue",
    rolloutLead: "Porcentaje de sitios de talento que reciben el aviso. Subirlo después avisa solo a los sitios nuevos.",
    rolloutSet: "Fijar despliegue",
    pause: "Pausar lanzamiento",
    resume: "Reanudar lanzamiento",
    done: "Listo.",
    demosDone: "demos actualizados",
    noticesDone: "avisos creados",
    bellsDone: "entradas de campana",
    cacheWarn: "Aviso, no se limpió la caché de la página",
  },
} as const;

export function langOf(v: string | undefined): Lang {
  return v === "es" ? "es" : "en";
}
