/** EN + ES copy for the "Rebuild demos" control (no em dashes). */
export const DEMO_REBUILD_COPY = {
  en: {
    title: "Rebuild demos",
    lead: "Rebuilds every demo talent on this design from the design itself. Only demo profiles are ever written. A backup is kept so each one can be restored.",
    preview: "Preview changes",
    previewing: "Checking...",
    elapsed: (sec: number) => `Still checking, ${sec}s. Reading every demo can take up to 30 seconds.`,
    timeout: "This is taking too long (over 30 seconds). Nothing was published.",
    retry: "Try again",
    previewTitle: "What would change",
    noDemos: "This design has no demos to rebuild.",
    nothingToDo: "Every demo is already up to date.",
    rebuild: (n: number) => `Rebuild and publish ${n} ${n === 1 ? "demo" : "demos"}`,
    rebuilding: "Rebuilding...",
    confirm: (n: number, design: string) =>
      `This rewrites ${n} ${n === 1 ? "demo" : "demos"} on ${design} and publishes ${n === 1 ? "it" : "them"}. Real talents and QA users are not touched. A backup is kept. Continue?`,
    confirmYes: "Continue",
    confirmCancel: "Cancel",
    resultTitle: "Result",
    restore: "Restore",
    restoring: "Restoring...",
    restored: "Restored.",
    colDemo: "Demo",
    colVersion: "Version",
    colStatus: "Status",
    colChanged: "Changed",
    none: "nothing",
    status: {
      unchanged: "Up to date",
      would_write: "Would change",
      wrote: "Rebuilt",
      refused: "Refused",
      failed: "Failed",
    },
    steps: {
      guard: "safety check",
      backup: "backup",
      content: "content",
      hero_facts: "hero facts",
      location: "location",
      design: "design",
      publish: "publish",
      cache: "page cache",
    },
    genericError: "Something went wrong. Nothing was published.",
  },
  es: {
    title: "Reconstruir demos",
    lead: "Reconstruye cada talento demo de este diseño a partir del propio diseño. Solo se escriben perfiles demo. Se guarda una copia para poder restaurar cada uno.",
    preview: "Ver cambios",
    previewing: "Revisando...",
    elapsed: (sec: number) => `Sigue revisando, ${sec}s. Leer cada demo puede tardar hasta 30 segundos.`,
    timeout: "Esto tarda demasiado (más de 30 segundos). No se publicó nada.",
    retry: "Intentar de nuevo",
    previewTitle: "Qué cambiaría",
    noDemos: "Este diseño no tiene demos para reconstruir.",
    nothingToDo: "Todos los demos ya están al día.",
    rebuild: (n: number) => `Reconstruir y publicar ${n} ${n === 1 ? "demo" : "demos"}`,
    rebuilding: "Reconstruyendo...",
    confirm: (n: number, design: string) =>
      `Esto reescribe ${n} ${n === 1 ? "demo" : "demos"} en ${design} y ${n === 1 ? "lo publica" : "los publica"}. Los talentos reales y usuarios de QA no se tocan. Se guarda una copia. ¿Continuar?`,
    confirmYes: "Continuar",
    confirmCancel: "Cancelar",
    resultTitle: "Resultado",
    restore: "Restaurar",
    restoring: "Restaurando...",
    restored: "Restaurado.",
    colDemo: "Demo",
    colVersion: "Versión",
    colStatus: "Estado",
    colChanged: "Cambios",
    none: "nada",
    status: {
      unchanged: "Al día",
      would_write: "Cambiaría",
      wrote: "Reconstruido",
      refused: "Rechazado",
      failed: "Falló",
    },
    steps: {
      guard: "revisión de seguridad",
      backup: "copia",
      content: "contenido",
      hero_facts: "datos del encabezado",
      location: "ubicación",
      design: "diseño",
      publish: "publicación",
      cache: "caché de la página",
    },
    genericError: "Algo salió mal. No se publicó nada.",
  },
} as const;
